var attacks = {
  "Alley Rat/Rat Funk Attack": {
    type: "block",
    perfect: 50,
    partialStart: 42,
    partialEnd: 63,
    video: "./resources/ratfunkphysical.mp4",
    poster: "./resources/ratfunkphysical.png",
    name: "Alley Rat/Rat Funk Attack",
    info: "Right when the tail comes down",
    note: "Partial block resumes when the tail comes up",
    frames: 5,
  },
  "Amanita Attack": {
    type: "block",
    perfect: 75,
    partialStart: 67,
    partialEnd: 88,
    video: "./resources/AmanitaAttack.mp4",
    poster: "./resources/AmanitaAttack.png",
    name: "Amanita Attack",
    info: "When the mushroom cap is fully curled",
    note: "",
    frames: 5,
  },
  "Ameboid Attack": {
    type: "block",
    perfect: 160,
    partialStart: 152,
    partialEnd: 172,
    video: "./resources/ameboid-attack.mp4",
    poster: "./resources/ameboid-attack.png",
    name: "Ameboid Attack",
    info:
      "First frame the Ameboid is extended to hit you, plus the four frames prior",
    note: "",
    frames: 5,
  },
  "Artichoker/Kriffid Attack": {
    type: "block",
    perfect: 140,
    partialStart: 132,
    partialEnd: 153,
    video: "./resources/ArtichokerAttack.mp4",
    poster: "./resources/ArtichokerAttack.png",
    name: "Artichoker/Kriffid Attack",
    info: "Before the walk animation ends and his head goes back in",
    note: "",
    frames: 5,
  },
  "Artichoker Ball": {
    type: "block",
    perfect: 233,
    partialStart: 225,
    partialEnd: 246,
    video: "./resources/ArtichokerBall.mp4",
    poster: "./resources/ArtichokerBall.png",
    name: "Artichoker Ball",
    info: "As the third splash appears",
    note: "",
    frames: 5,
  },
  "Apprentice Attack": {
    type: "block",
    perfect: 56,
    partialStart: 48,
    partialEnd: 69,
    video: "./resources/apprenticeattack.mp4",
    poster: "./resources/apprenticeattack.png",
    name: "Apprentice Attack",
    info: "When their lips look like Birdo's (5 frames)",
    note: "",
    frames: 5,
  },
  "Arachne/Spinthra Attack": {
    type: "block",
    perfect: 59,
    partialStart: 51,
    partialEnd: 72,
    video: "./resources/arachne.mp4",
    poster: "./resources/arachne.png",
    name: "Arachne/Spinthra Attack",
    info: "When Arachne lunges in to bite",
    note: "",
    frames: 5,
  },
  "Armored Ant/Shogun Attack": {
    type: "block",
    perfect: 50,
    partialStart: 42,
    partialEnd: 62,
    video: "./resources/shogun_attack.mp4",
    poster: "./resources/shogun_attack.png",
    name: "Armored Ant/Shogun Attack",
    info: "Time the instant before Shogun raises axe to max height",
    note: "",
    frames: 5,
  },
  "Axem Black Attack": {
    type: "block",
    perfect: 69,
    partialStart: 61,
    partialEnd: 82,
    video: "./resources/axemblack.mp4",
    poster: "./resources/axemblack.png",
    name: "Axem Black Attack",
    info: "When his axe is finished swinging (5 frames)",
    note: "",
    frames: 5,
  },
  "Axem Green Attack": {
    type: "block",
    perfect: 117,
    partialStart: 109,
    partialEnd: 129,
    video: "./resources/axem_green_attack.mp4",
    poster: "./resources/axem_green_attack.png",
    name: "Axem Green Attack",
    info: "First blockable on the pull-back from the first thrust",
    note: "",
    frames: 5,
  },
  "Axem Pink Counter": {
    type: "block",
    perfect: 75,
    partialStart: 67,
    partialEnd: 87,
    video: "./resources/machinemadepink-attack1.mp4",
    poster: "./resources/machinemadepink-attack1.png",
    name: "Axem Pink Counter",
    info: "Starts the third frame Pink relaxes slightly after the swing",
    note: "",
    frames: 5,
  },
  "Axem Red Attack": {
    type: "block",
    perfect: 73,
    partialStart: 65,
    partialEnd: 85,
    video: "./resources/axem_red_attack.mp4",
    poster: "./resources/axem_red_attack.png",
    name: "Axem Red Attack",
    info: "First blockable post-swing and pre-audio cue",
    note: "",
    frames: 5,
  },
  "Axem Red Orb": {
    type: "block",
    perfect: 44,
    partialStart: 36,
    partialEnd: 56,
    video: "./resources/axem_red_attack_2.mp4",
    poster: "./resources/axem_red_attack_2.png",
    name: "Axem Red Orb",
    info: "First blockable when orb is about halfway between Red and target",
    note: "",
    frames: 5,
  },
  "Axem Yellow Attack": {
    type: "block",
    perfect: 208,
    partialStart: 200,
    partialEnd: 221,
    video: "./resources/axemyellow1.mp4",
    poster: "./resources/axemyellow1.png",
    name: "Axem Yellow Attack",
    info:
      "When his axe is statically pointing at you after the swing (5 frames)",
    note: "",
    frames: 5,
  },
  "Axem Yellow Blob": {
    type: "block",
    perfect: 228,
    partialStart: 220,
    partialEnd: 241,
    video: "./resources/axemyellow2.mp4",
    poster: "./resources/axemyellow2.png",
    name: "Axem Yellow Blob",
    info: "About halfway through the splash animation (5 frames)",
    note: "",
    frames: 5,
  },
  "Axem Yellow Body Slam": {
    type: "block",
    perfect: 173,
    partialStart: 165,
    partialEnd: 185,
    video: "./resources/axem_yellow_body_slam.mp4",
    poster: "./resources/axem_yellow_body_slam.png",
    name: "Axem Yellow Body Slam",
    info: "First blockable post-spin and when axe is brought down in chop",
    note:
      "Awkward timing. Shoot for the instant you think you'll hear the audio cue",
    frames: 5,
  },
  "Bahamutt Bite": {
    type: "block",
    perfect: 43,
    partialStart: 35,
    partialEnd: 56,
    video: "./resources/Bahamutt_Bite.mp4",
    poster: "./resources/Bahamutt_Bite.png",
    name: "Bahamutt Bite",
    info:
      "Bahamutt will rear it's head back, soon as you see him shut his mouth press block",
    note: "The moment is just when his mouth closes",
    frames: 5,
  },
  "Bahamutt Rock": {
    type: "block",
    perfect: 138,
    partialStart: 130,
    partialEnd: 151,
    video: "./resources/Bahamutt_Rock_Attack.mp4",
    poster: "./resources/Bahamutt_Rock_Attack.png",
    name: "Bahamutt Rock",
    info: "Soon as the debris from the rock is behind you, hit block",
    note: "",
    frames: 5,
  },
  "Bandana Blue/Bandana Red Attack": {
    type: "block",
    perfect: 48,
    partialStart: 40,
    partialEnd: 60,
    video: "./resources/bandanablueattack.mp4",
    poster: "./resources/bandanablueattack.png",
    name: "Bandana Blue/Bandana Red Attack",
    info:
      "First blockable on final frame of spear the farthest back before second stab. (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Bandana Blue Pierce": {
    type: "block",
    perfect: 125,
    partialStart: 117,
    partialEnd: 133,
    video: "./resources/bandanabluepierce.mp4",
    poster: "./resources/bandanabluepierce.png",
    name: "Bandana Blue Pierce",
    info: "First blockable at the end of the last stab. (5 frames)",
    note:
      "(partial block only has 4 frames after end of perfect block, instead of the regular 8)",
    frames: 5,
    relevant: true,
  },
  "Bandana Red Skewer": {
    type: "block",
    perfect: 128,
    partialStart: 120,
    partialEnd: 141,
    video: "./resources/skewer.mp4",
    poster: "./resources/skewer.png",
    name: "Bandana Red Skewer",
    info: "First blockable at the end of the last stab. (5 frames)",
    frames: 5
  },
  "Belome Attack": {
    type: "block",
    perfect: 44,
    partialStart: 36,
    partialEnd: 56,
    video: "./resources/belomeattack.mp4",
    poster: "./resources/belomeattack.png",
    name: "Belome Attack",
    info:
      "First blockable when tongue curls first above Belome's snout. (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Birdo Attack": {
    type: "block",
    perfect: 89,
    partialStart: 81,
    partialEnd: 102,
    video: "./resources/birdo.mp4",
    poster: "./resources/birdo.png",
    name: "Birdo Attack",
    info: "Right after the last egg disappears (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Birdy/Bluebird Attack": {
    type: "block",
    perfect: 100,
    partialStart: 93,
    partialEnd: 112,
    video: "./resources/birdy-attack.mp4",
    poster: "./resources/birdy-attack.png",
    name: "Birdy/Bluebird Attack",
    info: "2 frames before through 2 frames after the spear is fully extended",
    note: "",
    frames: 5,
  },
  "Birdy/Bluebird Grinder": {
    type: "block",
    perfect: 107,
    partialStart: 99,
    partialEnd: 119,
    video: "./resources/birdy-grinder.mp4",
    poster: "./resources/birdy-grinder.png",
    name: "Birdy/Bluebird Grinder",
    info:
      "Window starts the third frame of the spear recoiling after stabbing you",
    note: "",
    frames: 5,
  },
  "Bloober Ink Blast": {
    type: "block",
    perfect: 140,
    partialStart: 132,
    partialEnd: 153,
    video: "./resources/BlooberInkBlast.mp4",
    poster: "./resources/BlooberInkBlast.png",
    name: "Bloober Ink Blast",
    info: "As the bubble pops",
    note: "",
    frames: 5,
  },
  "Bloober Attack": {
    type: "block",
    perfect: 156,
    partialStart: 148,
    partialEnd: 169,
    video: "./resources/BlooberAttack.mp4",
    poster: "./resources/BlooberAttack.png",
    name: "Bloober Attack",
    info: "As the tentacles come towards you",
    note: "",
    frames: 5,
  },
  "Bob-omb Explosion": {
    type: "block",
    perfect: 25,
    partialStart: 17,
    partialEnd: 38,
    video: "./resources/medbobomb.mp4",
    poster: "./resources/medbobomb.png",
    name: "Bob-omb Explosion",
    info: "As soon as you see the circle of the explosion (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Bodyguard/Shyper/Shyster Jump": {
    type: "block",
    perfect: 46,
    partialStart: 38,
    partialEnd: 59,
    video: "./resources/ShysterJump.mp4",
    poster: "./resources/ShysterJump.png",
    name: "Bodyguard/Shyper/Shyster Jump",
    info:
      "Just after Shyster reaches the character, before his spring is fully compressed",
    note: "",
    frames: 5,
  },
  "Boomer Attack": {
    type: "block",
    perfect: 68,
    partialStart: 60,
    partialEnd: 81,
    video: "./resources/boomer1.mp4",
    poster: "./resources/boomer1.png",
    name: "Boomer Attack",
    info:
      "During the swipe of his sword when you start to see the motion blur (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Boomer Shaker": {
    type: "block",
    perfect: 52,
    partialStart: 44,
    partialEnd: 65,
    video: "./resources/boomer2.mp4",
    poster: "./resources/boomer2.png",
    name: "Boomer Shaker",
    info: "When the swipe of his sword has finished (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Boomer Skewer": {
    type: "block",
    perfect: 132,
    partialStart: 124,
    partialEnd: 145,
    video: "./resources/boomer3.mp4",
    poster: "./resources/boomer3.png",
    name: "Boomer Skewer",
    info:
      "When he puts his sword back to his side and begins to retreat (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Booster Attack": {
    type: "block",
    perfect: 94,
    partialStart: 86,
    partialEnd: 107,
    video: "./resources/boosterattack.mp4",
    poster: "./resources/boosterattack.png",
    name: "Booster Attack",
    info: "When his fist is big and in your face (5 frames)",
    note: "",
    frames: 5,
  },
  "Bowser Chomp": {
    type: "attack",
    perfect: 52,
    partialStart: 42,
    partialEnd: 63,
    video: "./resources/bowserchomp.mp4",
    poster: "./resources/bowserchomp.png",
    name: "Bowser Chomp",
    info: "Right as it leaves Bowser's hands (7 frames)",
    note: "",
    frames: 7,
  },
  "Bowser Chomp Shell": {
    type: "attack",
    perfect: 53,
    partialStart: 43,
    partialEnd: 64,
    video: "./resources/bowserchompshell.mp4",
    poster: "./resources/bowserchompshell.png",
    name: "Bowser Chomp Shell",
    info: "Right as it leaves Bowser's hands",
    note: "",
    frames: 7,
  },
  "Bowser Crusher": {
    type: "attack",
    perfect: 151,
    partialStart: 125,
    partialEnd: 156,
    video: "./resources/crusher.mp4",
    poster: "./resources/crusher.png",
    name: "Bowser Crusher",
    info:
      "Right before all the rocks dissipate, as the rumbling sound effect is ending",
    note: "",
    frames: 4,
  },
  "Bowser Drill Claw": {
    type: "attack",
    perfect: 33,
    partialStart: 17,
    partialEnd: 54,
    video: "./resources/drillclaw.mp4",
    poster: "./resources/drillclaw.png",
    name: "Bowser Drill Claw",
    info: "Immediately before the swipe",
    note: "",
    frames: 8,
  },
  "Bowser Hurly Gloves": {
    type: "Attack",
    perfect: 29,
    partialStart: 17,
    partialEnd: 41,
    video: "./resources/hurlygloves.mp4",
    poster: "./resources/hurlygloves.png",
    name: "Bowser Hurly Gloves",
    info:
      "As soon as Mario begins moving forward. Ends 4 frames before contact. (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Bowser Spiked Link": {
    type: "attack",
    perfect: 60,
    partialStart: 50,
    partialEnd: 70,
    video: "./resources/bowser-spiked-link.mp4",
    poster: "./resources/bowser-spiked-link.png",
    name: "Bowser Spiked Link",
    info:
      "While the ball is airborne travelling from Bowser's hand to the target",
    note: "Bowser begins leaning forward the frame he releases it",
    frames: 7,
  },
  "Bowser Unarmed": {
    type: "Attack",
    perfect: 25,
    partialStart: 9,
    partialEnd: 46,
    video: "./resources/bowserunarmed.mp4",
    poster: "./resources/bowserunarmed.png",
    name: "Bowser Unarmed",
    info: "Right before the swipe (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Bowser Clone Claw": {
    type: "block",
    perfect: 57,
    partialStart: 49,
    partialEnd: 69,
    video: "./resources/bowser_clone_claw.mp4",
    poster: "./resources/bowser_clone_claw.png",
    name: "Bowser Clone Claw",
    info:
      "First blockable frame the instant after the arc of the slash animation",
    note: "Ends on frame 69",
    frames: 5,
  },
  "Bowser Clone Spine": {
    type: "block",
    perfect: 40,
    partialStart: 32,
    partialEnd: 52,
    video: "./resources/bowser_clone_spine.mp4",
    poster: "./resources/bowser_clone_spine.png",
    name: "Bowser Clone Spine",
    info: "First blockable the instant after the twinkle animation ends",
    note: "",
    frames: 5,
  },
  "Bowyer Arrow": {
    type: "block",
    perfect: 90,
    partialStart: 82,
    partialEnd: 103,
    video: "./resources/bowyerarrow.mp4",
    poster: "./resources/bowyerarrow.png",
    name: "Bowyer Arrow",
    info:
      "First blockable when arrow tip aligns with Bowyer's right shoulder. (5 frames)",
    note:
      "(Last blockable when arrow tip aligns with Bowyer's stretched index finger)",
    frames: 5,
    relevant: true,
  },
  "Box Boy Attack": {
    type: "block",
    perfect: 122,
    partialStart: 114,
    partialEnd: 134,
    video: "./resources/boxboy-attack.mp4",
    poster: "./resources/boxboy-attack.png",
    name: "Box Boy Attack",
    info:
      "After the ghost face splits in two(ish), the final four frames prior to the box shaking, plus the first frame of the box shaking",
    note: "",
    frames: 5,
  },
  "Bundt Attack": {
    type: "block",
    perfect: 19,
    partialStart: 10,
    partialEnd: 30,
    video: "./resources/bundtattack.mp4",
    poster: "./resources/bundtattack.png",
    name: "Bundt Attack",
    info:
      "First blockable 3 frames before he makes the 'O' with his mouth. (4 frames)",
    note: "",
    frames: 4,
    relevant: true,
  },
  "Bundt Orb (Left)": {
    type: "block",
    perfect: 71,
    partialStart: 63,
    partialEnd: 84,
    video: "./resources/bundtorbmario.mp4",
    poster: "./resources/bundtorbmario.png",
    name: "Bundt Orb (Left)",
    info: "When the orb passes Bowser's head (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Bundt Orb (Middle)": {
    type: "block",
    perfect: 54,
    partialStart: 46,
    partialEnd: 67,
    video: "./resources/bundtorbmid.mp4",
    poster: "./resources/bundtorbmid.png",
    name: "Bundt Orb (Middle)",
    info: "Right before the orb hits (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Bundt Orb (Right)": {
    type: "block",
    perfect: 37,
    partialStart: 29,
    partialEnd: 49,
    video: "./resources/bundtorb.mp4",
    poster: "./resources/bundtorb.png",
    name: "Bundt Orb (Right)",
    info:
      "The final six frames of the orb on screen are partial block. The five before those are perfect block. (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Buzzer/Stinger Attack": {
    type: "block",
    perfect: 101,
    partialStart: 93,
    partialEnd: 114,
    video: "./resources/BuzzerCounter.mp4",
    poster: "./resources/BuzzerCounter.png",
    name: "Buzzer/Stinger Attack",
    info: "Just before the final sting animation",
    note: "",
    frames: 5,
  },
  "Carroboscis Attack": {
    type: "block",
    perfect: 146,
    partialStart: 132,
    partialEnd: 159,
    video: "./resources/CarroboscisAttack.mp4",
    poster: "./resources/CarroboscisAttack.png",
    name: "Carroboscis Attack",
    info: "After his hair points towards you",
    note: "",
    frames: 5,
  },
  "Chained Kong/Guerilla Slam": {
    type: "block",
    perfect: 119,
    partialStart: 111,
    partialEnd: 132,
    video: "./resources/GuerillaSlam.mp4",
    poster: "./resources/GuerillaSlam.png",
    name: "Chained Kong/Guerilla Slam",
    info: "The moment his slap hits the ground",
    note: "",
    frames: 5,
  },
  "Chained Kong/Guerilla Rock": {
    type: "block",
    perfect: 198,
    partialStart: 190,
    partialEnd: 211,
    video: "./resources/GuerillaRock.mp4",
    poster: "./resources/GuerillaRock.png",
    name: "Chained Kong/Guerilla Rock",
    info: "After the rock has split into the smallest possible pieces",
    note: "",
    frames: 5,
  },
  "Chewy/Piranha Plant Attack": {
    type: "block",
    perfect: 55,
    partialStart: 47,
    partialEnd: 68,
    video: "./resources/piranhaplant.mp4",
    poster: "./resources/piranhaplant.png",
    name: "Chewy/Piranha Plant Attack",
    info: "When the munching noise stops (5 frames)",
    note: "",
    frames: 5,
  },
  "Chomp/Chomp Chomp Attack": {
    type: "block",
    perfect: 53,
    partialStart: 45,
    partialEnd: 66,
    video: "./resources/chomp.mp4",
    poster: "./resources/chomp.png",
    name: "Chomp/Chomp Chomp Attack",
    info: "As they close their mouth a 2nd time (5 frames)",
    note: "",
    frames: 5,
  },
  "Chow/K-9 Attack": {
    type: "block",
    perfect: 42,
    partialStart: 34,
    partialEnd: 55,
    video: "./resources/k-91.mp4",
    poster: "./resources/K-91.png",
    name: "Chow/K-9 Attack",
    info: "When it reaches its jaws forward",
    note: "",
    frames: 5,
  },
  "Clerk/Director/Manager Attack": {
    type: "block",
    perfect: 45,
    partialStart: 37,
    partialEnd: 58,
    video: "./resources/manager.mp4",
    poster: "./resources/manager.png",
    name: "Clerk/Director/Manager Attack",
    info:
      "When his hand first stops shaking and starts extending into and past you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Cloaker Attack": {
    type: "block",
    perfect: 57,
    partialStart: 50,
    partialEnd: 70,
    video: "./resources/cloaker1.mp4",
    poster: "./resources/cloaker1.png",
    name: "Cloaker Attack",
    info: "When he first strikes down onto you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Cloaker Knife": {
    type: "block",
    perfect: 61,
    partialStart: 53,
    partialEnd: 74,
    video: "./resources/cloaker2.mp4",
    poster: "./resources/cloaker2.png",
    name: "Cloaker Knife",
    info: "When the knife is about halfway to you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Cloaker Rock": {
    type: "block",
    perfect: 99,
    partialStart: 91,
    partialEnd: 112,
    video: "./resources/cloaker3.mp4",
    poster: "./resources/cloaker3.png",
    name: "Cloaker Rock",
    info:
      "When the rock has disintegrated and the falling bits are only overlapping the lower half of your body (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Cluster/Pulsar Attack": {
    type: "block",
    perfect: 71,
    partialStart: 63,
    partialEnd: 84,
    video: "./resources/cluster.mp4",
    poster: "./resources/cluster.png",
    name: "Cluster/Pulsar Attack",
    info: "A few frames after they are opened their widest (5 frames)",
    note: "",
    frames: 5,
  },
  "Cluster Psyche": {
    type: "block",
    perfect: 301,
    partialStart: 301,
    partialEnd: 322,
    video: "./resources/clusterpsyche.mp4",
    poster: "./resources/clusterpsyche.png",
    name: "Cluster Psyche",
    info: "When the sparks pulse a 3rd time (21 frames)",
    note: "",
    frames: 21,
  },
  "Corkpedite Attack": {
    type: "block",
    perfect: 63,
    partialStart: 55,
    partialEnd: 75,
    video: "./resources/corkpedite-attack.mp4",
    poster: "./resources/corkpedite-attack.png",
    name: "Corkpedite Attack",
    info:
      "The mouth is at maximum detached for 14 frames; window opens on frame 5",
    note: "",
    frames: 5,
  },
  "Croco Attack": {
    type: "block",
    perfect: 72,
    partialStart: 64,
    partialEnd: 84,
    video: "./resources/croco1attack.mp4",
    poster: "./resources/croco1attack.png",
    name: "Croco Attack",
    info:
      "First blockable when model returns to standing from charging. (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Croco Chomp": {
    type: "block",
    perfect: 203,
    partialStart: 195,
    partialEnd: 213,
    video: "./resources/croco2chomp.mp4",
    poster: "./resources/croco2chomp.png",
    name: "Croco Chomp",
    info:
      "First blockable on first frame that enemy begins downward arc. (5 frames)",
    note:
      "(only 6 partial block frames after the perfect window, instead of 8)",
    frames: 5,
    relevant: true,
  },
  "Crook/Sackit Attack": {
    type: "block",
    perfect: 32,
    partialStart: 24,
    partialEnd: 45,
    video: "./resources/crook1.mp4",
    poster: "./resources/crook1.png",
    name: "Crook/Sackit Attack",
    info: "During the Crook's first hand motion",
    note: "",
    frames: 5,
  },
  "Crook/Sackit Knife": {
    type: "block",
    perfect: 80,
    partialStart: 72,
    partialEnd: 93,
    video: "./resources/crook2.mp4",
    poster: "./resources/crook2.png",
    name: "Crook/Sackit Knife",
    info: "After the knife is half way to the target, before it hits",
    note: "",
    frames: 5,
  },
  "Crusty/Star Cruster Claw": {
    type: "block",
    perfect: 32,
    partialStart: 24,
    partialEnd: 45,
    video: "./resources/CrustyClaw.mp4",
    poster: "./resources/CrustyClaw.png",
    name: "Crusty/Star Cruster Claw",
    info: "As the claw comes towards you",
    note: "",
    frames: 5,
  },
  "Culex Attack": {
    type: "block",
    perfect: 22,
    partialStart: 14,
    partialEnd: 34,
    video: "./resources/culex-attack.mp4",
    poster: "./resources/culex-attack.png",
    name: "Culex Attack",
    info:
      "After being attacked, Culex always re-enters the bobbing animation at the bottom. The window begins 3 frames after he begins moving back downwards after the upwards swing",
    note:
      "Alternatively, the window begins 23 frames after the prior character comes to rest from their attack",
    frames: 5,
  },
  "Czar Dragon Attack": {
    type: "block",
    perfect: 69,
    partialStart: 61,
    partialEnd: 82,
    video: "./resources/czar1.mp4",
    poster: "./resources/czar1.png",
    name: "Czar Dragon Attack",
    info: "Right as he lunges at you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Ding-A-Ling Attack": {
    type: "block",
    perfect: 29,
    partialStart: 21,
    partialEnd: 42,
    video: "./resources/dingaling.mp4",
    poster: "./resources/dingaling.png",
    name: "Ding-A-Ling Attack",
    info: "As soon as all 6 stars form a circle (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Dodo Attack": {
    type: "block",
    perfect: 30,
    partialStart: 22,
    partialEnd: 43,
    video: "./resources/dodo1.mp4",
    poster: "./resources/dodo1.png",
    name: "Dodo Attack",
    info: "While Dodo's neck is fully extended backward (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Dodo Multistrike": {
    type: "block",
    perfect: 140,
    partialStart: 132,
    partialEnd: 153,
    video: "./resources/dodo2.mp4",
    poster: "./resources/dodo2.png",
    name: "Dodo Multistrike",
    info:
      "Right before the 4th strike noise, when Dodo's head is poking you after his hat momentarily pops off (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Doppel/Shadow Slap": {
    type: "block",
    perfect: 82,
    partialStart: 74,
    partialEnd: 94,
    video: "./resources/shadowslap.mp4",
    poster: "./resources/shadowslap.png",
    name: "Doppel/Shadow Slap",
    info: "Just after the hands come together and raise slightly",
    note: "Its eyes turn orange just a frame before the perfect window passes",
    frames: 5,
  },
  "Doppel/Shadow Orb": {
    type: "block",
    perfect: 60,
    partialStart: 52,
    partialEnd: 73,
    video: "./resources/shadowblast.mp4",
    poster: "./resources/shadowblast.png",
    name: "Doppel/Shadow Orb",
    info: "Right when the blast touches its target and disappears",
    note: "the other physical is cooler",
    frames: 5,
  },
  "Dry Bones/Vomer Bone Toss": {
    type: "block",
    perfect: 46,
    partialStart: 38,
    partialEnd: 59,
    video: "./resources/Dry_Bone_Toss.mp4",
    poster: "./resources/Dry_Bone_Toss.png",
    name: "Dry Bones/Vomer Bone Toss",
    info:
      "you want to hit block as soon as the bone reaches the top of the arc",
    note: "pereft frames are when the bone is Horizontal at the peak",
    frames: 5,
  },
  "Dry Bones/Vomer Head Spin": {
    type: "block",
    perfect: 62,
    partialStart: 54,
    partialEnd: 75,
    video: "./resources/Dry_Bone_HeadSpin.mp4",
    poster: "./resources/Dry_Bone_HeadSpin.png",
    name: "Dry Bones/Vomer Head Spin",
    info:
      "Right near the end of the spinning attack, befor It's head returns to it's body",
    note: "",
    frames: 5,
  },
  "Earthlink Attack": {
    type: "block",
    perfect: 71,
    partialStart: 63,
    partialEnd: 84,
    video: "./resources/earthlink1.mp4",
    poster: "./resources/earthlink1.png",
    name: "Earthlink Attack",
    info:
      "When he is upright in the middle of his lunge after retracting backwards (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Earthlink Carni-kiss": {
    type: "block",
    perfect: 128,
    partialStart: 120,
    partialEnd: 141,
    video: "./resources/earthlink2.mp4",
    poster: "./resources/earthlink2.png",
    name: "Earthlink Carni-kiss",
    info:
      "When he is upright in the middle of his lunge after retracting backwards (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Enigma/Gorgon Attack": {
    type: "block",
    perfect: 87,
    partialStart: 79,
    partialEnd: 100,
    video: "./resources/enigma.mp4",
    poster: "./resources/enigma.png",
    name: "Enigma/Gorgon Attack",
    info: "When they stop looking like an arrow and spread out (5 frames)",
    note: "",
    frames: 5,
  },
  "Factory Chief Attack": {
    type: "block",
    perfect: 62,
    partialStart: 54,
    partialEnd: 74,
    video: "./resources/factorychief-attack.mp4",
    poster: "./resources/factorychief-attack.png",
    name: "Factory Chief Attack",
    info:
      "The 2 frames on either side of the blade's visual swoosh first appearing",
    note: "",
    frames: 5,
  },
  "Fautso Jump": {
    type: "block",
    perfect: 185,
    partialStart: 177,
    partialEnd: 197,
    video: "./resources/fautso-jump.mp4",
    poster: "./resources/fautso-jump.png",
    name: "Fautso Jump",
    info: "Window starts on the third frame of Fautso puckering its lips",
    note: "",
    frames: 5,
  },
  "Fautso Orb": {
    type: "block",
    perfect: 59,
    partialStart: 51,
    partialEnd: 71,
    video: "./resources/fautso-lightball.mp4",
    poster: "./resources/fautso-lightball.png",
    name: "Fautso Orb",
    info:
      "Ball fires when chin is fully tucked, window starts first frame of two animation cels later",
    note: "",
    frames: 5,
  },
  "Fautso Rock (Left)": {
    type: "block",
    perfect: 119,
    partialStart: 111,
    partialEnd: 131,
    video: "./resources/fautso-rockthrow-left.mp4",
    poster: "./resources/fautso-rockthrow-left.png",
    name: "Fautso Rock (Left)",
    info:
      "Window starts the frame before the debris crosses the back of the playfield",
    note: "",
    frames: 5,
  },
  "Fautso Rock (Middle)": {
    type: "block",
    perfect: 101,
    partialStart: 93,
    partialEnd: 113,
    video: "./resources/fautso-rockthrow-middle.mp4",
    poster: "./resources/fautso-rockthrow-middle.png",
    name: "Fautso Rock (Middle)",
    info:
      "Window starts the second frame after the debris has crossed the back edge of the playfield",
    note: "",
    frames: 5,
  },
  "Fautso Rock (Right)": {
    type: "block",
    perfect: 131,
    partialStart: 123,
    partialEnd: 143,
    video: "./resources/fautso-rockthrow-right.mp4",
    poster: "./resources/fautso-rockthrow-right.png",
    name: "Fautso Rock (Right)",
    info:
      "As the rock flies at you, he tucks his chin. As the debris is scattering, he untucks it (2 cels) and then re-tucks it. Window begins the frame before it is re-tucked.",
    note:
      "Or, window starts the fourth frame after debris crosses the back of the playfield",
    frames: 5,
  },
  "Fink Flower/Snapdragon Attack": {
    type: "block",
    perfect: 51,
    partialStart: 43,
    partialEnd: 64,
    video: "./resources/snapdragon.mp4",
    poster: "./resources/snapdragon.png",
    name: "Fink Flower/Snapdragon Attack",
    info: "After the Snapdragon's second swipe",
    note: "",
    frames: 5,
  },
  "Fireball/Pyrosphere/Sparky Attack": {
    type: "block",
    perfect: 166,
    partialStart: 158,
    partialEnd: 179,
    video: "./resources/sparky.mp4",
    poster: "./resources/sparky.png",
    name: "Fireball/Pyrosphere/Sparky Attack",
    info: "After they have spun around 4 times (5 frames)",
    note: "",
    frames: 5,
  },
  "Forkies/Jawful Attack": {
    type: "block",
    perfect: 63,
    partialStart: 55,
    partialEnd: 75,
    video: "./resources/jawful-attack.mp4",
    poster: "./resources/jawful-attack.png",
    name: "Forkies/Jawful Attack",
    info:
      "Window opens the frame that Jawful is reaching as far back as possible",
    note: "",
    frames: 5,
  },
  "Frogog Attack 1": {
    type: "block",
    perfect: 173,
    partialStart: 165,
    partialEnd: 186,
    video: "./resources/frogog1.mp4",
    poster: "./resources/frogog1.png",
    name: "Frogog Attack 1",
    info:
      "When the three drops on the left disappear, but before the three on the right disappear",
    note: "",
    frames: 5,
  },
  "Frogog Attack 2": {
    type: "block",
    perfect: 55,
    partialStart: 47,
    partialEnd: 68,
    video: "./resources/frogog2.mp4",
    poster: "./resources/frogog2.png",
    name: "Frogog Attack 2",
    info: "As soon as he leans forward",
    note: "",
    frames: 5,
  },
  "Geckit/Gecko Attack 1": {
    type: "block",
    perfect: 43,
    partialStart: 35,
    partialEnd: 56,
    video: "./resources/geckoattack1.mp4",
    poster: "./resources/geckoattack1.png",
    name: "Geckit/Gecko Attack 1",
    info: "Just before they stick their tongue out (5 frames)",
    note: "",
    frames: 5,
  },
  "Gecko Attack 2": {
    type: "block",
    perfect: 174,
    partialStart: 166,
    partialEnd: 187,
    video: "./resources/geckoattack2.mp4",
    poster: "./resources/geckoattack2.png",
    name: "Gecko Attack 2",
    info: "When the top droplet bursts (5 frames)",
    note: "",
    frames: 5,
  },
  "Gecko Fun & Run": {
    type: "block",
    perfect: 111,
    partialStart: 103,
    partialEnd: 124,
    video: "./resources/geckofunnrun.mp4",
    poster: "./resources/geckofunnrun.png",
    name: "Gecko Fun & Run",
    info: "When its tongue is fully extended (5 frames)",
    note: "",
    frames: 5,
  },
  "Geno Beam/Geno Blast/Geno Flash": {
    type: "attack",
    perfect: 211,
    partialStart: 127,
    partialEnd: 236,
    video: "./resources/genobeam.mp4",
    poster: "./resources/genobeam.png",
    name: "Geno Beam/Geno Blast/Geno Flash",
    info:
      "Release Y at any point you see three stars on screen",
    note: "You must start holding Y before you hear the charge-up sound begin.<br/>You can begin holding Y during the \"Hold Y for power!\" dialog, and press another button or D-pad direction to clear it.",
    frames: 25,
  },
  "Geno Boost": {
    type: "attack",
    perfect: 158,
    partialStart: 158,
    partialEnd: 188,
    video: "./resources/geno-boost.mp4",
    poster: "./resources/geno-boost.png",
    name: "Geno Boost",
    info:
      "Aim for just before the arrows stop spawning, but err on the side of being early",
    note: "Only has a single boost level; ATK if fail, ATK+DEF if successful",
    frames: 31,
  },
  "Geno Double Punch": {
    type: "Attack",
    perfect: 30,
    partialStart: 10,
    partialEnd: 41,
    video: "./resources/doublepunch.mp4",
    poster: "./resources/doublepunch.png",
    name: "Geno Double Punch",
    info:
      "when his arms are extended and the explosions appear at his elbows (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Geno Finger Shot": {
    type: "Attack",
    perfect: 22,
    partialStart: 14,
    partialEnd: 32,
    video: "./resources/fingershot.mp4",
    poster: "./resources/fingershot.png",
    name: "Geno Finger Shot",
    info:
      "Frame before elbow appears, until frame when hand locks into place (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Geno Hand Cannon": {
    type: "attack",
    perfect: 54,
    partialStart: 16,
    partialEnd: 72,
    video: "./resources/geno-handcannon.mp4",
    poster: "./resources/geno-handcannon.png",
    name: "Geno Hand Cannon",
    info:
      "As his elbow bends, his hand goes beyond 90 degrees and closes slightly prior to the shots; window starts 3 frames after it begins to close",
    note: "Window ends on the first frame a bullet is visible on screen",
    frames: 7,
  },
  "Geno Hand Gun": {
    type: "attack",
    perfect: 31,
    partialStart: 15,
    partialEnd: 42,
    video: "./resources/genohandgun.mp4",
    poster: "./resources/genohandgun.png",
    name: "Geno Hand Gun",
    info: "When his arm is extended, before the gun part sticks out (7 frames)",
    note: "",
    frames: 7,
  },
  "Geno Star Gun": {
    type: "attack",
    perfect: 33,
    partialStart: 17,
    partialEnd: 43,
    video: "./resources/stargun.mp4",
    poster: "./resources/stargun.png",
    name: "Geno Star Gun",
    info: "When neither his fists nor guns are out",
    note: "",
    frames: 7,
  },
  "Geno Unarmed": {
    type: "Attack",
    perfect: 28,
    partialStart: 26,
    partialEnd: 36,
    video: "./resources/genounarmed.mp4",
    poster: "./resources/genounarmed.png",
    name: "Geno Unarmed",
    info:
      "during his forward lunge, after his elbow is fully extended (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Geno Whirl": {
    type: "Attack",
    perfect: 170,
    partialStart: 170,
    partialEnd: 186,
    video: "./resources/genowhirl.mp4",
    poster: "./resources/genowhirl.png",
    name: "Geno Whirl",
    info: "When the brightest disc has left the screen (16 frames)",
    note: "",
    frames: 16,
    relevant: true,
  },
  "Geno Clone Attack": {
    type: "block",
    perfect: 31,
    partialStart: 23,
    partialEnd: 42,
    video: "./resources/geno_clone_attack.mp4",
    poster: "./resources/geno_clone_attack.png",
    name: "Geno Clone Attack",
    info:
      "First blockable frame when Geno is aligned with target and instant he begins walking towards them",
    note: "",
    frames: 5,
  },
  "Glum Reaper/Greaper Attack": {
    type: "block",
    perfect: 49,
    partialStart: 41,
    partialEnd: 62,
    video: "./resources/Greaper_Attack.mp4",
    poster: "./resources/Greaper_Attack.png",
    name: "Glum Reaper/Greaper Attack",
    info: "Right before greaper reaches the top of it's swing",
    note:
      "There are only 5 still sprites used for the windup of this attack. 26 total frames [4,4,4,6,8]",
    frames: 5,
  },
  "Glum Reaper Scythe": {
    type: "block",
    perfect: 168,
    partialStart: 168,
    partialEnd: 188,
    video: "./resources/glumreaper-scythe.mp4",
    poster: "./resources/glumreaper-scythe.png",
    name: "Glum Reaper Scythe",
    info: "21 frames starting just after halfway through the SHING sfx",
    note: "No partial; full block or OHKO",
    frames: 21,
  },
  /*"Goby/Mr. Kipper Attack": {
    type: "block",
    perfect: 64,
    partialStart: 55,
    partialEnd: 77,
    video: "./resources/fish.mp4",
    poster: "./resources/fish.png",
    name: "Goby/Mr. Kipper Attack",
    info: "The moment the fish's angry face returns to normal (5 frames)",
    note: "",
    frames: 5,
  },*/
  "Goby/Mr. Kipper Attack": {
    type: "block",
    perfect: 73,
    partialStart: 65,
    partialEnd: 86,
    video: "./resources/goby.mp4",
    poster: "./resources/goby.png",
    name: "Goby/Mr. Kipper Attack",
    info: "Just after impact when the eyes are wide open",
    note: "",
    frames: 5,
  },
  "Goomba Bite": {
    type: "block",
    perfect: 72,
    partialStart: 64,
    partialEnd: 86,
    video: "./resources/goombabite.mp4",
    poster: "./resources/goombabite.png",
    name: "Goomba Bite",
    info: "When his mouth has fully opened",
    note: "",
    frames: 5,
  },
  "Goomba Spine": {
    type: "block",
    perfect: 61,
    partialStart: 53,
    partialEnd: 74,
    video: "./resources/goombaspine.mp4",
    poster: "./resources/goombaspine.png",
    name: "Goomba Spine",
    info: "As it's about to hit you, before it vanishes (5 frames)",
    note: "",
    frames: 5,
  },
  "Goombette Bite": {
    type: "block",
    perfect: 70,
    partialStart: 62,
    partialEnd: 83,
    video: "./resources/Goombette_attack.mp4",
    poster: "./resources/Goombette_attack.png",
    name: "Goombette Bite",
    info: "Timing is right before the 3rd bite",
    note: "Attack consists of 3 bites",
    frames: 5,
  },
  "Grate Guy Attack": {
    type: "block",
    perfect: 84,
    partialStart: 75,
    partialEnd: 96,
    video: "./resources/grateguyattack.mp4",
    poster: "./resources/grateguyattack.png",
    name: "Grate Guy Attack",
    info:
      "First blockable two frames before he starts springing up the second time. (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Gunyolk Attack": {
    type: "block",
    perfect: 86,
    partialStart: 78,
    partialEnd: 98,
    video: "./resources/gunyolk-attack.mp4",
    poster: "./resources/gunyolk-attack.png",
    name: "Gunyolk Attack",
    info:
      "After the guns pucker like lips, the bottom hits you followed by the top. Window is the final 2 frames of the lower gun and the first 3 frames of the upper gun",
    note: "",
    frames: 5,
  },
  "Hammer Bros. Attack": {
    type: "block",
    perfect: 55,
    partialStart: 47,
    partialEnd: 67,
    video: "./resources/hammerbrosattack.mp4",
    poster: "./resources/hammerbrosattack.png",
    name: "Hammer Bros. Attack",
    info:
      "First blockable on second to last frame of highest hammer position (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Hammer Bros. Hammer Time": {
    type: "block",
    perfect: 197,
    partialStart: 195,
    partialEnd: 215,
    video: "./resources/hammertime.mp4",
    poster: "./resources/hammertime.png",
    name: "Hammer Bros. Hammer Time",
    info:
      "First blockable when last hammer begins pointing straight down (5 frames)",
    note:
      "Hammer placement random, look for orientation of hammer with only one on screen",
    frames: 5,
    relevant: true,
  },
  "Heavy Troopa/Tub-O-Troopa Attack": {
    type: "block",
    perfect: 215,
    partialStart: 207,
    partialEnd: 227,
    video: "./resources/heavytroopa-attack.mp4",
    poster: "./resources/heavytroopa-attack.png",
    name: "Heavy Troopa/Tub-O-Troopa Attack",
    info:
      "Window begins on 7th frame of Troopa's shadow being visible on top of the defending unit",
    note: "",
    frames: 5,
  },
  "Hidon Bite": {
    type: "block",
    perfect: 40,
    partialStart: 32,
    partialEnd: 53,
    video: "./resources/Hidon_Bite.mp4",
    poster: "./resources/Hidon_Bite.png",
    name: "Hidon Bite",
    info: "Timing is right at the very begining of it's biting animation",
    note: "Time is right after it opens it's mouth the 2nd timed",
    frames: 5,
  },
  "Hippopo Attack": {
    type: "block",
    perfect: 53,
    partialStart: 45,
    partialEnd: 65,
    video: "./resources/hippopo-attack.mp4",
    poster: "./resources/hippopo-attack.png",
    name: "Hippopo Attack",
    info: "2 frames on either side of the mouth entering maximum open",
    note: "",
    frames: 5,
  },
  "Hippopo Body Slam": {
    type: "block",
    perfect: 121,
    partialStart: 113,
    partialEnd: 133,
    video: "./resources/hippopo-bodyslam.mp4",
    poster: "./resources/hippopo-bodyslam.png",
    name: "Hippopo Body Slam",
    info: "Starts the same frame the bite sfx starts",
    note: "",
    frames: 5,
  },
  "Hobgoblin/Straw Head Attack": {
    type: "block",
    perfect: 82,
    partialStart: 74,
    partialEnd: 95,
    video: "./resources/hobgoblinphysical.mp4",
    poster: "./resources/hobgoblinphysical.png",
    name: "Hobgoblin/Straw Head Attack",
    info: "When swaying, just before it fully extends to the left",
    note:
      "There's a few 'steps' to when it swings to the left. When the skull pops a little further left, it's too late",
    frames: 5,
  },
  "Jagger/Terrapin Attack": {
    type: "block",
    perfect: 69,
    partialStart: 61,
    partialEnd: 81,
    video: "./resources/jagger-attack.mp4",
    poster: "./resources/jagger-attack.png",
    name: "Jagger/Terrapin Attack",
    info: "His fist is fully extended for 0.3s; window is the final 5 frames",
    note: "",
    frames: 5,
  },
  "Jagger/Terra Cotta Terrapunch": {
    type: "block",
    perfect: 99,
    partialStart: 91,
    partialEnd: 111,
    video: "./resources/jagger-terrapunch.mp4",
    poster: "./resources/jagger-terrapunch.png",
    name: "Jagger/Terra Cotta Terrapunch",
    info: "The frame before Jagger starts moving towards you",
    note: "",
    frames: 5,
  },
  "Jester Attack": {
    type: "block",
    perfect: 80,
    partialStart: 72,
    partialEnd: 92,
    video: "./resources/jesterattack.mp4",
    poster: "./resources/jesterattack.png",
    name: "Jester Attack",
    info: "A few frames after their hand winds up all the way back",
    note: "",
    frames: 5,
  },
  "Jester Full House": {
    type: "block",
    perfect: 170,
    partialStart: 162,
    partialEnd: 183,
    video: "./resources/jesterfullhouse.mp4",
    poster: "./resources/jesterfullhouse.png",
    name: "Jester Full House",
    info: "As the card hits you",
    note: "Uncle Joey",
    frames: 5,
  },
  "Jester Wild Card": {
    type: "block",
    perfect: 179,
    partialStart: 171,
    partialEnd: 192,
    video: "./resources/jesterwildcard.mp4",
    poster: "./resources/jesterwildcard.png",
    name: "Jester Wild Card",
    info: "Just before the 3rd card hits",
    note: "",
    frames: 5,
  },
  "Jinx Bombs Away": {
    type: "block",
    perfect: 68,
    partialStart: 60,
    partialEnd: 81,
    video: "./resources/bombsaway.mp4",
    poster: "./resources/bombsaway.png",
    name: "Jinx Bombs Away",
    info: "",
    note: "",
    frames: 5,
  },
  "Jinx Quicksilver - Partial": {
    type: "block",
    perfect: 125,
    partialStart: 117,
    partialEnd: 138,
    video: "./resources/quicksilver.mp4",
    poster: "./resources/quicksilver.png",
    name: "Jinx Quicksilver - Partial",
    info: "",
    note: "Animation changes depending on target's health",
    frames: 5,
  },
  "Jinx Quicksilver - Full": {
    type: "block",
    perfect: 115,
    partialStart: 107,
    partialEnd: 128,
    video: "./resources/quicksilverfull.mp4",
    poster: "./resources/quicksilverfull.png",
    name: "Jinx Quicksilver - Full",
    info: "",
    note: "Animation changes depending on target's health",
    frames: 5,
  },
  "Jinx Silver Bullet": {
    type: "block",
    perfect: 43,
    partialStart: 35,
    partialEnd: 56,
    video: "./resources/silverbullet.mp4",
    poster: "./resources/silverbullet.png",
    name: "Jinx Silver Bullet",
    info: "",
    note: "",
    frames: 5,
  },
  "Jinx Triple Kick - Partial": {
    type: "block",
    perfect: 107,
    partialStart: 99,
    partialEnd: 128,
    video: "./resources/triplekick.mp4",
    poster: "./resources/triplekick.png",
    name: "Jinx Triple Kick - Partial",
    info: "",
    note: "Knockback has 2 different animations",
    frames: 5,
  },
  "Jinx Triple Kick - Full": {
    type: "block",
    perfect: 123,
    partialStart: 115,
    partialEnd: 136,
    video: "./resources/triplekickfull.mp4",
    poster: "./resources/triplekickfull.png",
    name: "Jinx Triple Kick - Full",
    info: "",
    note: "Knockback has 2 different animations",
    frames: 5,
  },
  Jinxed: {
    type: "block",
    perfect: 134,
    partialStart: 126,
    partialEnd: 147,
    video: "./resources/jinxed.mp4",
    poster: "./resources/jinxed.png",
    name: "Jinxed",
    info: "",
    note: "",
    frames: 5,
  },
  "Johnny Attack": {
    type: "block",
    perfect: 70,
    partialStart: 61,
    partialEnd: 81,
    video: "./resources/johnnyattack.mp4",
    poster: "./resources/johnnyattack.png",
    name: "Johnny Attack",
    info: 240,
    note:
      "(The very last frame before the trident starts extending is a partial block)",
    frames: 4,
    relevant: true,
  },
  "Johnny Skewer": {
    type: "block",
    perfect: 142,
    partialStart: 134,
    partialEnd: 155,
    video: "./resources/Johnny_Skewer.mp4",
    poster: "./resources/Johnny_Skewer.png",
    name: "Johnny Skewer",
    info: "Timing is right as the chain extends on his trident",
    note: "Trident spins and then extends toward the character",
    frames: 5,
  },
  "K-9 Fangs": {
    type: "block",
    perfect: 128,
    partialStart: 120,
    partialEnd: 141,
    video: "./resources/k-92.mp4",
    poster: "./resources/K-92.png",
    name: "K-9 Fangs",
    info: "When it closes its jaws",
    note: "",
    frames: 5,
  },
  "Knife Guy Attack": {
    type: "block",
    perfect: 91,
    partialStart: 83,
    partialEnd: 103,
    video: "./resources/knifeguyattack.mp4",
    poster: "./resources/knifeguyattack.png",
    name: "Knife Guy Attack",
    info: "First blockable the moment he stops juggling (5 frames)",
    note:
      "(note that this attack is first perfect blockable a full 10 frames before the stab happens)",
    frames: 5,
    relevant: true,
  },
  "Knife Guy Knife": {
    type: "block",
    perfect: 90,
    partialStart: 82,
    partialEnd: 103,
    video: "./resources/knifeguyknife.mp4",
    poster: "./resources/knifeguyknife.png",
    name: "Knife Guy Knife",
    info: "When knife is about 1/2 to 3/4 of the way to Mario (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Lakitu Attack": {
    type: "block",
    perfect: 31,
    partialStart: 23,
    partialEnd: 44,
    video: "./resources/LakituAttack.mp4",
    poster: "./resources/LakituAttack.png",
    name: "Lakitu Attack",
    info: "Right before the hand is all the way up",
    note: "",
    frames: 5,
  },
  "Li'l' Boo/The Big Boo Attack": {
    type: "block",
    perfect: 110,
    partialStart: 102,
    partialEnd: 123,
    video: "./resources/thebigboo.mp4",
    poster: "./resources/thebigboo.png",
    name: "Li'l' Boo/The Big Boo Attack",
    info: "Right when it uncovers it's face",
    note: "cheeky ghost",
    frames: 5,
  },
  "Machine Made (Axem Yellow) Body Slam": {
    type: "block",
    perfect: 195,
    partialStart: 187,
    partialEnd: 207,
    video: "./resources/machinemadeyellow-bodyslam.mp4",
    poster: "./resources/machinemadeyellow-bodyslam.png",
    name: "Machine Made (Axem Yellow) Body Slam",
    info: "Starts the first frame MMY begins moving away from you",
    note: "",
    frames: 5,
  },
  "Machine Made (Drill Bit) Attack": {
    type: "block",
    perfect: 73,
    partialStart: 65,
    partialEnd: 85,
    video: "./resources/mmdrillbit-attack.mp4",
    poster: "./resources/mmdrillbit-attack.png",
    name: "Machine Made (Drill Bit) Attack",
    info: "Starts the frame it ducks down immediately prior to hitting you",
    note: "",
    frames: 5,
  },
  "Machine Made (Drill Bit) Skewer": {
    type: "block",
    perfect: 146,
    partialStart: 138,
    partialEnd: 158,
    video: "./resources/mmdrillbit-skewer.mp4",
    poster: "./resources/mmdrillbit-skewer.png",
    name: "Machine Made (Drill Bit) Skewer",
    info: "Starts the same frame the stab sfx starts",
    note: "",
    frames: 5,
  },
  "Mack Jump": {
    type: "block",
    perfect: 49,
    partialStart: 41,
    partialEnd: 62,
    video: "./resources/MackJump.mp4",
    poster: "./resources/MackJump.png",
    name: "Mack Jump",
    info: "When Mack lands and his shadow reappears under him",
    note: "",
    frames: 5,
  },
  "Mad Mallet Attack": {
    type: "block",
    perfect: 33,
    partialStart: 25,
    partialEnd: 45,
    video: "./resources/madmallet-attack.mp4",
    poster: "./resources/madmellet-attack.png",
    name: "Mad Mallet Attack",
    info: "5 frames, starting 3 frames before it first starts to swing at you",
    note: "",
    frames: 5,
  },
  "Magmite/Magmus Attack": {
    type: "block",
    perfect: 84,
    partialStart: 76,
    partialEnd: 97,
    video: "./resources/magmite.mp4",
    poster: "./resources/magmite.png",
    name: "Magmite/Magmus Attack",
    info: "right before the main rock starts to attack (5 frames)",
    note: "",
    frames: 5,
  },
  "Malakoopa/Sky Troopa Attack": {
    type: "block",
    perfect: 84,
    partialStart: 76,
    partialEnd: 97,
    video: "./resources/skytroopa.mp4",
    poster: "./resources/skytroopa.png",
    name: "Malakoopa/Sky Troopa Attack",
    info: "When the Koopa pops out of their shell (5 frames)",
    note: "",
    frames: 5,
  },
  "Mallow Cymbals": {
    type: "Attack",
    perfect: 15,
    partialStart: 14,
    partialEnd: 40,
    video: "./resources/cymbals.mp4",
    poster: "./resources/cymbals.png",
    name: "Mallow Cymbals",
    info: "Frame when hands lock in until cymbals close. (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Mallow Froggiestick": {
    type: "attack",
    perfect: 54,
    partialStart: 44,
    partialEnd: 73,
    video: "./resources/mallow_froggiestick.mp4",
    poster: "./resources/mallow_froggiestick.png",
    name: "Mallow Froggiestick",
    info: "During the first downswing",
    note: "",
    frames: 7,
  },
  "Mallow HP Rain": {
    type: "attack",
    perfect: 311,
    partialStart: 253,
    partialEnd: 313,
    video: "./resources/hprain.mp4",
    poster: "./resources/hprain.png",
    name: "Mallow HP Rain",
    info: "When the cloud fully disappears",
    note:
      "yes, this is a 58 frame half-time window followed by a 2 frame perfect window followed by no timing window, it is just as rude as it sounds",
    frames: 2,
  },
  "Mallow Psychopath": {
    type: "attack",
    perfect: 195,
    partialStart: 195,
    partialEnd: 226,
    video: "./resources/psychopath.mp4",
    poster: "./resources/psychopath.png",
    name: "Psychopath",
    info: "When the spotlights approach the enemy",
    note: "",
    frames: 31,
  },
  "Mallow Ribbit Stick": {
    type: "attack",
    perfect: 24,
    partialStart: 14,
    partialEnd: 39,
    video: "./resources/ribbit_stick.mp4",
    poster: "./resources/ribbit_stick.png",
    name: "Mallow Ribbit Stick",
    info: "Time upon first strike with the stick",
    note: "More lenient with partial timing windows. 10-7-10",
    frames: 7,
  },
  "Mallow/Toadstool Shocker": {
    type: "Attack",
    perfect: 147,
    partialStart: 132,
    partialEnd: 163,
    video: "./resources/shocker.mp4",
    poster: "./resources/shocker.png",
    name: "Mallow/Toadstool Shocker",
    info:
      "The lightning sound has 2 pitches, press the button halfway through the duration of the second/lower pitch (6 frames)",
    note: "There is no visual cue for the perfect timing of this Attack",
    frames: 6,
    relevant: true,
  },
  "Mallow Sonic Cymbal": {
    type: "attack",
    perfect: 20,
    partialStart: 19,
    partialEnd: 46,
    video: "./resources/soniccymbal.mp4",
    poster: "./resources/soniccymbal.png",
    name: "Mallow Sonic Cymbal",
    info: "When the cymbals are about to shut",
    note: "",
    frames: 7,
  },
  "Mallow Sticky Glove": {
    type: "attack",
    perfect: 19,
    partialStart: 12,
    partialEnd: 33,
    video: "./resources/mallow-stickyglove.mp4",
    poster: "./resources/mallow-stickyglove.png",
    name: "Mallow Sticky Glove",
    info:
      "2 frames before until 4 frames after Mallow's fists touch each other",
    note: "",
    frames: 7,
  },
  "Mallow Thunderbolt": {
    type: "Attack",
    perfect: 154,
    partialStart: 154,
    partialEnd: 185,
    video: "./resources/thunderbolt.mp4",
    poster: "./resources/thunderbolt.png",
    name: "Mallow Thunderbolt",
    info: "When the sound effect has just ended (31 frames)",
    note:
      "The audio cue works best for this, but you can press the button when you see all the bolts scattering around",
    frames: 31,
    relevant: true,
  },
  "Mallow Unarmed": {
    type: "Attack",
    perfect: 16,
    partialStart: 6,
    partialEnd: 29,
    video: "./resources/mallowunarmed.mp4",
    poster: "./resources/mallowunarmed.png",
    name: "Mallow Unarmed",
    info: "During the extension of his punch (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Mallow Whomp Glove": {
    type: "attack",
    perfect: 18,
    partialStart: 10,
    partialEnd: 31,
    video: "./resources/mallowwhompglove.mp4",
    poster: "./resources/mallowwhompglove.png",
    name: "Mallow Whomp Glove",
    info: "As he pulls his fist back (7 frames)",
    note: "",
    frames: 7,
  },
  "Mallow Clone Attack": {
    type: "block",
    perfect: 22,
    partialStart: 14,
    partialEnd: 34,
    video: "./resources/mallow_clone_attack.mp4",
    poster: "./resources/mallow_clone_attack.png",
    name: "Mallow Clone Attack",
    info: "First blockable frame when Mallow is nearly half-way to target",
    note: "",
    frames: 5,
  },
  "Mario Hammer": {
    type: "attack",
    perfect: 50,
    partialStart: 44,
    partialEnd: 75,
    video: "./resources/mario_hammer.mp4",
    poster: "./resources/mario_hammer.png",
    name: "Mario Hammer",
    info:
      "Perfect hit window starts at the height of Mario's jump, with the hammer behind him",
    note: "",
    frames: 7,
  },
  "Mario Jump": {
    type: "Attack",
    perfect: 68,
    partialStart: 30,
    partialEnd: 74,
    video: "./resources/mariojump.mp4",
    poster: "./resources/mariojump.png",
    name: "Mario Jump",
    info:
      "First perfect frame is the last frame where 2 marios are still visible (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Mario Lazy Shell": {
    type: "attack",
    perfect: 37,
    partialStart: 32,
    partialEnd: 49,
    video: "./resources/lazyshell.mp4",
    poster: "./resources/lazyshell.png",
    name: "Mario Lazy Shell",
    info: "Right before he kicks it",
    note: "",
    frames: 6,
  },
  "Mario Masher": {
    type: "attack",
    perfect: 24,
    partialStart: 18,
    partialEnd: 49,
    video: "./resources/mariomasher.mp4",
    poster: "./resources/mariomasher.png",
    name: "Mario Masher",
    info: "When Mario reaches full jump height. (7 frames)",
    note: "",
    frames: 7,
  },
  "Mario Mega Glove": {
    type: "Attack",
    perfect: 28,
    partialStart: 22,
    partialEnd: 42,
    video: "./resources/megaglove.mp4",
    poster: "./resources/megaglove.png",
    name: "Mario Mega Glove",
    info:
      "Starts frame before glove begins moving forward, ends one frame before glove reaches final position (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Mario NokNok Shell": {
    type: "attack",
    perfect: 55,
    partialStart: 50,
    partialEnd: 67,
    video: "./resources/mario_noknok.mp4",
    poster: "./resources/mario_noknok.png",
    name: "Mario NokNok Shell",
    info: "As shell is dropping before it reaches Mario's head",
    note: "",
    frames: 7,
  },
  "Mario Punch Glove": {
    type: "Attack",
    perfect: 20,
    partialStart: 16,
    partialEnd: 35,
    video: "./resources/punchglove.mp4",
    poster: "./resources/punchglove.png",
    name: "Mario Punch Glove",
    info: "During his fist swing (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Mario Super Hammer": {
    type: "attack",
    perfect: 57,
    partialStart: 25,
    partialEnd: 68,
    video: "./resources/mariosuperhammer.mp4",
    poster: "./resources/mariosuperhammer.png",
    name: "Mario Super Hammer",
    info: "When he begins to swing the hammer to the left (7 frames)",
    note: "",
    frames: 7,
  },
  "Mario Troopa Shell": {
    type: "Attack",
    perfect: 35,
    partialStart: 30,
    partialEnd: 47,
    video: "./resources/troopashell.mp4",
    poster: "./resources/troopashell.png",
    name: "Mario Troopa Shell",
    info:
      "When the shell is falling around halfway down until it hits Mario's foot",
    note: "Has a very small partial timed buffer",
    frames: 7,
    relevant: true,
  },
  "Mario Ultra Hammer": {
    type: "Attack",
    perfect: 20,
    partialStart: 14,
    partialEnd: 45,
    video: "./resources/ultrahammer.mp4",
    poster: "./resources/ultrahammer.png",
    name: "Mario Ultra Hammer",
    info: "During the forward swing of his hammer (7 frames)",
    note: "",
    frames: 7,
  },
  "Mario Unarmed": {
    type: "Attack",
    perfect: 14,
    partialStart: 6,
    partialEnd: 29,
    video: "./resources/mariounarmed.mp4",
    poster: "./resources/mariounarmed.png",
    name: "Mario Unarmed",
    info: "During his fist swing (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Mario Clone Attack": {
    type: "block",
    perfect: 64,
    partialStart: 56,
    partialEnd: 76,
    video: "./resources/mario_clone_attack.mp4",
    poster: "./resources/mario_clone_attack.png",
    name: "Mario Clone Attack",
    info: "First blockable when Mario is nearly at apex of front-facing jump",
    note: "",
    frames: 5,
  },
  "Mastadoom Attack 1": {
    type: "block",
    perfect: 51,
    partialStart: 43,
    partialEnd: 64,
    video: "./resources/mastadoomattack1.mp4",
    poster: "./resources/mastadoomattack1.png",
    name: "Mastadoom Attack 1",
    info: "When the trunk is facing up-left (5 frames)",
    note: "Trunk attack",
    frames: 5,
  },
  "Mastadoom Attack 2": {
    type: "block",
    perfect: 37,
    partialStart: 29,
    partialEnd: 50,
    video: "./resources/mastadoomattack2.mp4",
    poster: "./resources/mastadoomattack2.png",
    name: "Mastadoom Attack 2",
    info: "When the bone begins to fall (5 frames)",
    note: "Bone projectile",
    frames: 5,
  },
  "Megasmilax Attack": {
    type: "block",
    perfect: 32,
    partialStart: 24,
    partialEnd: 45,
    video: "./resources/megasmilax.mp4",
    poster: "./resources/megasmilax.png",
    name: "Megasmilax Attack",
    info:
      "After Megasmilax's mouth is fully opened, before it's fully closed (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Mezzo Bomb Explosion": {
    type: "block",
    perfect: 29,
    partialStart: 20,
    partialEnd: 41,
    video: "./resources/bigbobomb.mp4",
    poster: "./resources/bigbobomb.png",
    name: "Mezzo Bomb Explosion",
    info: "As soon as you see the circle of the explosion (5 frames)",
    note:
      "(only 4 partial block frames after the perfect window, instead of 8)",
    frames: 5,
    relevant: true,
  },
  "Micro Bomb Explosion": {
    type: "block",
    perfect: 27,
    partialStart: 19,
    partialEnd: 40,
    video: "./resources/smallbobomb.mp4",
    poster: "./resources/smallbobomb.png",
    name: "Micro Bomb Explosion",
    info: "As soon as you see the circle of the explosion (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Mukumuku Attack 1": {
    type: "block",
    perfect: 116,
    partialStart: 108,
    partialEnd: 129,
    video: "./resources/mukumukuattack1.mp4",
    poster: "./resources/mukumukuattack1.png",
    name: "Mukumuku Attack 1",
    info: "At the end of its arm flailing (5 frames)",
    note: "",
    frames: 5,
  },
  "Mukumuku Attack 2": {
    type: "block",
    perfect: 168,
    partialStart: 160,
    partialEnd: 180,
    video: "./resources/mukumukuattack2.mp4",
    poster: "./resources/mukumukuattack2.png",
    name: "Mukumuku Attack 2",
    info: "As the note hits the peak of its arc (5 frames)",
    note: "Projectiles can vary",
    frames: 5,
  },
  "Neosquid Attack": {
    type: "attack",
    perfect: 17,
    partialStart: 8,
    partialEnd: 30,
    video: "./resources/neosquid.mp4",
    poster: "./resources/neosquid.png",
    name: "Neosquid Attack",
    info: "When mouth is almost fully opened",
    note: "",
    frames: 5,
  },
  "Neosquid Carni-Kiss": {
    type: "attack",
    perfect: 61,
    partialStart: 53,
    partialEnd: 74,
    video: "./resources/neosquidcarni.mp4",
    poster: "./resources/neosquidcarni.png",
    name: "Neosquid Carni-Kiss",
    info: "When mouth is almost fully opened",
    note: "",
    frames: 5,
  },
  "Ninja Knife": {
    type: "block",
    perfect: 75,
    partialStart: 67,
    partialEnd: 87,
    video: "./resources/ninja-attack-knifethrow.mp4",
    poster: "./resources/ninja-attack-knifethrow.png",
    name: "Ninja Knife",
    info: "Starts the second frame the knife is on screen",
    note: "",
    frames: 5,
  },
  "Ninja Shuriken": {
    type: "block",
    perfect: 88,
    partialStart: 80,
    partialEnd: 100,
    video: "./resources/ninja-attack-blackninjastar.mp4",
    poster: "./resources/ninja-attack-blackninjastar.png",
    name: "Ninja Shuriken",
    info: "First 5 of the final 6 frames before the impact sfx starts",
    note: "",
    frames: 5,
  },
  "Ninja Warp Stab": {
    type: "block",
    perfect: 51,
    partialStart: 43,
    partialEnd: 63,
    video: "./resources/ninja-attack-warpstab.mp4",
    poster: "./resources/ninja-attack-warpstab.png",
    name: "Ninja Warp Stab",
    info:
      "The 2 frames on either side of the blade's visual swoosh first appearing",
    note: "",
    frames: 5,
  },
  "Octolot/Octovader Attack": {
    type: "block",
    perfect: 144,
    partialStart: 136,
    partialEnd: 157,
    video: "./resources/OctolotAttack.mp4",
    poster: "./resources/OctolotAttack.png",
    name: "Octolot/Octovader Attack",
    info: "Just before his mouth gets large",
    note: "",
    frames: 5,
  },
  "Oerlikon/Spikester/Spikey Attack 1": {
    type: "block",
    perfect: 28,
    partialStart: 20,
    partialEnd: 41,
    video: "./resources/spikey1.mp4",
    poster: "./resources/spikey1.png",
    name: "Oerlikon/Spikester/Spikey Attack 1",
    info:
      "From when Spikey is curled, and on the ground, for one full rotation",
    note: "",
    frames: 5,
  },
  "Oerlikon/Spikey Attack 2": {
    type: "block",
    perfect: 99,
    partialStart: 91,
    partialEnd: 112,
    video: "./resources/spikey2.mp4",
    poster: "./resources/spikey2.png",
    name: "Oerlikon/Spikey Attack 2",
    info: "Just as the spike reaches the target",
    note: "",
    frames: 5,
  },
  "Orbison Attack": {
    type: "block",
    perfect: 87,
    partialStart: 79,
    partialEnd: 99,
    video: "./resources/orbison-attack.mp4",
    poster: "./resources/orbison-attack.png",
    name: "Orbison Attack",
    info:
      "Starts the frame after it first turns perpendicular to the defender during the second rotation",
    note: "ie, the first rotation at the faster speed",
    frames: 5,
  },
  "Pandorite Attack": {
    type: "block",
    perfect: 70,
    partialStart: 62,
    partialEnd: 82,
    video: "./resources/pandoriteattack.mp4",
    poster: "./resources/pandoriteattack.png",
    name: "Pandorite Attack",
    info: "First blockable 6 frames before rehiding (6 frames)",
    note:
      "Blockable on the last part of the animation when his right arm stays still",
    frames: 6,
    relevant: true,
  },
  "Pinwheel Attack": {
    type: "block",
    perfect: 55,
    partialStart: 47,
    partialEnd: 67,
    video: "./resources/pinwheel-attack.mp4",
    poster: "./resources/pinwheel-attack.png",
    name: "Pinwheel Attack",
    info:
      "Starts the first frame the fourth time it flashes red / the 15th frame after it comes to rest in front of the defender",
    note: "Good luck!",
    frames: 5,
  },
  "Pounder Attack": {
    type: "block",
    perfect: 34,
    partialStart: 26,
    partialEnd: 47,
    video: "./resources/pounder1.mp4",
    poster: "./resources/pounder1.png",
    name: "Pounder Attack",
    info: "During the swing after it is fully extended backward",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Pounder/Poundette Mallet": {
    type: "block",
    perfect: 45,
    partialStart: 37,
    partialEnd: 58,
    video: "./resources/pounder2.mp4",
    poster: "./resources/pounder2.png",
    name: "Pounder/Poundette Mallet",
    info: "When the mallet is at the apex of its curve trajectory (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Poundette Attack": {
    type: "block",
    perfect: 50,
    partialStart: 42,
    partialEnd: 62,
    video: "./resources/poundette-attack.mp4",
    poster: "./resources/poundette-attack.png",
    name: "Poundette Attack",
    info: "Starts while the hammer as at its peak with the head facing down",
    note: "",
    frames: 5,
  },
  "Pulsar Migraine": {
    type: "block",
    perfect: 266,
    partialStart: 266,
    partialEnd: 287,
    video: "./resources/pulsarmigraine.mp4",
    poster: "./resources/pulsarmigraine.png",
    name: "Pulsar Migraine",
    info: "When the sparks pulse a 3rd time (21 frames)",
    note: "",
    frames: 21,
  },
  "Punchinello Attack": {
    type: "block",
    perfect: 47,
    partialStart: 39,
    partialEnd: 60,
    video: "./resources/punchinello.mp4",
    poster: "./resources/punchinello.png",
    name: "Punchinello Attack",
    info: "When Punchinello's arms are fully retracted back (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Puppox Attack 2": {
    type: "block",
    perfect: 46,
    partialStart: 38,
    partialEnd: 58,
    video: "./resources/puppox-attack.mp4",
    poster: "./resources/puppox-attack.png",
    name: "Puppox Attack 2",
    info: "Starts the first frame the hammer head is visible at Puppox's side",
    note: "",
    frames: 5,
  },
  "Puppox/Remo Con Attack 1": {
    type: "block",
    perfect: 47,
    partialStart: 39,
    partialEnd: 60,
    video: "./resources/remoconattack.mp4",
    poster: "./resources/remoconattack.png",
    name: "Puppox/Remo Con Attack 1",
    info: "As soon as you can see the head of the hammer (5 frames)",
    note: "",
    frames: 5,
  },
  "Raspberry Attack": {
    type: "block",
    perfect: 20,
    partialStart: 12,
    partialEnd: 33,
    video: "./resources/raspberry1.mp4",
    poster: "./resources/raspberry1.png",
    name: "Raspberry Attack",
    info:
      "When the Raspberry returns to neutral position after moving backwards, before moving forwards (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Raspberry Orb (Left)": {
    type: "block",
    perfect: 69,
    partialStart: 61,
    partialEnd: 82,
    video: "./resources/rasporbmario.mp4",
    poster: "./resources/rasporbmario.png",
    name: "Raspberry Orb (Left)",
    info: "When the orb passes Bowser's head (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Raspberry Orb (Middle)": {
    type: "block",
    perfect: 49,
    partialStart: 37,
    partialEnd: 62,
    video: "./resources/raspberry2.mp4",
    poster: "./resources/raspberry2.png",
    name: "Raspberry Orb (Middle)",
    info: "When the orb is right in front of your face (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Raspberry Orb (Right)": {
    type: "block",
    perfect: 39,
    partialStart: 31,
    partialEnd: 52,
    video: "./resources/rasporbright.mp4",
    poster: "./resources/rasporbright.png",
    name: "Raspberry Orb (Right)",
    info: "Just before it hits Geno (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Reacher Fast Bone Toss": {
    type: "block",
    perfect: 21,
    partialStart: 13,
    partialEnd: 34,
    video: "./resources/Reacher_FastBone_Toss.mp4",
    poster: "./resources/Reacher_FastBone_Toss.png",
    name: "Reacher Fast Bone Toss",
    info: "Timing it right before the bone reaches the arc of throw",
    note: "Reacher rushes forward and the bone get thrown",
    frames: 5,
  },
  "Reacher Reach": {
    type: "block",
    perfect: 49,
    partialStart: 41,
    partialEnd: 62,
    video: "./resources/Reacher_Reach.mp4",
    poster: "./resources/Reacher_Reach.png",
    name: "Reacher Reach",
    info:
      "Hit block when Reacher is pulling it's hands back about halfway from it's body",
    note:
      "The reach animation is, close to body, middle, far, middle, close back to resting.",
    frames: 5,
  },
  "Reacher Reaching Bone Toss": {
    type: "block",
    perfect: 79,
    partialStart: 71,
    partialEnd: 92,
    video: "./resources/Reacher_ReachingBone_Toss.mp4",
    poster: "./resources/Reacher_ReachingBone_Toss.png",
    name: "Reacher Reaching Bone Toss",
    info: "Timing is right before or on the top most arc of the bone.",
    note:
      "Arms will reach out and pull back, then immediately launch a bone in an arc",
    frames: 5,
  },
  "Remo Con Body Slam": {
    type: "block",
    perfect: 93,
    partialStart: 85,
    partialEnd: 106,
    video: "./resources/remoconbodyslam.mp4",
    poster: "./resources/remoconbodyslam.png",
    name: "Remo Con Body Slam",
    info: "When their hammer is oriented straight up (5 frames)",
    note: "",
    frames: 5,
  },
  "Ribbite Attack": {
    type: "block",
    perfect: 46,
    partialStart: 38,
    partialEnd: 58,
    video: "./resources/ribbite_attack.mp4",
    poster: "./resources/ribbite_attack.png",
    name: "Ribbite Attack",
    info: "Time the instant Ribbite leans back",
    note: "",
    frames: 5,
  },
  "Right Eye Attack": {
    type: "attack",
    perfect: 34,
    partialStart: 25,
    partialEnd: 46,
    video: "./resources/eye.mp4",
    poster: "./resources/eye.png",
    name: "Right Eye Attack",
    info: "When eye opens and pupil becomes tiny",
    note: "",
    frames: 5,
  },
  "Shaman Attack": {
    type: "block",
    perfect: 51,
    partialStart: 43,
    partialEnd: 63,
    video: "./resources/shaman-attack.mp4",
    poster: "./resources/shaman-attack.png",
    name: "Shaman Attack",
    info: "The wand is extended for 22 frames; window starts on the seventh",
    note: "",
    frames: 5,
  },
  "Shy Away Attack": {
    type: "block",
    perfect: 72,
    partialStart: 64,
    partialEnd: 85,
    video: "./resources/shy_away_attack.mp4",
    poster: "./resources/shy_away_attack.png",
    name: "Shy Away Attack",
    info: "When Shy Away fully retracts",
    note: "",
    frames: 5,
  },
  /*"Shy Guy": {
    type: "block",
    perfect: 48,
    partialStart: 40,
    partialEnd: 61,
    video: "./resources/shyguy.mp4",
    poster: "./resources/shyguy.png",
    name: "Shy Guy",
    info: "After the Shy Guy fires, but before the shot hits",
    note: "",
    frames: 5,
  },*/
  "Shy Guy/Shy Ranger/Sling Shy Slingshot": {
    type: "block",
    perfect: 54,
    partialStart: 46,
    partialEnd: 67,
    video: "./resources/shyranger1.mp4",
    poster: "./resources/shyranger1.png",
    name: "Shy Guy/Shy Ranger/Sling Shy Slingshot",
    info: "When the sling is all the way forward (5 frames)",
    note: "Slingshot",
    frames: 5,
  },
  "Shy Ranger Shuriken": {
    type: "block",
    perfect: 138,
    partialStart: 130,
    partialEnd: 151,
    video: "./resources/shyranger2.mp4",
    poster: "./resources/shyranger2.png",
    name: "Shy Ranger Shuriken",
    info: "Just after they throw the shuriken (5 frames)",
    note: "Shuriken",
    frames: 5,
  },
  "Shy Ranger Knife": {
    type: "block",
    perfect: 152,
    partialStart: 144,
    partialEnd: 165,
    video: "./resources/shyranger3.mp4",
    poster: "./resources/shyranger3.png",
    name: "Shy Ranger Knife",
    info: "Just before the knife hits you (5 frames)",
    note: "Knife",
    frames: 5,
  },
  "Smilax Attack": {
    type: "block",
    perfect: 26,
    partialStart: 18,
    partialEnd: 39,
    video: "./resources/smilax.mp4",
    poster: "./resources/smilax.png",
    name: "Smilax Attack",
    info:
      "As soon as his mouth is fully open during the second bite animation (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Smithy 1 Hammer": {
    type: "block",
    perfect: 52,
    partialStart: 44,
    partialEnd: 65,
    video: "./resources/smithy1.mp4",
    poster: "./resources/smithy1.png",
    name: "Smithy 1 Hammer",
    info: "When the hammer drops onto you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Smithy 2 Finger Gun (Left)": {
    type: "block",
    perfect: 143,
    partialStart: 135,
    partialEnd: 155,
    video: "./resources/smithy2-fingergun-left.mp4",
    poster: "./resources/smithy2-fingergun-left.png",
    name: "Smithy 2 Finger Gun (Left)",
    info:
      "Starts the first frame that only 2 of the fired bullets are still on the screen",
    note:
      "The bullet you're looking for to disappear is the second one that bounces over his left shoulder",
    frames: 5,
    relevant: true,
  },
  "Smithy 2 Finger Gun (Middle)": {
    type: "block",
    perfect: 126,
    partialStart: 118,
    partialEnd: 138,
    video: "./resources/smithy2shot.mp4",
    poster: "./resources/smithy2shot.png",
    name: "Smithy 2 Finger Gun (Middle)",
    info:
      "First blockable 2 frames after bottom finger does second explosion (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Smithy 2 Finger Gun (Right)": {
    type: "block",
    perfect: 134,
    partialStart: 126,
    partialEnd: 146,
    video: "./resources/smithy2-fingergun-right.mp4",
    poster: "./resources/smithy2-fingergun-right.png",
    name: "Smithy 2 Finger Gun (Right)",
    info:
      "Starts the first frame that only 2 of the fired bullets are still on the screen",
    note:
      "The bullet you're looking for to disappear is the second one that bounces over his left shoulder",
    frames: 5,
    relevant: true,
  },
  "Smithy 2 Hammer": {
    type: "block",
    perfect: 61,
    partialStart: 54,
    partialEnd: 74,
    video: "./resources/smithy2hammer.mp4",
    poster: "./resources/smithy2hammer.png",
    name: "Smithy 2 Hammer",
    info: "First blockable 1 frame after hammer comes down (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Starslap/Zeostar Attack": {
    type: "block",
    perfect: 158,
    partialStart: 150,
    partialEnd: 171,
    video: "./resources/starslap.mp4",
    poster: "./resources/starslap.png",
    name: "Starslap/Zeostar Attack",
    info:
      "During the last slap animation before the Starslap returns to its position",
    note: "",
    frames: 5,
  },
  "Stumpet Backfire": {
    type: "block",
    perfect: 266,
    partialStart: 258,
    partialEnd: 278,
    video: "./resources/stumpet-backfire.mp4",
    poster: "./resources/stumpet-backfire.png",
    name: "Stumpet Backfire",
    info:
      "The explosion animation is random. Window opens 198 frames/3.3 seconds after the Backfire namebar disappears",
    note: "",
    frames: 5,
  },
  "Stumpet Va Va Voom": {
    type: "block",
    perfect: 265,
    partialStart: 257,
    partialEnd: 277,
    video: "./resources/stumpet-vavavoom.mp4",
    poster: "./resources/stumpet-vavavoom.png",
    name: "Stumpet Va Va Voom",
    info:
      "The explosion animation is random. Window opens 197 frames/3.283 seconds after the Va Va Voom namebar disappears",
    note: "",
    frames: 5,
  },
  "Tentacles (Left) Slap": {
    type: "block",
    perfect: 38,
    partialStart: 30,
    partialEnd: 51,
    video: "./resources/midtentacle.mp4",
    poster: "./resources/midtentacle.png",
    name: "Tentacles (Left) Slap",
    info: "As soon as the tentacle is straight up (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Tentacles (Right) Slap": {
    type: "block",
    perfect: 28,
    partialStart: 20,
    partialEnd: 40,
    video: "./resources/bottomtentacle.mp4",
    poster: "./resources/bottomtentacle.png",
    name: "Tentacles (Right) Slap",
    info: "First blockable 2 frames before fully extended upward. (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Terra Cotta Sword": {
    type: "attack",
    perfect: 63,
    partialStart: 55,
    partialEnd: 76,
    video: "./resources/terracotta.mp4",
    poster: "./resources/terracotta.png",
    name: "Terra Cotta Sword",
    info: "After sword is lowered",
    note: "",
    frames: 5,
  },
  "Toadstool Come Back": {
    type: "attack",
    perfect: 315,
    partialStart: 315,
    partialEnd: 345,
    video: "./resources/peach-comeback.mp4",
    poster: "./resources/peach-comeback.png",
    name: "Toadstool Come Back",
    info: "The entire back half of the time the rainbow star is on the screen",
    note: "Only has a single boost level",
    frames: 31,
  },
  "Toadstool Frying Pan": {
    type: "attack",
    perfect: 13,
    partialStart: 9,
    partialEnd: 34,
    video: "./resources/fryingpan.mp4",
    poster: "./resources/fryingpan.png",
    name: "Toadstool Frying Pan",
    info: "When the glare in the pan is the brightest",
    note: "",
    frames: 7,
  },
  "Toadstool Group Hug": {
    type: "attack",
    perfect: 88,
    partialStart: 88,
    partialEnd: 118,
    video: "./resources/peach-grouphug.mp4",
    poster: "./resources/peach-grouphug.png",
    name: "Toadstool Group Hug",
    info:
      "Only has a single boost level; just aim anywhere in the back half of the animation",
    note: "",
    frames: 31,
  },
  "Toadstool Parasol": {
    type: "attack",
    perfect: 21,
    partialStart: 13,
    partialEnd: 35,
    video: "./resources/parasol.mp4",
    poster: "./resources/parasol.png",
    name: "Toadstool Parasol",
    info: "Time at the instant Peach raises the parasol overhead",
    note: "",
    frames: 7,
  },
  "Toadstool Slap Glove": {
    type: "attack",
    perfect: 20,
    partialStart: 10,
    partialEnd: 47,
    video: "./resources/peachslapglove.mp4",
    poster: "./resources/peachslapglove.png",
    name: "Toadstool Slap Glove",
    info: "When she begins to slap left (7 frames)",
    note: "",
    frames: 7,
  },
  "Toadstool Super Slap": {
    type: "Attack",
    perfect: 16,
    partialStart: 14,
    partialEnd: 43,
    video: "./resources/superslap.mp4",
    poster: "./resources/superslap.png",
    name: "Toadstool Super Slap",
    info: "During the swing of her first slap (7 frames)",
    note: "",
    frames: 7,
    relevant: true,
  },
  "Toadstool Therapy": {
    type: "attack",
    perfect: 240,
    partialStart: 215,
    partialEnd: 245,
    video: "./resources/peach-therapy.mp4",
    poster: "./resources/peach-therapy.png",
    name: "Toadstool Therapy",
    info: "Starts the final frame the blue stars are on screen",
    note: "",
    frames: 5,
  },
  "Toadstool Unarmed": {
    type: "attack",
    perfect: 15,
    partialStart: 5,
    partialEnd: 42,
    video: "./resources/PeachUnarmed.mp4",
    poster: "./resources/PeachUnarmed.png",
    name: "Toadstool Unarmed",
    info: "As her hand starts to slap",
    note:
      "Long half-hit frame window after perfect window (20 frames) and before window (10 frames)",
    frames: 7,
  },
  "Toadstool War Fan": {
    type: "Attack",
    perfect: 16,
    partialStart: 14,
    partialEnd: 37,
    video: "./resources/warfan.mp4",
    poster: "./resources/warfan.png",
    name: "Toadstool War Fan",
    info: "Right after the fan is first raised (7 frames)",
    note:
      "Like Super Slap, the perfect timed window is very early. Unlike all other characters' weapons, there is only a 2 frame half-time buffer before the perfect time window instead of 8 frames",
    frames: 7,
  },
  "Toadstool 2 Attack": {
    type: "block",
    perfect: 26,
    partialStart: 18,
    partialEnd: 38,
    video: "./resources/toadstool_clone_attack.mp4",
    poster: "./resources/toadstool_clone_attack.png",
    name: "Toadstool 2 Attack",
    info: "First blockable frame instant after Peach begins angry animation",
    note: "",
    frames: 5,
  },
  "Torte Attack": {
    type: "block",
    perfect: 82,
    partialStart: 74,
    partialEnd: 93,
    video: "./resources/chefattack.mp4",
    poster: "./resources/chefattack.png",
    name: "Torte Attack",
    info:
      "First blockable when right hand is up for the third time. (5 frames)",
    note:
      "(only 6 partial block frames after the perfect window, instead of 8)",
    frames: 5,
    relevant: true,
  },
  "Valentina Attack": {
    type: "block",
    perfect: 17,
    partialStart: 9,
    partialEnd: 30,
    video: "./resources/valentina.mp4",
    poster: "./resources/valentina.png",
    name: "Valentina Attack",
    info:
      "When her arm is being raised between 45 and 90 degrees pointing at you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Wiggler Ball": {
    type: "block",
    perfect: 147,
    partialStart: 139,
    partialEnd: 160,
    video: "./resources/WigglerBall.mp4",
    poster: "./resources/WigglerBall.png",
    name: "Wiggler Ball",
    info: "After the second splash comes off the ball",
    note: "",
    frames: 5,
  },
  "Wiggler Slam": {
    type: "block",
    perfect: 70,
    partialStart: 62,
    partialEnd: 83,
    video: "./resources/WigglerSlam.mp4",
    poster: "./resources/WigglerSlam.png",
    name: "Wiggler Slam",
    info: "After the wiggler hits the ground, before his mouth starts to close",
    note: "",
    frames: 5,
  },
  "Yaridovich Attack": {
    type: "block",
    perfect: 137,
    partialStart: 129,
    partialEnd: 150,
    video: "./resources/yarid1.mp4",
    poster: "./resources/yarid1.png",
    name: "Yaridovich Attack",
    info: "Halfway during his spear lunge (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  },
  "Yaridovich Orb": {
    type: "block",
    perfect: 34,
    partialStart: 26,
    partialEnd: 47,
    video: "./resources/yarid2.mp4",
    poster: "./resources/yarid2.png",
    name: "Yaridovich Orb",
    info: "when the orb is right in front of your face (5 frames)",
    note: "",
    frames: 5,
  },
  "Yaridovich Pierce": {
    type: "block",
    perfect: 178,
    partialStart: 170,
    partialEnd: 191,
    video: "./resources/yarid3.mp4",
    poster: "./resources/yarid3.png",
    name: "Yaridovich Pierce",
    info:
      "When he has already started retreating, partway through the sound effect (5 frames)",
    note: "",
    frames: 5,
  },
  "Zombone Attack": {
    type: "block",
    perfect: 77,
    partialStart: 69,
    partialEnd: 90,
    video: "./resources/zombone.mp4",
    poster: "./resources/zombone.png",
    name: "Zombone Attack",
    info:
      "While his neck is fully arched upright, right before hitting you (5 frames)",
    note: "",
    frames: 5,
    relevant: true,
  }
};
