var items = [
	{name: "Able Juice", type: "drink"},
	{name: "Amulet", type: "accessory"},
	{name: "Antidote Pin", type: "accessory"},
	{name: "Attack Scarf", type: "accessory"},
	{name: "B'Tub Ring", type: "accessory"},
	{name: "Bad Mushroom", type: "drink"},
	{name: "Bracer", type: "drink"},
	{name: "Bright Card", type: "none"},
	{name: "Carbo Cookie", type: "none"},
	{name: "Chomp", type: "chomp"},
	{name: "Chomp Shell", type: "chomp"},
	{name: "Coin Trick", type: "accessory"},
	{name: "CourageShell", type: "armor"},
	{name: "Crystalline", type: "drink"},
	{name: "Cymbals", type: "music"},
	{name: "Double Punch", type: "glove"},
	{name: "Drill Claw", type: "glove"},
	{name: "EarlierTimes", type: "question"},
	{name: "Elixir", type: "drink"},
	{name: "Energizer", type: "drink"},
	{name: "Exp. Booster", type: "accessory"},
	{name: "Fearless Pin", type: "accessory"},
	{name: "Feather", type: "accessory"},
	{name: "Fertilizer", type: "none"},
	{name: "Finger Shot", type: "geno"},
	{name: "Fire Bomb", type: "bomb"},
	{name: "Fire Cape", type: "armor"},
	{name: "Fire Dress", type: "armor"},
	{name: "Fire Pants", type: "armor"},
	{name: "Fire Shell", type: "armor"},
	{name: "Fire Shirt", type: "armor"},
	{name: "Fireworks", type: "none"},
	{name: "Flower Box", type: "none"},
	{name: "Flower Jar", type: "none"},
	{name: "Flower Tab", type: "none"},
	{name: "Freshen Up", type: "drink"},
	{name: "Fright Bomb", type: "bomb"},
	{name: "FroggieDrink", type: "drink"},
	{name: "FroggieStick", type: "stick"},
	{name: "Frying Pan", type: "pan"},
	{name: "Fuzzy Cape", type: "armor"},
	{name: "Fuzzy Dress", type: "armor"},
	{name: "Fuzzy Pants", type: "armor"},
	{name: "Fuzzy Shirt", type: "armor"},
	{name: "Ghost Medal", type: "accessory"},
	{name: "Goodie Bag", type: "question"},
	{name: "Hammer", type: "hammer"},
	{name: "Hammer (lucky)", type: "hammer"},
	{name: "Hand Cannon", type: "geno"},
	{name: "Hand Gun", type: "geno"},
	{name: "Happy Cape", type: "armor"},
	{name: "Happy Pants", type: "armor"},
	{name: "Happy Shell", type: "armor"},
	{name: "Happy Shirt", type: "armor"},
	{name: "Heal Shell", type: "armor"},
	{name: "Hero Shirt", type: "armor"},
	{name: "Honey Syrup", type: "drink"},
	{name: "Hurly Gloves", type: "glove"},
	{name: "Ice Bomb", type: "bomb"},
	{name: "Jinx Belt", type: "accessory"},
	{name: "Jump Shoes", type: "accessory"},
	{name: "KerokeroCola", type: "drink"},
	{name: "Lamb's Lure", type: "question"},
	{name: "Lazy Shell", type: "shell"},
	{name: "Lazy Shell", type: "armor"},
	{name: "Lamb's Lure", type: "Lucky Jewel"},
	{name: "Maple Syrup", type: "drink"},
	{name: "Masher", type: "hammer"},
	{name: "Max Mushroom", type: "drink"},
	{name: "Mega Cape", type: "armor"},
	{name: "Mega Glove", type: "glove"},
	{name: "Mega Pants", type: "armor"},
	{name: "Mega Shirt", type: "armor"},
	{name: "Megalixir", type: "drink"},
	{name: "Mid Mushroom", type: "drink"},
	{name: "Moldy Mush", type: "drink"},
	{name: "Muku Cookie", type: "dot"},
	{name: "Mushroom", type: "drink"},
	{name: "Mushroom (but...)", type: "drink"},
	{name: "Mystery Egg", type: "question"},
	{name: "NauticaDress", type: "armor"},
	{name: "NokNok Shell", type: "shell"},
	{name: "Pants", type: "armor"},
	{name: "Parasol", type: "stick"},
	{name: "Pick Me Up", type: "drink"},
	{name: "Polka Dress", type: "armor"},
	{name: "Power Blast", type: "drink"},
	{name: "Prince Pants", type: "armor"},
	{name: "Punch Glove", type: "glove"},
	{name: "Pure Water", type: "bomb"},
	{name: "Quartz Charm", type: "accessory"},
	{name: "Rare Scarf", type: "accessory"},
	{name: "Red Essence", type: "drink"},
	{name: "Ribbit Stick", type: "stick"},
	{name: "Rock Candy", type: "bomb"},
	{name: "Rotten Mush", type: "drink"},
	{name: "Royal Dress", type: "armor"},
	{name: "Royal Syrup", type: "drink"},
	{name: "Safety Badge", type: "accessory"},
	{name: "Safety Ring", type: "accessory"},
	{name: "Sailor Cape", type: "armor"},
	{name: "Sailor Pants", type: "armor"},
	{name: "Sailor Shirt", type: "armor"},
	{name: "Scrooge Ring", type: "accessory"},
	{name: "See Ya", type: "question"},
	{name: "Seed", type: "none"},
	{name: "Sheep Attack", type: "question"},
	{name: "Shiny Stone", type: "none"},
	{name: "Shirt", type: "armor"},
	{name: "Signal Ring", type: "accessory"},
	{name: "Slap Glove", type: "glove"},
	{name: "Sleepy Bomb", type: "bomb"},
	{name: "Sonic Cymbal", type: "music"},
	{name: "Spiked Link", type: "chomp"},
	{name: "Star Cape", type: "armor"},
	{name: "Star Egg", type: "bomb"},
	{name: "Star Gun", type: "geno"},
	{name: "Sticky Glove", type: "glove"},
	{name: "Super Hammer", type: "hammer"},
	{name: "Super Slap", type: "glove"},
	{name: "Super Suit", type: "armor"},
	{name: "Thick Pants", type: "armor"},
	{name: "Thick Shirt", type: "armor"},
	{name: "Troopa Pin", type: "accessory"},
	{name: "Troopa Shell", type: "shell"},
	{name: "Trueform Pin", type: "accessory"},
	{name: "Ultra Hammer", type: "hammer"},
	{name: "Wake Up Pin", type: "accessory"},
	{name: "Wallet", type: "none"},
	{name: "War Fan", type: "pan"},
	{name: "Whomp Glove", type: "glove"},
	{name: "Wilt Shroom", type: "drink"},
	{name: "Work Pants", type: "armor"},
	{name: "Yoshi Candy", type: "dot"},
	{name: "Yoshi Cookie", type: "dot"},
	{name: "Yoshi-Ade", type: "drink"},
	{name: "Zoom Shoes", type: "accessory"},
]

var locations = [
	{name: "M-Kingdom", map: "default"},
	{name: "Tadpole-JB", map: "semilocked"},
	{name: "Rose-Item", map: "default"},
	{name: "Rose-Arm", map: "default"},
	{name: "Moleville", map: "default"},
	{name: "Marrymore", map: "default"},
	{name: "Seaside-1", map: "missable"},
	{name: "Sea-Ship", map: "default"},
	{name: "Monstro-Item", map: "default"},
	{name: "Monstro-Trip", map: "default"},
	{name: "Nimbus", map: "default"},
	{name: "Croco-1", map: "default"},
	{name: "Seaside-Item", map: "locked"},
	{name: "Seaside-Wpn", map: "locked"},
	{name: "Seaside-Arm", map: "locked"},
	{name: "Seaside-Acc", map: "locked"},
	{name: "Volcano-Item", map: "locked"},
	{name: "Volcano-Arm", map: "locked"},
	{name: "Croco-2", map: "locked"},
	{name: "Toad", map: "locked"},
	{name: "Tadpole-FCE", map: "frog"},
	{name: "Seaside-FC", map: "frog"},
]