import {
  LevelupBonus,
  Character,
  WeaponName,
  ArmorName,
  AccessoryName,
  AttackName,
  Party,
} from "./types";

let CHARACTER_DATA: Character[] = [
  {
    id: Party.MARIO,
    name: "Mario",
    minLevel: 1,
    speed: 20,
    levelBonuses: [
      {
        stats: {
          hp: 20,
          attack: 20,
          defense: 0,
          magicAttack: 10,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 0 },
          pow: { attack: 0, defense: 0 },
          sp: { magicAttack: 0, magicDefense: 0 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 3,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 3,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 3,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 3,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 4,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 6,
          attack: 4,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 6,
          attack: 4,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 4,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 4,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 5,
          defense: 4,
          magicAttack: 3,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 10,
          attack: 6,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 10,
          attack: 6,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 10,
          attack: 6,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
    ],
    statbonuses: Array.from({ length: 29 }, () => LevelupBonus.HP),
    level: 1,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.JUMP,
      AttackName.FIREBALL,
      AttackName.SUPER_JUMP,
      AttackName.SUPER_FIREBALL,
      AttackName.ULTRA_JUMP,
      AttackName.ULTRA_FIREBALL,
      AttackName.STAR_GUST,
      AttackName.STAR_RIDERS,
      AttackName.CLOWN_CAR_BARRAGE,
      AttackName.SHOOTING_STAR_SHOT,
      AttackName.STARRY_SHELL_SPIKE,
      AttackName.BAD_MUSHROOM,
      AttackName.FRIGHT_BOMB,
      AttackName.STAR_EGG,
      AttackName.FIRE_BOMB,
      AttackName.ICE_BOMB,
      AttackName.ROCK_CANDY,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.HAMMER,
      WeaponName.KOOPA_SHELL,
      WeaponName.LAZY_SHELL,
      WeaponName.LUCKY_HAMMER,
      WeaponName.MASHER,
      WeaponName.MEGA_GLOVE,
      WeaponName.PARATROOPA_SHELL,
      WeaponName.PUNCH_GLOVE,
      WeaponName.SUPER_HAMMER,
      WeaponName.ULTRA_HAMMER,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_SHIRT,
      ArmorName.FLUFFY_SHIRT,
      ArmorName.HAPPY_SHIRT,
      ArmorName.HERO_SHIRT,
      ArmorName.LAZY_SHELL,
      ArmorName.MEGA_SHIRT,
      ArmorName.SAILOR_SHIRT,
      ArmorName.SHIRT,
      ArmorName.SUPER_SUIT,
      ArmorName.THICK_SHIRT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.ATTACK_SCARF,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.COIN_TRICK,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.JUMP_SHOES,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TEAMWORK_BAND,
      AccessoryName.TROOPA_MEDAL,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
    hasAttackBoost: false,
    hasDefenseBoost: false,
    isFeared: false,
  },
  {
    id: Party.MALLOW,
    name: "Mallow",
    speed: 18,
    minLevel: 2,
    levelBonuses: [
      {
        stats: {
          hp: 20,
          attack: 22,
          defense: 3,
          magicAttack: 15,
          magicDefense: 10,
        },
        bonus: {
          hp: { hp: 0 },
          pow: { attack: 0, defense: 0 },
          sp: { magicAttack: 0, magicDefense: 0 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 2,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 3,
          defense: 3,
          magicAttack: 3,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 3,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 6,
          attack: 3,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 6,
          attack: 3,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 6,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 4,
          defense: 3,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 4,
          defense: 3,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 4,
          defense: 3,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 5,
          defense: 3,
          magicAttack: 5,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 3,
          magicAttack: 5,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 3,
          magicAttack: 5,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 4 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 2, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
    ],
    statbonuses: Array.from({ length: 28 }, () => LevelupBonus.HP),
    level: 2,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.THUNDERBOLT,
      AttackName.SHOCKER,
      AttackName.SNOWY,
      AttackName.STAR_RAIN,
      AttackName.STAR_GUST,
      AttackName.STAR_RIDERS,
      AttackName.CLOWN_CAR_BARRAGE,
      AttackName.BAD_MUSHROOM,
      AttackName.FRIGHT_BOMB,
      AttackName.STAR_EGG,
      AttackName.FIRE_BOMB,
      AttackName.ICE_BOMB,
      AttackName.ROCK_CANDY,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.CYMBALS,
      WeaponName.FROGGIE_STICK,
      WeaponName.RIBBIT_STICK,
      WeaponName.SAGE_STICK,
      WeaponName.SONIC_CYMBALS,
      WeaponName.STICKY_GLOVE,
      WeaponName.WHOMP_GLOVE,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_PANTS,
      ArmorName.FLUFFY_PANTS,
      ArmorName.HAPPY_PANTS,
      ArmorName.LAZY_SHELL,
      ArmorName.MEGA_PANTS,
      ArmorName.PANTS,
      ArmorName.PRINCE_PANTS,
      ArmorName.SAILOR_PANTS,
      ArmorName.SUPER_SUIT,
      ArmorName.THICK_PANTS,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TEAMWORK_BAND,
      AccessoryName.TROOPA_MEDAL,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
    hasAttackBoost: false,
    hasDefenseBoost: false,
    isFeared: false,
  },
  {
    id: Party.GENO,
    name: "Geno",
    minLevel: 6,
    speed: 30,
    levelBonuses: [
      {
        stats: {
          hp: 45,
          attack: 60,
          defense: 23,
          magicAttack: 25,
          magicDefense: 17,
        },
        bonus: {
          hp: { hp: 0 },
          pow: { attack: 0, defense: 0 },
          sp: { magicAttack: 0, magicDefense: 0 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 6,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 6,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 6 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 6,
          defense: 4,
          magicAttack: 5,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 1,
          attack: 2,
          defense: 3,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
    ],
    statbonuses: Array.from({ length: 24 }, () => LevelupBonus.HP),
    level: 6,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.GENO_BEAM,
      AttackName.GENO_WHIRL,
      AttackName.GENO_BLAST,
      AttackName.GENO_FLASH,
      AttackName.STAR_GUST,
      AttackName.STAR_RIDERS,
      AttackName.SHOOTING_STAR_SHOT,
      AttackName.BAD_MUSHROOM,
      AttackName.FRIGHT_BOMB,
      AttackName.STAR_EGG,
      AttackName.FIRE_BOMB,
      AttackName.ICE_BOMB,
      AttackName.ROCK_CANDY,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.DOUBLE_PUNCH,
      WeaponName.FINGER_SHOT,
      WeaponName.HAND_CANNON,
      WeaponName.HAND_GUN,
      WeaponName.STAR_GUN,
      WeaponName.STELLA_023,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_CAPE,
      ArmorName.FLUFFY_CAPE,
      ArmorName.HAPPY_CAPE,
      ArmorName.LAZY_SHELL,
      ArmorName.MEGA_CAPE,
      ArmorName.SAILOR_CAPE,
      ArmorName.STAR_CAPE,
      ArmorName.SUPER_SUIT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TEAMWORK_BAND,
      AccessoryName.TROOPA_MEDAL,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
    hasAttackBoost: false,
    hasDefenseBoost: false,
    isFeared: false,
  },
  {
    id: Party.BOWSER,
    name: "Bowser",
    minLevel: 8,
    speed: 15,
    levelBonuses: [
      {
        stats: {
          hp: 80,
          attack: 85,
          defense: 52,
          magicAttack: 20,
          magicDefense: 30,
        },
        bonus: {
          hp: { hp: 0 },
          pow: { attack: 0, defense: 0 },
          sp: { magicAttack: 0, magicDefense: 0 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 3,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 3,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 5,
          defense: 4,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 4,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 4,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 2, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
    ],
    statbonuses: Array.from({ length: 22 }, () => LevelupBonus.HP),
    level: 8,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.TERRORIZE,
      AttackName.POISON_GAS,
      AttackName.CRUSHER,
      AttackName.MECHAKOOPA_STOMP,
      AttackName.STAR_GUST,
      AttackName.CLOWN_CAR_BARRAGE,
      AttackName.SHOOTING_STAR_SHOT,
      AttackName.STARRY_SHELL_SPIKE,
      AttackName.BAD_MUSHROOM,
      AttackName.FRIGHT_BOMB,
      AttackName.STAR_EGG,
      AttackName.FIRE_BOMB,
      AttackName.ICE_BOMB,
      AttackName.ROCK_CANDY,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.CHAIN_CHOMP,
      WeaponName.DRILL_CLAW,
      WeaponName.FAKE_CHOMP,
      WeaponName.HURLY_GLOVE,
      WeaponName.SPIKED_CHOMP,
      WeaponName.WONDER_CHOMP,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.COURAGE_SHELL,
      ArmorName.FIRE_SHELL,
      ArmorName.HAPPY_SHELL,
      ArmorName.HEEL_SHELL,
      ArmorName.LAZY_SHELL,
      ArmorName.SUPER_SUIT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TEAMWORK_BAND,
      AccessoryName.TROOPA_MEDAL,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
    hasAttackBoost: false,
    hasDefenseBoost: false,
    isFeared: false,
  },
  {
    id: Party.PEACH,
    name: "Peach",
    speed: 24,
    minLevel: 9,
    levelBonuses: [
      {
        stats: {
          hp: 50,
          attack: 40,
          defense: 24,
          magicAttack: 40,
          magicDefense: 28,
        },
        bonus: {
          hp: { hp: 0 },
          pow: { attack: 0, defense: 0 },
          sp: { magicAttack: 0, magicDefense: 0 },
        },
      },
      {
        stats: {
          hp: 4,
          attack: 1,
          defense: 3,
          magicAttack: 4,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 9 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 5,
          attack: 2,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 6,
          attack: 3,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 7,
          attack: 4,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 9 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 8,
          attack: 5,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 9,
          attack: 6,
          defense: 3,
          magicAttack: 4,
          magicDefense: 3,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 10,
          attack: 7,
          defense: 3,
          magicAttack: 4,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 9 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 11,
          attack: 8,
          defense: 4,
          magicAttack: 4,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 12,
          attack: 9,
          defense: 4,
          magicAttack: 4,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 13,
          attack: 10,
          defense: 4,
          magicAttack: 4,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 9 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 14,
          attack: 10,
          defense: 4,
          magicAttack: 4,
          magicDefense: 4,
        },
        bonus: {
          hp: { hp: 5 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 2 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 1 },
          pow: { attack: 1, defense: 1 },
          sp: { magicAttack: 3, magicDefense: 1 },
        },
      },
      {
        stats: {
          hp: 2,
          attack: 2,
          defense: 2,
          magicAttack: 2,
          magicDefense: 2,
        },
        bonus: {
          hp: { hp: 3 },
          pow: { attack: 3, defense: 1 },
          sp: { magicAttack: 1, magicDefense: 1 },
        },
      },
    ],
    statbonuses: Array.from({ length: 21 }, () => LevelupBonus.HP),
    level: 9,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.PSYCH_BOMB,
      AttackName.STAR_GUST,
      AttackName.STARRY_SHELL_SPIKE,
      AttackName.BAD_MUSHROOM,
      AttackName.FRIGHT_BOMB,
      AttackName.STAR_EGG,
      AttackName.FIRE_BOMB,
      AttackName.ICE_BOMB,
      AttackName.ROCK_CANDY,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.FRYING_PAN,
      WeaponName.PARASOL,
      WeaponName.SLAP_GLOVE,
      WeaponName.SUPER_SLAP,
      WeaponName.WAR_FAN,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_DRESS,
      ArmorName.FLUFFY_DRESS,
      ArmorName.LAZY_SHELL,
      ArmorName.LOVELY_DRESS,
      ArmorName.ROYAL_DRESS,
      ArmorName.SAILOR_DRESS,
      ArmorName.SUPER_SUIT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.NURTURE_RING,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TEAMWORK_BAND,
      AccessoryName.TROOPA_MEDAL,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
    hasAttackBoost: false,
    hasDefenseBoost: false,
    isFeared: false,
  },
];

export default CHARACTER_DATA;
