import {
  LevelupBonus,
  Character,
  WeaponName,
  ArmorName,
  AccessoryName,
  AttackName,
} from "./types";

let CHARACTER_DATA: Character[] = [
  {
    id: "mario",
    name: "Mario",
    minLevel: 1,
    statbonuses: Array.from({ length: 29 }, () => LevelupBonus.HP),
    level: 1,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.JUMP,
      AttackName.FIREBALL,
      AttackName.SUPER_JUMP,
      AttackName.SUPER_FIREBALL,
      AttackName.ULTRA_JUMP,
      AttackName.ULTRA_FIREBALL,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.HAMMER,
      WeaponName.KOOPA_SHELL,
      WeaponName.LAZY_SHELL,
      WeaponName.LUCKY_HAMMER,
      WeaponName.MASHER,
      WeaponName.MEGA_GLOVE,
      WeaponName.PARATROOPA_SHELL,
      WeaponName.PUNCH_GLOVE,
      WeaponName.SUPER_HAMMER,
      WeaponName.ULTRA_HAMMER,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_SHIRT,
      ArmorName.FUZZY_SHIRT,
      ArmorName.HAPPY_SHIRT,
      ArmorName.HERO_SHIRT,
      ArmorName.LAZY_SHELL,
      ArmorName.MEGA_SHIRT,
      ArmorName.SAILOR_SHIRT,
      ArmorName.SHIRT,
      ArmorName.SUPER_SUIT,
      ArmorName.THICK_SHIRT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.ATTACK_SCARF,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.COIN_TRICK,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.JUMP_SHOES,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TROOPA_PIN,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
  },
  {
    id: "mallow",
    name: "Mallow",
    minLevel: 2,
    statbonuses: Array.from({ length: 28 }, () => LevelupBonus.HP),
    level: 2,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.THUNDERBOLT,
      AttackName.SHOCKER,
      AttackName.SNOWY,
      AttackName.STAR_RAIN,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.CYMBALS,
      WeaponName.FROGGIE_STICK,
      WeaponName.RIBBIT_STICK,
      WeaponName.SAGE_STICK,
      WeaponName.SONIC_CYMBALS,
      WeaponName.STICKY_GLOVE,
      WeaponName.WHOMP_GLOVE,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_PANTS,
      ArmorName.FUZZY_PANTS,
      ArmorName.HAPPY_PANTS,
      ArmorName.LAZY_SHELL,
      ArmorName.MEGA_PANTS,
      ArmorName.PRINCE_PANTS,
      ArmorName.PANTS,
      ArmorName.SAILOR_PANTS,
      ArmorName.SUPER_SUIT,
      ArmorName.THICK_PANTS,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TROOPA_PIN,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
  },
  {
    id: "geno",
    name: "Geno",
    minLevel: 6,
    statbonuses: Array.from({ length: 24 }, () => LevelupBonus.HP),
    level: 6,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.GENO_BEAM,
      AttackName.GENO_WHIRL,
      AttackName.GENO_BLAST,
      AttackName.GENO_FLASH,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.DOUBLE_PUNCH,
      WeaponName.FINGER_SHOT,
      WeaponName.HAND_CANNON,
      WeaponName.HAND_GUN,
      WeaponName.STELLA_023,
      WeaponName.STAR_GUN,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_CAPE,
      ArmorName.FUZZY_CAPE,
      ArmorName.HAPPY_CAPE,
      ArmorName.LAZY_SHELL,
      ArmorName.MEGA_CAPE,
      ArmorName.SAILOR_CAPE,
      ArmorName.STAR_CAPE,
      ArmorName.SUPER_SUIT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TROOPA_PIN,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
  },
  {
    id: "bowser",
    name: "Bowser",
    minLevel: 8,
    statbonuses: Array.from({ length: 22 }, () => LevelupBonus.HP),
    level: 8,
    attacks: [
      AttackName.PHYSICAL,
      AttackName.TERRORIZE,
      AttackName.POISON_GAS,
      AttackName.CRUSHER,
      AttackName.BOWSER_CRUSH,
    ],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.CHAIN_CHOMP,
      WeaponName.DRILL_CLAW,
      WeaponName.FAKE_CHOMP,
      WeaponName.HURLY_GLOVES,
      WeaponName.SPIKED_CHOMP,
      WeaponName.WONDER_CHOMP,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.COURAGE_SHELL,
      ArmorName.FIRE_SHELL,
      ArmorName.HAPPY_SHELL,
      ArmorName.HEEL_SHELL,
      ArmorName.LAZY_SHELL,
      ArmorName.SUPER_SUIT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TROOPA_PIN,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
  },
  {
    id: "peach",
    name: "Peach",
    minLevel: 9,
    statbonuses: Array.from({ length: 21 }, () => LevelupBonus.HP),
    level: 9,
    attacks: [AttackName.PHYSICAL, AttackName.PSYCH_BOMB],
    weapons: [
      WeaponName.UNARMED,
      WeaponName.FRYING_PAN,
      WeaponName.PARASOL,
      WeaponName.SLAP_GLOVE,
      WeaponName.SUPER_SLAP,
      WeaponName.WAR_FAN,
    ],
    armors: [
      ArmorName.NONE,
      ArmorName.FIRE_DRESS,
      ArmorName.FUZZY_DRESS,
      ArmorName.LAZY_SHELL,
      ArmorName.LOVELY_DRESS,
      ArmorName.ROYAL_DRESS,
      ArmorName.SAILOR_DRESS,
      ArmorName.SUPER_SUIT,
      ArmorName.WORK_PANTS,
    ],
    accessories: [
      AccessoryName.NONE,
      AccessoryName.ANTIDOTE_PIN,
      AccessoryName.BOOSTERS_CHARM,
      AccessoryName.DEFENSE_SCARF,
      AccessoryName.ECHO_SIGNAL_RING,
      AccessoryName.ENDURING_BROOCH,
      AccessoryName.EXP_BOOSTER,
      AccessoryName.FEARLESS_PIN,
      AccessoryName.FEATHER,
      AccessoryName.FLOWER_RING,
      AccessoryName.GHOST_MEDAL,
      AccessoryName.JINX_BELT,
      AccessoryName.NURTURE_RING,
      AccessoryName.QUARTZ_CHARM,
      AccessoryName.SAFETY_BADGE,
      AccessoryName.SAFETY_RING,
      AccessoryName.SIGNAL_RING,
      AccessoryName.TROOPA_PIN,
      AccessoryName.TRUEFORM_PIN,
      AccessoryName.WAKE_UP_PIN,
      AccessoryName.ZOOM_SHOES,
    ],
    activeWeapon: WeaponName.UNARMED,
    activeArmor: ArmorName.NONE,
    activeAccessory: AccessoryName.NONE,
    activeAttack: AttackName.PHYSICAL,
  },
];

export default CHARACTER_DATA;
