export enum LevelupBonus {
  ATTACK = 0,
  HP = 1,
  SP = 2,
}

export enum HitType {
  HIT = "0",
  BLOCK = "1",
}

export enum AttackBoostModifier {
  BOOSTED = "1.5",
  FEARED = "0.5",
  NONE = "1",
}

export enum AttackTimingModifier {
  PERFECT = "2",
  PARTIAL = "1.5",
  NONE = "1",
}

export enum AttackElement {
  FIRE = "Fire",
  THUNDER = "Thunder",
  ICE = "Ice",
  JUMP = "Jump",
  CRITICAL = "Critical",
  NONE = "None",
}

export enum AttackType {
  PHYSICAL = 0,
  SPELL = 1,
}

export interface Attack {
  name: string;
  formula: (args: number[]) => number;
  type: AttackType;
  basepower: number;
  minLevel: number;
  element: AttackElement;
}

export interface EnemyAttack {
  name: string;
  basepower: number;
  element: AttackElement;
  multiplier: number;
  blockable: boolean;
}

export interface Weapon {
  name: string;
  basepower: number;
  variance: number;
}

export interface Armor {
  name: string;
  defense: number;
  magicDefense: number;
  attack: number;
  magicAttack: number;
  speed: number;
}
export interface Accessory {
  name: string;
  defense: number;
  magicDefense: number;
  attack: number;
  magicAttack: number;
  speed: number;
}

enum EnemyAttackName {
  PHYSICAL = "Physical",
  PHYSICAL_1_5X = "Physical 1.5x",
  PHYSICAL_2X = "Physical 2x",
  ARROW_RAIN = "Arrow Rain",
  AURORA_FLASH = "Aurora Flash",
  BACKFIRE = "Backfire",
  BIG_BANG = "Big Bang",
  BLAST = "Blast",
  BLAZER = "Blazer",
  BLIZZARD = "Blizzard",
  BODY_SLAM = "Body Slam",
  BOLT = "Bolt",
  BOMBS_AWAY = "Bombs Away",
  BOULDER = "Boulder",
  BREAKER_BEAM = "Breaker Beam",
  CARNI_KISS = "Carni-Kiss",
  CHEST_HEAD_SCARECROW_SPELL = "Chest head scarecrow spell",
  CHOMP = "Chomp",
  CLAW = "Claw",
  CRYSTAL = "Crystal",
  DARK_CLAW = "Dark Claw",
  DARK_STAR = "Dark Star",
  DEATHSICKLE = "Deathsickle",
  DIAMOND_SAW = "Diamond Saw",
  ECHO_FINDER = "Echofinder",
  ELECTROSHOCK = "Electroshock",
  FANGS = "Fangs",
  FEAR_ROULETTE = "Fear Roulette",
  FINAL_CLAW = "Final Claw",
  FIRE_SABER = "Fire Saber",
  FLAME_STONE = "Flame Stone",
  FLAME_WALL = "Flame Wall",
  FLAME = "Flame",
  FLARE = "Flare",
  FULL_HOUSE = "Full House",
  FUN_AND_RUN = "Fun & Run",
  FUNGUSPIKE = "Funguspike",
  GRINDER = "Grinder",
  GUNK_BALL = "Gunk Ball",
  HAMMER_TIME = "Hammer Time",
  HOT_SHOT = "Hot Shot",
  ICE_ROCK = "Ice Rock",
  INK_BLAST = "Ink Blast",
  JINXED = "Jinxed",
  LAST_SHOT = "Last Shot!",
  LIGHT_BEAM = "Light Beam",
  LIGHTNING_ORB = "Lightning Orb",
  LOCO_EXPRESS = "Loco Express",
  MAGNUM = "Magnum",
  MEGA_RECOVER = "Mega Recover",
  METEOR_BLAST = "Meteor Blast",
  METEOR_SWARM = "Meteor Swarm",
  MIGRAINE = "Migraine",
  MULTISTRIKE = "Multistrike",
  PAIN_SPOUT = "Pain Spout",
  PETAL_BLAST = "Petal Blast",
  PIERCE = "Pierce",
  POISON = "Poison",
  PSYCHE = "Psyche!",
  QUICKSILVER = "Quicksilver",
  RECOVER = "Recover",
  SAND_STORM = "Sand Storm",
  SCYTHE = "Scythe",
  SHAKER = "Shaker",
  SILVER_BULLET = "Silver Bullet",
  SKEWER = "Skewer",
  SLEDGE = "Sledge",
  SOLIDIFY = "Solidify",
  SPEAR_RAIN = "Spear Rain",
  SPRITZ_BOMB = "Spritz Bomb",
  STATIC_E = "Static E!",
  STORM = "Storm",
  SWORD_RAIN = "Sword Rain",
  TERRAPUNCH = "Terrapunch",
  THORNET = "Thornet",
  TRIPLE_KICK = "Triple Kick",
  VA_VA_VOOM = "Va Va Voom",
  WATER_BLAST = "Water Blast",
  WEIRD_MUSHROOM = "Weird Mushroom",
  WILD_CARD = "Wild Card",
  WILL_O_WISP = "Will-o-Wisp",
}

export const enemyAttacks = [
  {
    name: EnemyAttackName.PHYSICAL,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: true,
  },
  {
    name: EnemyAttackName.PHYSICAL_1_5X,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.PHYSICAL_2X,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2,
    blockable: true,
  },
  {
    name: EnemyAttackName.ARROW_RAIN,
    basepower: 40,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.AURORA_FLASH,
    basepower: 50,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.BACKFIRE,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.BIG_BANG,
    basepower: 120,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.BLAST,
    basepower: 89,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.BLAZER,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.BLIZZARD,
    basepower: 22,
    element: AttackElement.ICE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.BODY_SLAM,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.BOLT,
    basepower: 20,
    element: AttackElement.THUNDER,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.BOMBS_AWAY,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 4.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.BOULDER,
    basepower: 72,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.BREAKER_BEAM,
    basepower: 80,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.CARNI_KISS,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.CHEST_HEAD_SCARECROW_SPELL,
    basepower: 10,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.CHOMP,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.CLAW,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.FLARE,
    basepower: 88,
    element: AttackElement.FIRE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.CRYSTAL,
    basepower: 25,
    element: AttackElement.ICE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.DARK_CLAW,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: false,
  },
  {
    name: EnemyAttackName.DARK_STAR,
    basepower: 160,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.DEATHSICKLE,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.DIAMOND_SAW,
    basepower: 60,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.ECHO_FINDER,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: false,
  },
  {
    name: EnemyAttackName.ELECTROSHOCK,
    basepower: 72,
    element: AttackElement.THUNDER,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.FANGS,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.FEAR_ROULETTE,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.FINAL_CLAW,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.FIRE_SABER,
    basepower: 40,
    element: AttackElement.FIRE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.FLAME_STONE,
    basepower: 32,
    element: AttackElement.FIRE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.FLAME_WALL,
    basepower: 8,
    element: AttackElement.FIRE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.FLAME,
    basepower: 12,
    element: AttackElement.FIRE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.FULL_HOUSE,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.FUN_AND_RUN,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.FUNGUSPIKE,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.GRINDER,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.GUNK_BALL,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: false,
  },
  {
    name: EnemyAttackName.HAMMER_TIME,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.HOT_SHOT,
    basepower: 4,
    element: AttackElement.FIRE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.ICE_ROCK,
    basepower: 130,
    element: AttackElement.ICE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.INK_BLAST,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.JINXED,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.LAST_SHOT,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 4.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.LIGHT_BEAM,
    basepower: 34,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.LIGHTNING_ORB,
    basepower: 8,
    element: AttackElement.THUNDER,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.LOCO_EXPRESS,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 4.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.MAGNUM,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.MEGA_RECOVER,
    basepower: 200,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.METEOR_BLAST,
    basepower: 30,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.METEOR_SWARM,
    basepower: 100,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.MIGRAINE,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.MULTISTRIKE,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.PAIN_SPOUT,
    basepower: 26,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.PETAL_BLAST,
    basepower: 40,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.PIERCE,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.POISON,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: false,
  },
  {
    name: EnemyAttackName.PSYCHE,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.QUICKSILVER,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.RECOVER,
    basepower: 50,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.SAND_STORM,
    basepower: 16,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.SCYTHE,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.SHAKER,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.SILVER_BULLET,
    basepower: 0,
    element: AttackElement.CRITICAL,
    multiplier: 0.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.SKEWER,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.SLEDGE,
    basepower: 50,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.SOLIDIFY,
    basepower: 47,
    element: AttackElement.ICE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.SPEAR_RAIN,
    basepower: 60,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.SPRITZ_BOMB,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: false,
  },
  {
    name: EnemyAttackName.STATIC_E,
    basepower: 12,
    element: AttackElement.THUNDER,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.STORM,
    basepower: 108,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.SWORD_RAIN,
    basepower: 80,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.TERRAPUNCH,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 2.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.THORNET,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: false,
  },
  {
    name: EnemyAttackName.TRIPLE_KICK,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.VA_VA_VOOM,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 1.5,
    blockable: true,
  },
  {
    name: EnemyAttackName.WATER_BLAST,
    basepower: 39,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.WEIRD_MUSHROOM,
    basepower: 30,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
  {
    name: EnemyAttackName.WILD_CARD,
    basepower: 0,
    element: AttackElement.NONE,
    multiplier: 4.0,
    blockable: true,
  },
  {
    name: EnemyAttackName.WILL_O_WISP,
    basepower: 48,
    element: AttackElement.NONE,
    multiplier: 1,
    blockable: false,
  },
];

export enum WeaponName {
  UNARMED = "Unarmed (すで)",
  CHAIN_CHOMP = "Chain Chomp (ワンワン)",
  CYMBALS = "Cymbals (シンバル)",
  DOUBLE_PUNCH = "Double Punch (スーパーダブルパンチ)",
  DRILL_CLAW = "Drill Claw (ドリルクロー)",
  FAKE_CHOMP = "Fake Chomp (ワンワンのぬけがら)",
  FINGER_SHOT = "Finger Shot (フィンガーショット)",
  FROGGIE_STICK = "Froggie Stick (ケロケロのつえ)",
  FRYING_PAN = "Frying Pan (フライパン)",
  HAMMER = "Hammer (ハンマー)",
  HAND_CANNON = "Hand Cannon (ハンドキャノン)",
  HAND_GUN = "Hand Gun (ハンドガン)",
  HURLY_GLOVES = "Hurly Gloves (ぶんなげグローブ)",
  LAZY_SHELL = "Lazy Shell (ひまんパタこうら)",
  LUCKY_HAMMER = "Lucky Hammer",
  MASHER = "Masher (ムラっけハンマー)",
  MEGA_GLOVE = "Mega Glove (でかパンチグローブ)",
  KOOPA_SHELL = "Koopa Shell (ノコノコこうら)",
  PARASOL = "Parasol (パラソル)",
  PARATROOPA_SHELL = "Paratroopa Shell (パタパタこうら)",
  PUNCH_GLOVE = "Punch Glove (パンチグローブ)",
  RIBBIT_STICK = "Ribbit Stick (ゲコゲコのつえ)",
  SAGE_STICK = "Sage Stick",
  SLAP_GLOVE = "Slap Glove (ビンタグローブ)",
  SONIC_CYMBALS = "Sonic Cymbals (ソニックシンバル)",
  SPIKED_CHOMP = "Spiked Chomp (トゲワンワン)",
  STAR_GUN = "Star Gun (スターガン)",
  STELLA_023 = "Stella 023",
  STICKY_GLOVE = "Sticky Glove (くっつきグローブ)",
  SUPER_HAMMER = "Super Hammer (スーパーハンマー)",
  SUPER_SLAP = "Super Slap (ちょービンタグローブ)",
  ULTRA_HAMMER = "Ultra Hammer (ウルトラハンマー)",
  WAR_FAN = "War Fan (センス)",
  WHOMP_GLOVE = "Whomp Glove (のびパンチグローブ)",
  WONDER_CHOMP = "Wonder Chomp",
}

export enum ArmorName {
  NONE = "(NONE)",
  FIRE_SHIRT = "Fire Shirt (ファイアつなぎ)",
  FUZZY_SHIRT = "Fuzzy Shirt (ふかふかつなぎ)",
  HAPPY_SHIRT = "Happy Shirt (ハッピーつなぎ)",
  HERO_SHIRT = "Hero Shirt (ヒーローつなぎ)",
  LAZY_SHELL = "Lazy Shell (ひまんパタこうら)",
  MEGA_SHIRT = "Mega Shirt (ばっちりつなぎ)",
  SAILOR_SHIRT = "Sailor Shirt (セーラーつなぎ)",
  SHIRT = "Shirt (ふつうのつなぎ)",
  SUPER_SUIT = "Super Suit (スーパージャンパー)",
  THICK_SHIRT = "Thick Shirt (しっかりつなぎ)",
  WORK_PANTS = "Work Pants (ばっちいパンツ)",
  FIRE_PANTS = "Fire Pants (ファイアパンツ)",
  FUZZY_PANTS = "Fuzzy Pants (ふかふかパンツ)",
  HAPPY_PANTS = "Happy Pants (ハッピーパンツ)",
  MEGA_PANTS = "Mega Pants (ばっちりパンツ)",
  PRINCE_PANTS = "Prince Pants (プリンスパンツ)",
  SAILOR_PANTS = "Sailor Pants (セーラーパンツ)",
  PANTS = "Pants (ふつうのパンツ)",
  THICK_PANTS = "Thick Pants (しっかりパンツ)",
  STAR_CAPE = "Star Cape (スターマント)",
  FIRE_CAPE = "Fire Cape (ファイアマント)",
  FUZZY_CAPE = "Fuzzy Cape (ふかふかマント)",
  HAPPY_CAPE = "Happy Cape (ハッピーマント)",
  MEGA_CAPE = "Mega Cape (ばっちりマント)",
  SAILOR_CAPE = "Sailor Cape (セーラーマント)",
  CAPE = "Cape (ふつうのマント)",
  COURAGE_SHELL = "Courage Shell (むてきのこうら)",
  FIRE_SHELL = "Fire Shell (ファイアシェル)",
  HAPPY_SHELL = "Happy Shell (ハッピーシェル)",
  HEEL_SHELL = "Heel Shell (ヒールシェル)",
  WORK_PANTS_BOWSER = "Work Pants (ばっちいパンツ)",
  FIRE_DRESS = "Fire Dress (ファイアドレス)",
  FUZZY_DRESS = "Fuzzy Dress (ふかふかドレス)",
  SAILOR_DRESS = "Sailor Dress (セーラードレス)",
  LOVELY_DRESS = "Lovely Dress (ラブラブドレス)",
  ROYAL_DRESS = "Royal Dress (プリンセスドレス)",
}

export enum AccessoryName {
  NONE = "(NONE)",
  ANTIDOTE_PIN = "Antidote Pin (どくふせぎバッジ)",
  ATTACK_SCARF = "Attack Scarf (ジャンパースカーフ)",
  BOOSTERS_CHARM = "Booster's Charm (ブッキーのおまもり)",
  COIN_TRICK = "Coin Trick (かがやけるひのために)",
  DEFENSE_SCARF = "Defense Scarf (ぼうぎょスカーフ)",
  ECHO_SIGNAL_RING = "Echo Signal Ring",
  ENDURING_BROOCH = "Enduring Brooch",
  EXP_BOOSTER = "Exp. Booster (あなたをこえたくて)",
  FEARLESS_PIN = "Fearless Pin (きょうふふせぎバッジ)",
  FEATHER = "Feather (ドドのはね)",
  FLOWER_RING = "Flower Ring (きみがいてくれたから)",
  GHOST_MEDAL = "Ghost Medal (ゆうれいくんしょう)",
  JINX_BELT = "Jinx Belt (ジャッキーベルト)",
  JUMP_SHOES = "Jump Shoes (かいてんシューズ)",
  NURTURE_RING = "Nurture Ring (ラブラブリング)",
  QUARTZ_CHARM = "Quartz Charm (クリスタルのおまもり)",
  SAFETY_BADGE = "Safety Badge (あんしんバッジ)",
  SAFETY_RING = "Safety Ring (セーフティーリング)",
  SIGNAL_RING = "Signal Ring (おしらせリング)",
  TROOPA_PIN = "Troopa Pin (パタパタくんしょう)",
  TRUEFORM_PIN = "Trueform Pin (へんしんふせぎバッジ)",
  WAKE_UP_PIN = "Wake Up Pin (ぼんやりふせぎバッジ)",
  ZOOM_SHOES = "Zoom Shoes (シュビビンシューズ)",
}

export const Weapons: Weapon[] = [
  {
    name: WeaponName.UNARMED,
    basepower: 0,
    variance: 0,
  },
  {
    name: WeaponName.CHAIN_CHOMP,
    basepower: 10,
    variance: 4,
  },
  {
    name: WeaponName.CYMBALS,
    basepower: 30,
    variance: 3,
  },
  {
    name: WeaponName.DOUBLE_PUNCH,
    basepower: 35,
    variance: 5,
  },
  {
    name: WeaponName.DRILL_CLAW,
    basepower: 40,
    variance: 7,
  },
  {
    name: WeaponName.HURLY_GLOVES,
    basepower: 20,
    variance: 5,
  },
  {
    name: WeaponName.FAKE_CHOMP,
    basepower: 9,
    variance: 3,
  },
  {
    name: WeaponName.FINGER_SHOT,
    basepower: 12,
    variance: 3,
  },
  {
    name: WeaponName.FROGGIE_STICK,
    basepower: 20,
    variance: 2,
  },
  {
    name: WeaponName.FRYING_PAN,
    basepower: 90,
    variance: 20,
  },
  {
    name: WeaponName.HAMMER,
    basepower: 10,
    variance: 1,
  },
  {
    name: WeaponName.HAND_CANNON,
    basepower: 45,
    variance: 6,
  },
  {
    name: WeaponName.HAND_GUN,
    basepower: 24,
    variance: 4,
  },
  {
    name: WeaponName.KOOPA_SHELL,
    basepower: 20,
    variance: 2,
  },
  {
    name: WeaponName.LAZY_SHELL,
    basepower: 90,
    variance: 40,
  },
  {
    name: WeaponName.LUCKY_HAMMER,
    basepower: 0,
    variance: 0,
  },
  {
    name: WeaponName.MASHER,
    basepower: 50,
    variance: 30,
  },
  {
    name: WeaponName.MEGA_GLOVE,
    basepower: 60,
    variance: 6,
  },
  {
    name: WeaponName.PUNCH_GLOVE,
    basepower: 30,
    variance: 3,
  },
  {
    name: WeaponName.SLAP_GLOVE,
    basepower: 40,
    variance: 4,
  },
  {
    name: WeaponName.SPIKED_CHOMP,
    basepower: 30,
    variance: 6,
  },
  {
    name: WeaponName.STAR_GUN,
    basepower: 57,
    variance: 7,
  },
  {
    name: WeaponName.STELLA_023,
    basepower: 62,
    variance: 0,
  },
  {
    name: WeaponName.SUPER_HAMMER,
    basepower: 40,
    variance: 4,
  },
  {
    name: WeaponName.PARASOL,
    basepower: 50,
    variance: 5,
  },
  {
    name: WeaponName.PARATROOPA_SHELL,
    basepower: 50,
    variance: 5,
  },
  {
    name: WeaponName.RIBBIT_STICK,
    basepower: 50,
    variance: 5,
  },
  {
    name: WeaponName.SAGE_STICK,
    basepower: 80,
    variance: 0,
  },
  {
    name: WeaponName.SONIC_CYMBALS,
    basepower: 70,
    variance: 7,
  },
  {
    name: WeaponName.STICKY_GLOVE,
    basepower: 60,
    variance: 6,
  },
  {
    name: WeaponName.SUPER_SLAP,
    basepower: 70,
    variance: 7,
  },
  {
    name: WeaponName.ULTRA_HAMMER,
    basepower: 70,
    variance: 7,
  },
  {
    name: WeaponName.WHOMP_GLOVE,
    basepower: 35,
    variance: 4,
  },
  {
    name: WeaponName.SPIKED_CHOMP,
    basepower: 30,
    variance: 6,
  },
  {
    name: WeaponName.WAR_FAN,
    basepower: 60,
    variance: 5,
  },
  {
    name: WeaponName.WONDER_CHOMP,
    basepower: 67,
    variance: 45,
  },
];

export const Armors: Armor[] = [
  {
    name: ArmorName.NONE,
    defense: 0,
    magicDefense: 0,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FIRE_SHIRT,
    defense: 42,
    magicDefense: 21,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FUZZY_SHIRT,
    defense: 36,
    magicDefense: 18,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.HAPPY_SHIRT,
    defense: 24,
    magicDefense: 12,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.HERO_SHIRT,
    defense: 48,
    magicDefense: 24,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.LAZY_SHELL,
    defense: 127,
    magicDefense: 127,
    attack: -50,
    magicAttack: -50,
    speed: -50,
  },
  {
    name: ArmorName.MEGA_SHIRT,
    defense: 18,
    magicDefense: 9,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.SAILOR_SHIRT,
    defense: 30,
    magicDefense: 15,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.SHIRT,
    defense: 6,
    magicDefense: 3,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.SUPER_SUIT,
    defense: 50,
    magicDefense: 50,
    attack: 50,
    magicAttack: 50,
    speed: 30,
  },
  {
    name: ArmorName.THICK_SHIRT,
    defense: 12,
    magicDefense: 6,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.WORK_PANTS,
    defense: 15,
    magicDefense: 5,
    attack: 10,
    magicAttack: 10,
    speed: 5,
  },
  {
    name: ArmorName.FIRE_PANTS,
    defense: 42,
    magicDefense: 21,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FUZZY_PANTS,
    defense: 36,
    magicDefense: 18,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.HAPPY_PANTS,
    defense: 24,
    magicDefense: 12,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.MEGA_PANTS,
    defense: 18,
    magicDefense: 9,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.PANTS,
    defense: 6,
    magicDefense: 3,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.PRINCE_PANTS,
    defense: 48,
    magicDefense: 24,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.SAILOR_PANTS,
    defense: 30,
    magicDefense: 15,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.THICK_PANTS,
    defense: 12,
    magicDefense: 6,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FIRE_CAPE,
    defense: 30,
    magicDefense: 15,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FUZZY_CAPE,
    defense: 24,
    magicDefense: 12,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.HAPPY_CAPE,
    defense: 12,
    magicDefense: 6,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.MEGA_CAPE,
    defense: 6,
    magicDefense: 3,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.SAILOR_CAPE,
    defense: 18,
    magicDefense: 9,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.STAR_CAPE,
    defense: 36,
    magicDefense: 18,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.COURAGE_SHELL,
    defense: 12,
    magicDefense: 6,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FIRE_SHELL,
    defense: 18,
    magicDefense: 9,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.HAPPY_SHELL,
    defense: 6,
    magicDefense: 3,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.HEEL_SHELL,
    defense: 24,
    magicDefense: 12,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FIRE_DRESS,
    defense: 42,
    magicDefense: 21,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.FUZZY_DRESS,
    defense: 36,
    magicDefense: 18,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.SAILOR_DRESS,
    defense: 30,
    magicDefense: 15,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.LOVELY_DRESS,
    defense: 24,
    magicDefense: 12,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
  {
    name: ArmorName.ROYAL_DRESS,
    defense: 48,
    magicDefense: 24,
    attack: 0,
    magicAttack: 0,
    speed: 0,
  },
];

export const Accessories: Accessory[] = [
  {
    name: AccessoryName.NONE,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.ANTIDOTE_PIN,
    attack: 0,
    magicAttack: 0,
    defense: 2,
    magicDefense: 2,
    speed: 0,
  },
  {
    name: AccessoryName.ATTACK_SCARF,
    attack: 30,
    magicAttack: 30,
    defense: 30,
    magicDefense: 30,
    speed: 30,
  },
  {
    name: AccessoryName.BOOSTERS_CHARM,
    attack: 7,
    magicAttack: 7,
    defense: 7,
    magicDefense: 7,
    speed: -5,
  },
  {
    name: AccessoryName.COIN_TRICK,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.DEFENSE_SCARF,
    attack: 0,
    magicAttack: 0,
    defense: 15,
    magicDefense: 15,
    speed: 0,
  },
  {
    name: AccessoryName.ECHO_SIGNAL_RING,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 10,
  },
  {
    name: AccessoryName.ENDURING_BROOCH,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.FLOWER_RING,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.EXP_BOOSTER,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.FEARLESS_PIN,
    attack: 0,
    magicAttack: 0,
    defense: 5,
    magicDefense: 5,
    speed: 0,
  },
  {
    name: AccessoryName.FEATHER,
    attack: 0,
    magicAttack: 0,
    defense: 5,
    magicDefense: 5,
    speed: 20,
  },
  {
    name: AccessoryName.GHOST_MEDAL,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.JINX_BELT,
    attack: 27,
    magicAttack: 0,
    defense: 27,
    magicDefense: 0,
    speed: 12,
  },
  {
    name: AccessoryName.JUMP_SHOES,
    attack: 0,
    magicAttack: 5,
    defense: 1,
    magicDefense: 1,
    speed: 2,
  },
  {
    name: AccessoryName.NURTURE_RING,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.QUARTZ_CHARM,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 0,
  },
  {
    name: AccessoryName.SAFETY_BADGE,
    attack: 0,
    magicAttack: 0,
    defense: 5,
    magicDefense: 5,
    speed: 0,
  },
  {
    name: AccessoryName.SAFETY_RING,
    attack: 0,
    magicAttack: 0,
    defense: 5,
    magicDefense: 5,
    speed: 5,
  },
  {
    name: AccessoryName.SIGNAL_RING,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 10,
  },
  {
    name: AccessoryName.TROOPA_PIN,
    attack: 0,
    magicAttack: 0,
    defense: 0,
    magicDefense: 0,
    speed: 20,
  },
  {
    name: AccessoryName.TRUEFORM_PIN,
    attack: 0,
    magicAttack: 0,
    defense: 4,
    magicDefense: 4,
    speed: 0,
  },
  {
    name: AccessoryName.WAKE_UP_PIN,
    attack: 0,
    magicAttack: 0,
    defense: 3,
    magicDefense: 3,
    speed: 0,
  },
  {
    name: AccessoryName.ZOOM_SHOES,
    attack: 0,
    magicAttack: 0,
    defense: 5,
    magicDefense: 5,
    speed: 10,
  },
];

export interface Character {
  id: string;
  name: string;
  statbonuses: LevelupBonus[];
  level: number;
  minLevel: number;
  attacks: Attack[];
  weapons: WeaponName[];
  armors: ArmorName[];
  accessories: AccessoryName[];
  activeWeapon: WeaponName;
  activeArmor: ArmorName;
  activeAccessory: AccessoryName;
}
