var attacks = {
  "Belome Attack": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.400",
    video: "./resources/belomeattack.mp4",
    poster: "./resources/belomeattack.png",
    name: "Belome Attack",
    info: "Right when the tongue makes contact",
    note: "",
    frames: 6,
  },
  "Mallow Shocker": {
    type: "attack",
    perfect: "00:00:02.049",
    partialStart: "00:00:01.983",
    partialEnd: "00:00:02.416",
    video: "./resources/mallow-shocker.mp4",
    poster: "./resources/mallow-shocker.png",
    name: "Mallow Shocker",
    info: "Right when lightning strikes",
    note: "",
    frames: 5,
  },
  "Bob-omb/Rob-omb Explosion": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.066",
    video: "./resources/bob-omb-rob-omb-explosion.mp4",
    poster: "./resources/bob-omb-rob-omb-explosion.png",
    name: "Bob-omb/Rob-omb Explosion",
    info: "When the bomb gets close to you",
    note: "",
    frames: 10,
  },
  Bolt: {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.550",
    video: "./resources/bolt.mp4",
    poster: "./resources/bolt.png",
    name: "Bolt",
    info: "When the sound effect plays",
    note: "Might actually be closer to the end of the perfect window, during the lightning strike. Hard to tell with indicator opacity",
    frames: 15,
  },
  "Bowser Clone Claw": {
    type: "block",
    perfect: "00:00:00.883",
    partialStart: "00:00:00.816",
    partialEnd: "00:00:01.250",
    video: "./resources/bowser-clone-claw.mp4",
    poster: "./resources/bowser-clone-claw.png",
    name: "Bowser Clone Claw",
    info: "When the claw strikes you",
    note: "",
    frames: 6,
  },
  "Bowser Clone Spine": {
    type: "block",
    perfect: "00:00:01.149",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.483",
    video: "./resources/bowser-clone-spike.mp4",
    poster: "./resources/bowser-clone-spike.png",
    name: "Bowser Clone Spine",
    info: "When the spike touches you",
    note: "",
    frames: 6,
  },
  "Bowser Unarmed": {
    type: "attack",
    perfect: "00:00:00.616",
    partialStart: "00:00:00.549",
    partialEnd: "00:00:00.983",
    video: "./resources/bowser-unarmed.mp4",
    poster: "./resources/bowser-unarmed.png",
    name: "Bowser Unarmed",
    info: "As Bowser is just landing his swipe",
    note: "",
    frames: 8,
  },
  "Bowyer Arrow": {
    type: "block",
    perfect: "00:00:02.050",
    partialStart: "00:00:01.983",
    partialEnd: "00:00:02.449",
    video: "./resources/bowyer-arrow.mp4",
    poster: "./resources/bowyer-arrow.png",
    name: "Bowyer Arrow",
    info: "Right when the arrow is about to hit",
    note: "",
    frames: 10,
  },
  "Bundt Orb": {
    type: "block",
    perfect: "00:00:01.166",
    partialStart: "00:00:01.100",
    partialEnd: "00:00:01.483",
    video: "./resources/bundt-orb.mp4",
    poster: "./resources/bundt-orb.png",
    name: "Bundt Orb",
    info: "As the orb is about to hit",
    note: "",
    frames: 6,
  },
  "Claymorton Jump": {
    type: "block",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.216",
    video: "./resources/claymorton-jump.mp4",
    poster: "./resources/claymorton-jump.png",
    name: "Claymorton Jump",
    info: "As he approaches your head",
    note: "",
    frames: 6,
  },
  "Booster/Croco/Axem Black/Director bomb toss": {
    type: "block",
    perfect: "00:00:02.533",
    partialStart: "00:00:02.466",
    partialEnd: "00:00:02.833",
    video: "./resources/booster-croco-axem-black-director-bomb-toss.mp4",
    poster: "./resources/booster-croco-axem-black-director-bomb-toss.png",
    name: "Booster/Croco/Axem Black/Director bomb toss",
    info: "As the bomb falls on your head",
    note: "",
    frames: 5,
  },
  "Croco Attack": {
    type: "block",
    perfect: "00:00:01.133",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.449",
    video: "./resources/croco-attack.mp4",
    poster: "./resources/croco-attack.png",
    name: "Croco Attack",
    info: "As he bonks into you",
    note: "",
    frames: 7,
  },
  "Diamond Saw": {
    type: "block",
    perfect: "00:00:02.300",
    partialStart: "00:00:02.233",
    partialEnd: "00:00:02.616",
    video: "./resources/diamond-saw.mp4",
    poster: "./resources/diamond-saw.png",
    name: "Diamond Saw",
    info: "Right as the diamond saws are about to cross",
    note: "",
    frames: 6,
  },
  "Flame Stone": {
    type: "block",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.900",
    partialEnd: "00:00:01.266",
    video: "./resources/flame-stone.mp4",
    poster: "./resources/flame-stone.png",
    name: "Flame Stone",
    info: "When the flame stone engulfs your head",
    note: "",
    frames: 5,
  },
  Flame: {
    type: "block",
    perfect: "00:00:01.533",
    partialStart: "00:00:01.466",
    partialEnd: "00:00:01.833",
    video: "./resources/flame.mp4",
    poster: "./resources/flame.png",
    name: "Flame",
    info: "When the orb descends on you",
    note: "",
    frames: 5,
  },
  "Geno Finger Shot": {
    type: "attack",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.649",
    partialEnd: "00:00:01.116",
    video: "./resources/geno-finger-shot.mp4",
    poster: "./resources/geno-finger-shot.png",
    name: "Geno Finger Shot",
    info: "Right before your final bullet",
    note: "",
    frames: 10,
  },
  "Geno Unarmed": {
    type: "attack",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.333",
    video: "./resources/geno-unarmed.mp4",
    poster: "./resources/geno-unarmed.png",
    name: "Geno Unarmed",
    info: "As the fist launches",
    note: "",
    frames: 10,
  },
  "Grate Guy Attack": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.466",
    video: "./resources/grate-guy-attack.mp4",
    poster: "./resources/grate-guy-attack.png",
    name: "Grate Guy Attack",
    info: "During his max stretch",
    note: "",
    frames: 10,
  },
  "Hammer Bros. Attack": {
    type: "block",
    perfect: "00:00:01.066",
    partialStart: "00:00:01.000",
    partialEnd: "00:00:01.383",
    video: "./resources/hammer-bros-attack.mp4",
    poster: "./resources/hammer-bros-attack.png",
    name: "Hammer Bros. Attack",
    info: "During the downward strike",
    note: "",
    frames: 5,
  },
  "Hammer Bros. Hammer Time": {
    type: "block",
    perfect: "00:00:01.466",
    partialStart: "00:00:01.400",
    partialEnd: "00:00:01.633",
    video: "./resources/hammer-bros-hammer-time.mp4",
    poster: "./resources/hammer-bros-hammer-time.png",
    name: "Hammer Bros. Hammer Time",
    info: "During the first hammer's bonk",
    note: "",
    frames: 10,
  },
  "Hot Shot": {
    type: "block",
    perfect: "00:00:01.850",
    partialStart: "00:00:01.783",
    partialEnd: "00:00:02.166",
    video: "./resources/hot-shot.mp4",
    poster: "./resources/hot-shot.png",
    name: "Hot Shot",
    info: "Right as the fire hits you",
    note: "",
    frames: 5,
  },
  "Mallow HP Rain": {
    type: "attack",
    perfect: "00:00:04.516",
    partialStart: "00:00:04.450",
    partialEnd: "00:00:05.083",
    video: "./resources/mallow-hp-rain.mp4",
    poster: "./resources/mallow-hp-rain.png",
    name: "Mallow HP Rain",
    info: "During the extended hover period",
    note: "about 20 frames long",
    frames: 20,
  },
  "Mario Jump": {
    type: "attack",
    perfect: "00:00:01.183",
    partialStart: "00:00:01.183",
    partialEnd: "00:00:01.483",
    video: "./resources/mario-jump.mp4",
    poster: "./resources/mario-jump.png",
    name: "Mario Jump",
    info: "When Mario appears on screen",
    note: "Might even be earlier. The indicator comes on screen with him.",
    frames: 8,
  },
  "Knife Guy Attack": {
    type: "block",
    perfect: "00:00:01.650",
    partialStart: "00:00:01.583",
    partialEnd: "00:00:01.966",
    video: "./resources/knife-guy-attack.mp4",
    poster: "./resources/knife-guy-attack.png",
    name: "Knife Guy Attack",
    info: "As the slash impact hits",
    note: "",
    frames: 7,
  },
  "Knife Guy Knife": {
    type: "block",
    perfect: "00:00:01.616",
    partialStart: "00:00:01.550",
    partialEnd: "00:00:01.933",
    video: "./resources/knife-guy-knife.mp4",
    poster: "./resources/knife-guy-knife.png",
    name: "Knife Guy Knife",
    info: "Right as the knife impacts",
    note: "",
    frames: 5,
  },
  "Lightning Orb": {
    type: "block",
    perfect: "00:00:01.033",
    partialStart: "00:00:00.966",
    partialEnd: "00:00:01.533",
    video: "./resources/lightning-orb.mp4",
    poster: "./resources/lightning-orb.png",
    name: "Lightning Orb",
    info: "While the orb is on its way to you",
    note: "",
    frames: 17,
  },
  "Mallow Cymbals": {
    type: "attack",
    perfect: "00:00:00.533",
    partialStart: "00:00:00.466",
    partialEnd: "00:00:00.849",
    video: "./resources/mallow-cymbals.mp4",
    poster: "./resources/mallow-cymbals.png",
    name: "Mallow Cymbals",
    info: "Right as the cymbals clap together",
    note: "",
    frames: 5,
  },
  "Mallow Unarmed": {
    type: "attack",
    perfect: "00:00:00.316",
    partialStart: "00:00:00.250",
    partialEnd: "00:00:00.883",
    video: "./resources/mallow-unarmed.mp4",
    poster: "./resources/mallow-unarmed.png",
    name: "Mallow Unarmed",
    info: "As Mallow extends his fist",
    note: "",
    frames: 20,
  },
  "Mario Hammer": {
    type: "attack",
    perfect: "00:00:00.533",
    partialStart: "00:00:00.466",
    partialEnd: "00:00:01.083",
    video: "./resources/mario-hammer.mp4",
    poster: "./resources/mario-hammer.png",
    name: "Mario Hammer",
    info: "During the swing",
    note: "",
    frames: 19,
  },
  "Mario Punch Glove": {
    type: "attack",
    perfect: "00:00:00.483",
    partialStart: "00:00:00.416",
    partialEnd: "00:00:00.816",
    video: "./resources/mario-punch-glove.mp4",
    poster: "./resources/mario-punch-glove.png",
    name: "Mario Punch Glove",
    info: "During the forward swing",
    note: "",
    frames: 6,
  },
  "Mario Unarmed": {
    type: "attack",
    perfect: "00:00:00.483",
    partialStart: "00:00:00.416",
    partialEnd: "00:00:00.783",
    video: "./resources/mario-unarmed.mp4",
    poster: "./resources/mario-unarmed.png",
    name: "Mario Unarmed",
    info: "During the forward swing",
    note: "",
    frames: 4,
  },
  "Mezzo Bomb Explosion": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.066",
    video: "./resources/mezzo-bomb-explosion.mp4",
    poster: "./resources/mezzo-bomb-explosion.png",
    name: "Mezzo Bomb Explosion",
    info: "When the bomb gets close to you",
    note: "",
    frames: 10,
  },
  "Micro Bomb Explosion": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.066",
    video: "./resources/micro-bomb-explosion.mp4",
    poster: "./resources/micro-bomb-explosion.png",
    name: "Micro Bomb Explosion",
    info: "When the bomb gets close to you",
    note: "",
    frames: 10,
  },
  "Croco/Lakitu Monster Toss": {
    type: "block",
    perfect: "00:00:01.966",
    partialStart: "00:00:01.900",
    partialEnd: "00:00:02.283",
    video: "./resources/croco-lakitu-monster-toss.mp4",
    poster: "./resources/croco-lakitu-monster-toss.png",
    name: "Croco/Lakitu Monster Toss",
    info: "Right as the projectile bonks you",
    note: "",
    frames: 5,
  },
  "Punchinello Attack": {
    type: "block",
    perfect: "00:00:00.849",
    partialStart: "00:00:00.783",
    partialEnd: "00:00:01.166",
    video: "./resources/punchinello-claw.mp4",
    poster: "./resources/punchinello-claw.png",
    name: "Punchinello Attack",
    info: "As he makes contact",
    note: "",
    frames: 6,
  },
  "Raspberry Attack": {
    type: "block",
    perfect: "00:00:00.266",
    partialStart: "00:00:00.200",
    partialEnd: "00:00:00.633",
    video: "./resources/raspberry-attack.mp4",
    poster: "./resources/raspberry-attack.png",
    name: "Raspberry Attack",
    info: "While the mouth is closing",
    note: "",
    frames: 8,
  },
  "Bodyguard/Shymore/Springer Jump": {
    type: "block",
    perfect: "00:00:00.816",
    partialStart: "00:00:00.750",
    partialEnd: "00:00:01.133",
    video: "./resources/bodyguard-shymore-springer-jump.mp4",
    poster: "./resources/bodyguard-shymore-springer-jump.png",
    name: "Bodyguard/Shymore/Springer Jump",
    info: "When he approaches your head",
    note: "",
    frames: 6,
  },
  "Raspberry Orb": {
    type: "block",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:00.966",
    video: "./resources/raspberry-orb.mp4",
    poster: "./resources/raspberry-orb.png",
    name: "Raspberry Orb",
    info: "As the orb is about to hit",
    note: "",
    frames: 6,
  },
  "Stop it!": {
    type: "block",
    perfect: "00:00:02.750",
    partialStart: "00:00:02.683",
    partialEnd: "00:00:03.150",
    video: "./resources/stop-it-.mp4",
    poster: "./resources/stop-it-.png",
    name: "Stop it!",
    info: "As the final hit comes down",
    note: "",
    frames: 10,
  },
  "Stop! Stop!": {
    type: "block",
    perfect: "00:00:01.683",
    partialStart: "00:00:01.616",
    partialEnd: "00:00:02.083",
    video: "./resources/stop-stop-.mp4",
    poster: "./resources/stop-stop-.png",
    name: "Stop! Stop!",
    info: "As the final hit comes down",
    note: "",
    frames: 10,
  },
  "Tentacle (Left) Slap": {
    type: "block",
    perfect: "00:00:00.766",
    partialStart: "00:00:00.700",
    partialEnd: "00:00:01.150",
    video: "./resources/tentacle-left-slap.mp4",
    poster: "./resources/tentacle-left-slap.png",
    name: "Tentacle (Left) Slap",
    info: "As the tentacle descends on you",
    note: "",
    frames: 12,
  },
  "Tentacle (Right) Slap": {
    type: "block",
    perfect: "00:00:00.566",
    partialStart: "00:00:00.500",
    partialEnd: "00:00:00.966",
    video: "./resources/tentacle-right-slap.mp4",
    poster: "./resources/tentacle-right-slap.png",
    name: "Tentacle (Right) Slap",
    info: "As the tentacle descends on you",
    note: "",
    frames: 11,
  },
  "Jagger/Terrapin Attack": {
    type: "block",
    perfect: "00:00:01.066",
    partialStart: "00:00:01.000",
    partialEnd: "00:00:01.449",
    video: "./resources/jagger-terrapin-attack.mp4",
    poster: "./resources/jagger-terrapin-attack.png",
    name: "Jagger/Terrapin Attack",
    info: "As the punch connects with you",
    note: "",
    frames: 8,
  },
  "Mallow Thunderbolt": {
    type: "attack",
    perfect: "00:00:02.533",
    partialStart: "00:00:02.466",
    partialEnd: "00:00:02.933",
    video: "./resources/mallow-thunderbolt.mp4",
    poster: "./resources/mallow-thunderbolt.png",
    name: "Mallow Thunderbolt",
    info: "When 3 bolts in a row start to clear",
    note: "",
    frames: 10,
  },
  "Will-o-Wisp": {
    type: "block",
    perfect: "00:00:02.283",
    partialStart: "00:00:02.216",
    partialEnd: "00:00:02.766",
    video: "./resources/will-o-wisp.mp4",
    poster: "./resources/will-o-wisp.png",
    name: "Will-o-Wisp",
    info: "As soon as the orb rises out of the ground",
    note: "",
    frames: 15,
  },
  "Speardovich Attack": {
    type: "block",
    perfect: "00:00:01.566",
    partialStart: "00:00:01.500",
    partialEnd: "00:00:01.966",
    video: "./resources/speardovich-attack.mp4",
    poster: "./resources/speardovich-attack.png",
    name: "Speardovich Attack",
    info: "During the spear lunge",
    note: "",
    frames: 10,
  },
  "Spikester/Spikey/Urspike Attack 1": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:00.983",
    video: "./resources/spikester-spikey-urspike-attack-1.mp4",
    poster: "./resources/spikester-spikey-urspike-attack-1.png",
    name: "Spikester/Spikey/Urspike Attack 1",
    info: "When he begins to fall",
    note: "",
    frames: 5,
  },
};
