var attacks = {
  "Alley Rat/Rat Funk Attack": {
    type: "block",
    perfect: "00:00:01.116",
    partialStart: "00:00:01.050",
    partialEnd: "00:00:01.433",
    video: "./resources/alley-rat-rat-funk-attack.mp4",
    poster: "./resources/alley-rat-rat-funk-attack.png",
    name: "Alley Rat/Rat Funk Attack",
    info: "As it raises its tail after turning around",
    note: "",
    frames: 5,
  },
  "Alley Rat/Rat Funk Poison": {
    type: "block",
    perfect: "00:00:01.133",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.500",
    video: "./resources/alley-rat-rat-funk-poison.mp4",
    poster: "./resources/alley-rat-rat-funk-poison.png",
    name: "Alley Rat/Rat Funk Poison",
    info: "As its head moves forward after rearing back",
    note: "",
    frames: 8,
  },
  "Amanita Attack": {
    type: "block",
    perfect: "00:00:00.866",
    partialStart: "00:00:00.800",
    partialEnd: "00:00:01.266",
    video: "./resources/amanita-attack.mp4",
    poster: "./resources/amanita-attack.png",
    name: "Amanita Attack",
    info: "As soon as it grows back to full size",
    note: "",
    frames: 10,
  },
  "Ameboid Attack": {
    type: "block",
    perfect: "00:00:02.250",
    partialStart: "00:00:02.183",
    partialEnd: "00:00:02.566",
    video: "./resources/ameboid-attack.mp4",
    poster: "./resources/ameboid-attack.png",
    name: "Ameboid Attack",
    info: "Right in the middle of the way between being fully stretched backwards and touching you",
    note: "",
    frames: 5,
  },
  "Apprentice/Big Blaster/Blaster/Snifit/Snifster bullet": {
    type: "block",
    perfect: "00:00:00.683",
    partialStart: "00:00:00.616",
    partialEnd: "00:00:00.999",
    video:
      "./resources/apprentice-big-blaster-blaster-snifit-snifster-bullet.mp4",
    poster:
      "./resources/apprentice-big-blaster-blaster-snifit-snifster-bullet.png",
    name: "Apprentice/Big Blaster/Blaster/Snifit/Snifster bullet",
    info: "Slightly before the bullet makes contact",
    note: "",
    frames: 5,
  },
  "Apprentice/Snifit/Snifster Attack": {
    type: "block",
    perfect: "00:00:00.783",
    partialStart: "00:00:00.716",
    partialEnd: "00:00:01.150",
    video: "./resources/apprentice-snifit-snifster-attack.mp4",
    poster: "./resources/apprentice-snifit-snifster-attack.png",
    name: "Apprentice/Snifit/Snifster Attack",
    info: "As the mouth makes contact",
    note: "",
    frames: 10,
  },
  "Arachne/Spinthra Attack": {
    type: "block",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.249",
    video: "./resources/arachne-spinthra-attack.mp4",
    poster: "./resources/arachne-spinthra-attack.png",
    name: "Arachne/Spinthra Attack",
    info: "As its head rises upward after coming forward",
    note: "",
    frames: 7,
  },
  "Armored Ant/Shogun Attack": {
    type: "block",
    perfect: "00:00:00.733",
    partialStart: "00:00:00.666",
    partialEnd: "00:00:01.050",
    video: "./resources/armored-ant-shogun-attack.mp4",
    poster: "./resources/armored-ant-shogun-attack.png",
    name: "Armored Ant/Shogun Attack",
    info: "During the downward swing",
    note: "",
    frames: 5,
  },
  "Armored Ant/Shogun Carni-Kiss": {
    type: "block",
    perfect: "00:00:01.266",
    partialStart: "00:00:01.200",
    partialEnd: "00:00:01.566",
    video: "./resources/shogun-carni-kiss.mp4",
    poster: "./resources/shogun-carni-kiss.png",
    name: "Shogun Carni-Kiss",
    info: "When the animated teeth fully close",
    note: "",
    frames: 5,
  },
  "Artichoker Ball": {
    type: "block",
    perfect: "00:00:02.150",
    partialStart: "00:00:02.083",
    partialEnd: "00:00:02.516",
    video: "./resources/artichoker-ball.mp4",
    poster: "./resources/artichoker-ball.png",
    name: "Artichoker Ball",
    info: "As the goop lands",
    note: "",
    frames: 9,
  },
  "Artichoker/Kriffid Attack": {
    type: "block",
    perfect: "00:00:01.050",
    partialStart: "00:00:00.983",
    partialEnd: "00:00:01.449",
    video: "./resources/artichoker-kriffid-attack.mp4",
    poster: "./resources/artichoker-kriffid-attack.png",
    name: "Artichoker/Kriffid Attack",
    info: "As it charges forward and its head appears",
    note: "",
    frames: 9,
  },
  "Axem Black Attack": {
    type: "block",
    perfect: "00:00:01.000",
    partialStart: "00:00:00.933",
    partialEnd: "00:00:01.316",
    video: "./resources/axem-black-attack.mp4",
    poster: "./resources/axem-black-attack.png",
    name: "Axem Black Attack",
    info: "Before the second swing",
    note: "",
    frames: 5,
  },
  "Axem Green Attack": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.466",
    video: "./resources/axem-green-attack.mp4",
    poster: "./resources/axem-green-attack.png",
    name: "Axem Green Attack",
    info: "During the second thrust",
    note: "",
    frames: 6,
  },
  "Axem Pink Attack": {
    type: "block",
    perfect: "00:00:00.683",
    partialStart: "00:00:00.616",
    partialEnd: "00:00:01.016",
    video: "./resources/axem-pink-counter.mp4",
    poster: "./resources/axem-pink-counter.png",
    name: "Axem Pink Attack",
    info: "Just before the swing",
    note: "",
    frames: 6,
  },
  "Axem Red Attack": {
    type: "block",
    perfect: "00:00:00.816",
    partialStart: "00:00:00.750",
    partialEnd: "00:00:01.149",
    video: "./resources/axem-red-attack.mp4",
    poster: "./resources/axem-red-attack.png",
    name: "Axem Red Attack",
    info: "During the downward swing",
    note: "",
    frames: 6,
  },
  "Axem Red Orb": {
    type: "block",
    perfect: "00:00:01.066",
    partialStart: "00:00:01.000",
    partialEnd: "00:00:01.366",
    video: "./resources/axem-red-orb.mp4",
    poster: "./resources/axem-red-orb.png",
    name: "Axem Red Orb",
    info: "Before the orb hits",
    note: "",
    frames: 5,
  },
  "Axem Yellow Attack": {
    type: "block",
    perfect: "00:00:02.850",
    partialStart: "00:00:02.783",
    partialEnd: "00:00:03.133",
    video: "./resources/axem-yellow-attack.mp4",
    poster: "./resources/axem-yellow-attack.png",
    name: "Axem Yellow Attack",
    info: "Right before the axe makes contact",
    note: "",
    frames: 5,
  },
  "Axem Yellow Blob": {
    type: "block",
    perfect: "00:00:03.016",
    partialStart: "00:00:02.949",
    partialEnd: "00:00:03.400",
    video: "./resources/axem-yellow-blob.mp4",
    poster: "./resources/axem-yellow-blob.png",
    name: "Axem Yellow Blob",
    info: "As the goop hits the target character",
    note: "",
    frames: 8,
  },
  "Axem Yellow Body Slam": {
    type: "block",
    perfect: "00:00:00.833",
    partialStart: "00:00:00.766",
    partialEnd: "00:00:01.233",
    video: "./resources/axem-yellow-body-slam.mp4",
    poster: "./resources/axem-yellow-body-slam.png",
    name: "Axem Yellow Body Slam",
    info: "Before the ranger makes contact",
    note: "",
    frames: 10,
  },
  "Bad Adder Attack": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.400",
    video: "./resources/bad-adder-attack.mp4",
    poster: "./resources/bad-adder-attack.png",
    name: "Bad Adder Attack",
    info: "As it is fully extended before closing its mouth",
    note: "",
    frames: 5,
  },
  "Bad Adder Carni-kiss": {
    type: "block",
    perfect: "00:00:01.216",
    partialStart: "00:00:01.149",
    partialEnd: "00:00:01.533",
    video: "./resources/bad-adder-carni-kiss.mp4",
    poster: "./resources/bad-adder-carni-kiss.png",
    name: "Bad Adder Carni-kiss",
    info: "Right when the theeth effect starts",
    note: "",
    frames: 5,
  },
  "Bad Adder Poison": {
    type: "block",
    perfect: "00:00:01.183",
    partialStart: "00:00:01.116",
    partialEnd: "00:00:01.550",
    video: "./resources/bad-adder-poison.mp4",
    poster: "./resources/bad-adder-poison.png",
    name: "Bad Adder Poison",
    info: "When it's vertical",
    note: "",
    frames: 8,
  },
  "Bahamutt Bite": {
    type: "block",
    perfect: "00:00:01.200",
    partialStart: "00:00:01.133",
    partialEnd: "00:00:01.566",
    video: "./resources/bahamutt-bite.mp4",
    poster: "./resources/bahamutt-bite.png",
    name: "Bahamutt Bite",
    info: "As it lunges forward",
    note: "",
    frames: 8,
  },
  "Bahamutt Rock": {
    type: "block",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.216",
    video: "./resources/bahamutt-rock.mp4",
    poster: "./resources/bahamutt-rock.png",
    name: "Bahamutt Rock",
    info: "Just before the rocks make contact",
    note: "",
    frames: 5,
  },
  "Bandana Blue Pierce": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.466",
    video: "./resources/bandana-blue-pierce.mp4",
    poster: "./resources/bandana-blue-pierce.png",
    name: "Bandana Blue Pierce",
    info: "As the spear makes contact",
    note: "",
    frames: 5,
  },
  "Bandana Blue/Bandana Red Attack": {
    type: "block",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.216",
    video: "./resources/bandana-blue-bandana-red-attack.mp4",
    poster: "./resources/bandana-blue-bandana-red-attack.png",
    name: "Bandana Blue/Bandana Red Attack",
    info: "As the spear makes contact",
    note: "",
    frames: 5,
  },
  "Bandana Red Skewer": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.466",
    video: "./resources/bandana-red-skewer.mp4",
    poster: "./resources/bandana-red-skewer.png",
    name: "Bandana Red Skewer",
    info: "As the spear makes contact",
    note: "",
    frames: 5,
  },
  "Beezo Attack": {
    type: "block",
    perfect: "00:00:01.400",
    partialStart: "00:00:01.333",
    partialEnd: "00:00:01.716",
    video: "./resources/beezo-attack.mp4",
    poster: "./resources/beezo-attack.png",
    name: "Beezo Attack",
    info: "As it lunges forward",
    note: "",
    frames: 5,
  },
  "Belome Attack": {
    type: "block",
    perfect: "00:00:01.133",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.450",
    video: "./resources/belome-attack.mp4",
    poster: "./resources/belome-attack.png",
    name: "Belome Attack",
    info: "As the tongue makes contact",
    note: "",
    frames: 5,
  },
  "Big Blaster Blazer": {
    type: "block",
    perfect: "00:00:00.683",
    partialStart: "00:00:00.616",
    partialEnd: "00:00:00.983",
    video: "./resources/big-blaster-blazer.mp4",
    poster: "./resources/big-blaster-blazer.png",
    name: "Big Blaster Blazer",
    info: "Slightly before the bullet makes contact",
    note: "",
    frames: 5,
  },
  "Big Troopa/Grand Troopa Attack": {
    type: "block",
    perfect: "00:00:02.716",
    partialStart: "00:00:02.650",
    partialEnd: "00:00:03.033",
    video: "./resources/big-troopa-grand-troopa-attack.mp4",
    poster: "./resources/big-troopa-grand-troopa-attack.png",
    name: "Big Troopa/Grand Troopa Attack",
    info: "Just before it slams into the ground",
    note: "",
    frames: 5,
  },
  "Birdo Attack": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.466",
    video: "./resources/birdo-attack.mp4",
    poster: "./resources/birdo-attack.png",
    name: "Birdo Attack",
    info: "When the 3rd egg is halfway between you and Birdo",
    note: "",
    frames: 6,
  },
  "Birdo Single Egg Shot": {
    type: "block",
    perfect: "00:00:00.683",
    partialStart: "00:00:00.616",
    partialEnd: "00:00:00.983",
    video: "./resources/birdo-single-egg-shot.mp4",
    poster: "./resources/birdo-single-egg-shot.png",
    name: "Birdo Single Egg Shot",
    info: "When the egg is about to hit you",
    note: "",
    frames: 5,
  },
  "Birdy/Bluebird Attack": {
    type: "block",
    perfect: "00:00:00.766",
    partialStart: "00:00:00.699",
    partialEnd: "00:00:01.083",
    video: "./resources/birdy-bluebird-attack.mp4",
    poster: "./resources/birdy-bluebird-attack.png",
    name: "Birdy/Bluebird Attack",
    info: "Just before the spear hits",
    note: "",
    frames: 5,
  },
  "Birdy/Bluebird Grinder": {
    type: "block",
    perfect: "00:00:00.699",
    partialStart: "00:00:00.633",
    partialEnd: "00:00:01.016",
    video: "./resources/birdy-bluebird-grinder.mp4",
    poster: "./resources/birdy-bluebird-grinder.png",
    name: "Birdy/Bluebird Grinder",
    info: "During the downward swing, before contact",
    note: "",
    frames: 5,
  },
  Blast: {
    type: "block",
    perfect: "00:00:01.550",
    partialStart: "00:00:01.483",
    partialEnd: "00:00:01.866",
    video: "./resources/blast.mp4",
    poster: "./resources/blast.png",
    name: "Blast",
    info: "The sign will fully cover a blast after a big blast on the left side",
    note: "",
    frames: 5,
  },
  "Blooper Attack": {
    type: "block",
    perfect: "00:00:01.716",
    partialStart: "00:00:01.650",
    partialEnd: "00:00:02.033",
    video: "./resources/blooper-attack.mp4",
    poster: "./resources/blooper-attack.png",
    name: "Blooper Attack",
    info: "When the tentacles make contact",
    note: "",
    frames: 5,
  },
  "Bob-omb/Rob-omb Explosion": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.066",
    video: "./resources/bob-omb-rob-omb-explosion.mp4",
    poster: "./resources/bob-omb-rob-omb-explosion.png",
    name: "Bob-omb/Rob-omb Explosion",
    info: "When the bomb gets close to you",
    note: "",
    frames: 10,
  },
  "Bodyguard/Shymore/Springer Jump": {
    type: "block",
    perfect: "00:00:00.816",
    partialStart: "00:00:00.750",
    partialEnd: "00:00:01.133",
    video: "./resources/bodyguard-shymore-springer-jump.mp4",
    poster: "./resources/bodyguard-shymore-springer-jump.png",
    name: "Bodyguard/Shymore/Springer Jump",
    info: "When he approaches your head",
    note: "",
    frames: 6,
  },
  Bolt: {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.550",
    video: "./resources/bolt.mp4",
    poster: "./resources/bolt.png",
    name: "Bolt",
    info: "When the sound effect plays",
    note: "",
    frames: 15,
  },
  "Boo/High Boo Attack": {
    type: "block",
    perfect: "00:00:01.650",
    partialStart: "00:00:01.583",
    partialEnd: "00:00:01.966",
    video: "./resources/boo-high-boo-attack.mp4",
    poster: "./resources/boo-high-boo-attack.png",
    name: "Boo/High Boo Attack",
    info: "When it has opened its mouth fully",
    note: "",
    frames: 6,
  },
  "Boomer Attack": {
    type: "block",
    perfect: "00:00:01.133",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.483",
    video: "./resources/boomer-attack.mp4",
    poster: "./resources/boomer-attack.png",
    name: "Boomer Attack",
    info: "After he's assumed slashing stance, before the sword comes out",
    note: "",
    frames: 6,
  },
  "Boomer Shaker": {
    type: "block",
    perfect: "00:00:01.016",
    partialStart: "00:00:00.949",
    partialEnd: "00:00:01.433",
    video: "./resources/boomer-shaker.mp4",
    poster: "./resources/boomer-shaker.png",
    name: "Boomer Shaker",
    info: "When the sword is fully behind him",
    note: "",
    frames: 11,
  },
  "Boomer Skewer": {
    type: "block",
    perfect: "00:00:01.766",
    partialStart: "00:00:01.699",
    partialEnd: "00:00:02.100",
    video: "./resources/boomer-skewer.mp4",
    poster: "./resources/boomer-skewer.png",
    name: "Boomer Skewer",
    info: "When the sword point is completely in the target character",
    note: "",
    frames: 5,
  },
  "Booster Attack": {
    type: "block",
    perfect: "00:00:01.683",
    partialStart: "00:00:01.616",
    partialEnd: "00:00:01.999",
    video: "./resources/booster-attack.mp4",
    poster: "./resources/booster-attack.png",
    name: "Booster Attack",
    info: "As Booster's fist reaches you after 2 wind ups",
    note: "",
    frames: 5,
  },
  "Booster Loco Express": {
    type: "block",
    perfect: "00:00:01.666",
    partialStart: "00:00:01.600",
    partialEnd: "00:00:02.000",
    video: "./resources/booster-loco-express.mp4",
    poster: "./resources/booster-loco-express.png",
    name: "Booster Loco Express",
    info: "Right when the express is about to hit you",
    note: "",
    frames: 5,
  },
  "Booster/Croco/Axem Black/Director bomb toss": {
    type: "block",
    perfect: "00:00:02.533",
    partialStart: "00:00:02.466",
    partialEnd: "00:00:02.833",
    video: "./resources/booster-croco-axem-black-director-bomb-toss.mp4",
    poster: "./resources/booster-croco-axem-black-director-bomb-toss.png",
    name: "Booster/Croco/Axem Black/Director bomb toss",
    info: "As the bomb falls on your head",
    note: "",
    frames: 5,
  },
  "Bowser Chain Chomp": {
    type: "attack",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.900",
    partialEnd: "00:00:01.316",
    video: "./resources/bowser-chain-chomp.mp4",
    poster: "./resources/bowser-chain-chomp.png",
    name: "Bowser Chain Chomp",
    info: "On the 3rd spin, before it's released",
    note: "",
    frames: 7,
  },
  "Bowser Clone Claw": {
    type: "block",
    perfect: "00:00:00.883",
    partialStart: "00:00:00.816",
    partialEnd: "00:00:01.250",
    video: "./resources/bowser-clone-claw.mp4",
    poster: "./resources/bowser-clone-claw.png",
    name: "Bowser Clone Claw",
    info: "When the claw strikes you",
    note: "",
    frames: 6,
  },
  "Bowser Clone Spine": {
    type: "block",
    perfect: "00:00:01.149",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.483",
    video: "./resources/bowser-clone-spine.mp4",
    poster: "./resources/bowser-clone-spine.png",
    name: "Bowser Clone Spine",
    info: "When the spike touches you",
    note: "",
    frames: 6,
  },
  "Bowser Crusher": {
    type: "attack",
    perfect: "00:00:02.249",
    partialStart: "00:00:01.999",
    partialEnd: "00:00:02.466",
    video: "./resources/bowser-crusher.mp4",
    poster: "./resources/bowser-crusher.png",
    name: "Bowser Crusher",
    info: "Right when it stops shaking",
    note: "",
    frames: 10,
  },
  "Bowser Drill Claw": {
    type: "attack",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.033",
    video: "./resources/bowser-drill-claw.mp4",
    poster: "./resources/bowser-drill-claw.png",
    name: "Bowser Drill Claw",
    info: "During the forward swing",
    note: "",
    frames: 8,
  },
  "Bowser Fake Chomp": {
    type: "attack",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.900",
    partialEnd: "00:00:01.316",
    video: "./resources/bowser-fake-chomp.mp4",
    poster: "./resources/bowser-fake-chomp.png",
    name: "Bowser Fake Chomp",
    info: "On the 3rd spin, before it's released",
    note: "",
    frames: 7,
  },
  "Bowser Hurly Gloves": {
    type: "attack",
    perfect: "00:00:00.600",
    partialStart: "00:00:00.533",
    partialEnd: "00:00:00.916",
    video: "./resources/bowser-hurly-gloves.mp4",
    poster: "./resources/bowser-hurly-gloves.png",
    name: "Bowser Hurly Gloves",
    info: "3 frames before Mario is the farthest back",
    note: "",
    frames: 7,
  },
  "Bowser Hurly Gloves (Mario incapacitated)": {
    type: "attack",
    perfect: "00:00:00.883",
    partialStart: "00:00:00.816",
    partialEnd: "00:00:01.200",
    video: "./resources/bowser-hurly-gloves-mario-incapacitated-.mp4",
    poster: "./resources/bowser-hurly-gloves-mario-incapacitated-.png",
    name: "Bowser Hurly Gloves (Mario incapacitated)",
    info: "When Bowser has the doll high up/starts lifting his right foot",
    note: "",
    frames: 6,
  },
  "Bowser Spiked Chomp": {
    type: "attack",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.499",
    video: "./resources/bowser-spiked-chomp.mp4",
    poster: "./resources/bowser-spiked-chomp.png",
    name: "Bowser Spiked Chomp",
    info: "When the Chomp is looking left during the third spin",
    note: "",
    frames: 7,
  },
  "Bowser Unarmed": {
    type: "attack",
    perfect: "00:00:00.616",
    partialStart: "00:00:00.549",
    partialEnd: "00:00:00.983",
    video: "./resources/bowser-unarmed.mp4",
    poster: "./resources/bowser-unarmed.png",
    name: "Bowser Unarmed",
    info: "As Bowser is just landing his swipe",
    note: "",
    frames: 8,
  },
  "Bowser Wonder Chomp": {
    type: "attack",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.500",
    video: "./resources/bowser-wonder-chomp.mp4",
    poster: "./resources/bowser-wonder-chomp.png",
    name: "Bowser Wonder Chomp",
    info: "Right before throwing",
    note: "",
    frames: 7,
  },
  "Bowyer Arrow": {
    type: "block",
    perfect: "00:00:02.050",
    partialStart: "00:00:01.983",
    partialEnd: "00:00:02.449",
    video: "./resources/bowyer-arrow.mp4",
    poster: "./resources/bowyer-arrow.png",
    name: "Bowyer Arrow",
    info: "Right when the arrow is about to hit",
    note: "",
    frames: 10,
  },
  "Bundt Attack": {
    type: "block",
    perfect: "00:00:00.600",
    partialStart: "00:00:00.533",
    partialEnd: "00:00:00.966",
    video: "./resources/bundt-attack.mp4",
    poster: "./resources/bundt-attack.png",
    name: "Bundt Attack",
    info: "As the top layer moves forward after rearing back",
    note: "",
    frames: 9,
  },
  "Bundt Orb": {
    type: "block",
    perfect: "00:00:01.166",
    partialStart: "00:00:01.100",
    partialEnd: "00:00:01.483",
    video: "./resources/bundt-orb.mp4",
    poster: "./resources/bundt-orb.png",
    name: "Bundt Orb",
    info: "As the orb is about to hit",
    note: "",
    frames: 6,
  },
  "Buzzer/Stinger Attack": {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.250",
    partialEnd: "00:00:01.716",
    video: "./resources/buzzer-stinger-attack.mp4",
    poster: "./resources/buzzer-stinger-attack.png",
    name: "Buzzer/Stinger Attack",
    info: "As the stinger makes contact",
    note: "",
    frames: 10,
  },
  "Carroboscis Attack": {
    type: "block",
    perfect: "00:00:02.216",
    partialStart: "00:00:02.133",
    partialEnd: "00:00:02.600",
    video: "./resources/carroboscis-attack.mp4",
    poster: "./resources/carroboscis-attack.png",
    name: "Carroboscis Attack",
    info: "After the eyes have flashed briefly",
    note: "",
    frames: 10,
  },
  "Chain Chomp/Chomp Chomp Attack": {
    type: "block",
    perfect: "00:00:00.983",
    partialStart: "00:00:00.916",
    partialEnd: "00:00:01.366",
    video: "./resources/chain-chomp-chomp-chomp-attack.mp4",
    poster: "./resources/chain-chomp-chomp-chomp-attack.png",
    name: "Chain Chomp/Chomp Chomp Attack",
    info: "After it lunges and bites",
    note: "",
    frames: 11,
  },
  "Chained Kong/Guerilla Rock": {
    type: "block",
    perfect: "00:00:01.966",
    partialStart: "00:00:01.899",
    partialEnd: "00:00:02.283",
    video: "./resources/chained-kong-guerilla-rock.mp4",
    poster: "./resources/chained-kong-guerilla-rock.png",
    name: "Chained Kong/Guerilla Rock",
    info: "Just before rock hits",
    note: "",
    frames: 5,
  },
  "Chained Kong/Guerilla Slam": {
    type: "block",
    perfect: "00:00:01.366",
    partialStart: "00:00:01.300",
    partialEnd: "00:00:01.733",
    video: "./resources/chained-kong-guerilla-slam.mp4",
    poster: "./resources/chained-kong-guerilla-slam.png",
    name: "Chained Kong/Guerilla Slam",
    info: "Just before fist hits",
    note: "",
    frames: 10,
  },
  "Cheep Cheep/Mr. Kipper Attack": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.000",
    partialEnd: "00:00:01.416",
    video: "./resources/cheep-cheep-mr-kipper-attack.mp4",
    poster: "./resources/cheep-cheep-mr-kipper-attack.png",
    name: "Cheep Cheep/Mr. Kipper Attack",
    info: "As it reaches its target",
    note: "",
    frames: 6,
  },
  "Chewy/Piranha Plant Attack": {
    type: "block",
    perfect: "00:00:01.516",
    partialStart: "00:00:01.449",
    partialEnd: "00:00:01.916",
    video: "./resources/chewy-piranha-plant-attack.mp4",
    poster: "./resources/chewy-piranha-plant-attack.png",
    name: "Chewy/Piranha Plant Attack",
    info: "As it lunges forward",
    note: "",
    frames: 10,
  },
  "Chomp Chomp Carni-Kiss": {
    type: "block",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.183",
    video: "./resources/chomp-chomp-carni-kiss.mp4",
    poster: "./resources/chomp-chomp-carni-kiss.png",
    name: "Chomp Chomp Carni-Kiss",
    info: "When the animated mouth closes",
    note: "",
    frames: 7,
  },
  "Chow Claw": {
    type: "block",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.650",
    partialEnd: "00:00:01.116",
    video: "./resources/chow-claw.mp4",
    poster: "./resources/chow-claw.png",
    name: "Chow Claw",
    info: "As the claw makes contact",
    note: "",
    frames: 10,
  },
  "Chow Poison": {
    type: "block",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.300",
    video: "./resources/chow-poison.mp4",
    poster: "./resources/chow-poison.png",
    name: "Chow Poison",
    info: "When its jaws close fully",
    note: "",
    frames: 8,
  },
  "Chow/K-9 Attack": {
    type: "block",
    perfect: "00:00:00.916",
    partialStart: "00:00:00.849",
    partialEnd: "00:00:01.283",
    video: "./resources/chow-k-9-attack.mp4",
    poster: "./resources/chow-k-9-attack.png",
    name: "Chow/K-9 Attack",
    info: "As the bite makes contact",
    note: "",
    frames: 12,
  },
  "Claymorton Jump": {
    type: "block",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.216",
    video: "./resources/claymorton-jump.mp4",
    poster: "./resources/claymorton-jump.png",
    name: "Claymorton Jump",
    info: "As he approaches your head",
    note: "",
    frames: 6,
  },
  "Clerk/Director/Manager Attack": {
    type: "block",
    perfect: "00:00:00.750",
    partialStart: "00:00:00.683",
    partialEnd: "00:00:01.066",
    video: "./resources/clerk-director-manager-attack.mp4",
    poster: "./resources/clerk-director-manager-attack.png",
    name: "Clerk/Director/Manager Attack",
    info: "The frame before it moves the axe forward",
    note: "",
    frames: 5,
  },
  "Cloaker Attack": {
    type: "block",
    perfect: "00:00:01.166",
    partialStart: "00:00:01.100",
    partialEnd: "00:00:01.483",
    video: "./resources/cloaker-attack.mp4",
    poster: "./resources/cloaker-attack.png",
    name: "Cloaker Attack",
    info: "Right when the sword is vertical",
    note: "As vertical as it gets",
    frames: 5,
  },
  "Cloaker Knife": {
    type: "block",
    perfect: "00:00:00.916",
    partialStart: "00:00:00.850",
    partialEnd: "00:00:01.233",
    video: "./resources/cloaker-knife.mp4",
    poster: "./resources/cloaker-knife.png",
    name: "Cloaker Knife",
    info: "At three quarters of the way",
    note: "",
    frames: 5,
  },
  "Cloaker Rock": {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.250",
    partialEnd: "00:00:01.633",
    video: "./resources/cloaker-rock.mp4",
    poster: "./resources/cloaker-rock.png",
    name: "Cloaker Rock",
    info: "A frame before it touches the warning sign",
    note: "There is probably a better reference, it's 29/36 frames",
    frames: 6,
  },
  "Cluster Psyche": {
    type: "block",
    perfect: "00:00:02.266",
    partialStart: "00:00:02.199",
    partialEnd: "00:00:02.683",
    video: "./resources/cluster-psyche.mp4",
    poster: "./resources/cluster-psyche.png",
    name: "Cluster Psyche",
    info: "After the crystals fully encase the cute pink thing",
    note: "",
    frames: 10,
  },
  "Cluster/Pulsar Attack": {
    type: "block",
    perfect: "00:00:00.850",
    partialStart: "00:00:00.783",
    partialEnd: "00:00:01.250",
    video: "./resources/cluster-pulsar-attack.mp4",
    poster: "./resources/cluster-pulsar-attack.png",
    name: "Cluster/Pulsar Attack",
    info: "As the first fragments make contact",
    note: "",
    frames: 10,
  },
  "Croco Attack": {
    type: "block",
    perfect: "00:00:01.133",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.449",
    video: "./resources/croco-attack.mp4",
    poster: "./resources/croco-attack.png",
    name: "Croco Attack",
    info: "As he bonks into you",
    note: "",
    frames: 7,
  },
  "Croco/Lakitu Monster Toss": {
    type: "block",
    perfect: "00:00:01.966",
    partialStart: "00:00:01.900",
    partialEnd: "00:00:02.283",
    video: "./resources/croco-lakitu-monster-toss.mp4",
    poster: "./resources/croco-lakitu-monster-toss.png",
    name: "Croco/Lakitu Monster Toss",
    info: "Right as the projectile bonks you",
    note: "",
    frames: 5,
  },
  "Crook/Sackit Attack": {
    type: "block",
    perfect: "00:00:00.683",
    partialStart: "00:00:00.616",
    partialEnd: "00:00:00.983",
    video: "./resources/crook-sackit-attack.mp4",
    poster: "./resources/crook-sackit-attack.png",
    name: "Crook/Sackit Attack",
    info: "After it feints the first slap",
    note: "",
    frames: 6,
  },
  "Crook/Sackit Knife": {
    type: "block",
    perfect: "00:00:00.866",
    partialStart: "00:00:00.799",
    partialEnd: "00:00:01.183",
    video: "./resources/crook-sackit-knife.mp4",
    poster: "./resources/crook-sackit-knife.png",
    name: "Crook/Sackit Knife",
    info: "Before the knife hits",
    note: "",
    frames: 7,
  },
  "Crusty/Star Cruster Claw": {
    type: "block",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:00.966",
    video: "./resources/crusty-star-cruster-claw.mp4",
    poster: "./resources/crusty-star-cruster-claw.png",
    name: "Crusty/Star Cruster Claw",
    info: "Right as the claw connects",
    note: "",
    frames: 5,
  },
  Crystal: {
    type: "block",
    perfect: "00:00:01.850",
    partialStart: "00:00:01.783",
    partialEnd: "00:00:02.250",
    video: "./resources/crystal.mp4",
    poster: "./resources/crystal.png",
    name: "Crystal",
    info: "Between the 2nd and 3rd crystals hitting",
    note: "",
    frames: 10,
  },
  "Culex 3D Attack": {
    type: "block",
    perfect: "00:00:02.350",
    partialStart: "00:00:02.283",
    partialEnd: "00:00:02.749",
    video: "./resources/culex-3d-attack.mp4",
    poster: "./resources/culex-3d-attack.png",
    name: "Culex 3D Attack",
    info: "3 frames after the frontmost crystal moves forward",
    note: "Probably find a better refence",
    frames: 10,
  },
  "Culex 3D Final Claw": {
    type: "block",
    perfect: "00:00:02.316",
    partialStart: "00:00:02.266",
    partialEnd: "00:00:02.716",
    video: "./resources/culex-3d-final-claw.mp4",
    poster: "./resources/culex-3d-final-claw.png",
    name: "Culex 3D Final Claw",
    info: "When the right hand is vertical",
    note: "2 frames in that position",
    frames: 11,
  },
  "Culex Attack": {
    type: "block",
    perfect: "00:00:00.550",
    partialStart: "00:00:00.483",
    partialEnd: "00:00:00.950",
    video: "./resources/culex-attack.mp4",
    poster: "./resources/culex-attack.png",
    name: "Culex Attack",
    info: "7 frames after the flash there is no other indication",
    note: "",
    frames: 11,
  },
  "Czar Dragon Attack": {
    type: "block",
    perfect: "00:00:01.283",
    partialStart: "00:00:01.216",
    partialEnd: "00:00:01.700",
    video: "./resources/czar-dragon-attack.mp4",
    poster: "./resources/czar-dragon-attack.png",
    name: "Czar Dragon Attack",
    info: "During the downward lunge",
    note: "",
    frames: 10,
  },
  "Dark Star": {
    type: "block",
    perfect: "00:00:03.733",
    partialStart: "00:00:03.666",
    partialEnd: "00:00:04.216",
    video: "./resources/dark-star.mp4",
    poster: "./resources/dark-star.png",
    name: "Dark Star",
    info: "At halfway down during the 3rd jump",
    note: "",
    frames: 17,
  },
  "Diamond Saw": {
    type: "block",
    perfect: "00:00:02.300",
    partialStart: "00:00:02.233",
    partialEnd: "00:00:02.616",
    video: "./resources/diamond-saw.mp4",
    poster: "./resources/diamond-saw.png",
    name: "Diamond Saw",
    info: "Right as the diamond saws are about to cross",
    note: "",
    frames: 6,
  },
  "Dodo Attack": {
    type: "block",
    perfect: "00:00:00.699",
    partialStart: "00:00:00.633",
    partialEnd: "00:00:01.016",
    video: "./resources/dodo-attack.mp4",
    poster: "./resources/dodo-attack.png",
    name: "Dodo Attack",
    info: "When his beak reaches you",
    note: "",
    frames: 6,
  },
  "Dodo Multistrike": {
    type: "block",
    perfect: "00:00:01.349",
    partialStart: "00:00:01.300",
    partialEnd: "00:00:01.683",
    video: "./resources/dodo-multistrike.mp4",
    poster: "./resources/dodo-multistrike.png",
    name: "Dodo Multistrike",
    info: "Right when his 4th peck reaches you",
    note: "",
    frames: 6,
  },
  "Dollox Body Slam": {
    type: "block",
    perfect: "00:00:00.300",
    partialStart: "00:00:00.233",
    partialEnd: "00:00:00.700",
    video: "./resources/dollox-body-slam.mp4",
    poster: "./resources/dollox-body-slam.png",
    name: "Dollox Body Slam",
    info: "As it reaches the target character",
    note: "",
    frames: 10,
  },
  "Dollox/Puppox Attack 1": {
    type: "block",
    perfect: "00:00:00.816",
    partialStart: "00:00:00.750",
    partialEnd: "00:00:01.216",
    video: "./resources/dollox-puppox-attack-1.mp4",
    poster: "./resources/dollox-puppox-attack-1.png",
    name: "Dollox/Puppox Attack 1",
    info: "As the hammer swings downward",
    note: "",
    frames: 12,
  },
  "Doppel/Shadow Orb": {
    type: "block",
    perfect: "00:00:01.000",
    partialStart: "00:00:00.949",
    partialEnd: "00:00:01.333",
    video: "./resources/doppel-shadow-orb.mp4",
    poster: "./resources/doppel-shadow-orb.png",
    name: "Doppel/Shadow Orb",
    info: "Just before the orb hits the target",
    note: "",
    frames: 6,
  },
  "Doppel/Shadow Slap": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.466",
    video: "./resources/doppel-shadow-slap.mp4",
    poster: "./resources/doppel-shadow-slap.png",
    name: "Doppel/Shadow Slap",
    info: "As it finishes spreading its arms and its eyes start to glow",
    note: "",
    frames: 7,
  },
  "Dry Bones/Vomer Bone Toss": {
    type: "block",
    perfect: "00:00:01.116",
    partialStart: "00:00:01.049",
    partialEnd: "00:00:01.433",
    video: "./resources/dry-bones-vomer-bone-toss.mp4",
    poster: "./resources/dry-bones-vomer-bone-toss.png",
    name: "Dry Bones/Vomer Bone Toss",
    info: "Just before the bone connects",
    note: "",
    frames: 5,
  },
  "Dry Bones/Vomer Head Spin": {
    type: "block",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.899",
    partialEnd: "00:00:01.283",
    video: "./resources/dry-bones-vomer-head-spin.mp4",
    poster: "./resources/dry-bones-vomer-head-spin.png",
    name: "Dry Bones/Vomer Head Spin",
    info: "As the head is traveling to you",
    note: "",
    frames: 5,
  },
  Echofinder: {
    type: "block",
    perfect: "00:00:01.533",
    partialStart: "00:00:01.466",
    partialEnd: "00:00:01.850",
    video: "./resources/echofinder.mp4",
    poster: "./resources/echofinder.png",
    name: "Echofinder",
    info: "As the circle that appears around the target grows to full size",
    note: "",
    frames: 5,
  },

  Electroshock: {
    type: "block",
    perfect: "00:00:02.800",
    partialStart: "00:00:02.733",
    partialEnd: "00:00:03.316",
    video: "./resources/electroshock.mp4",
    poster: "./resources/electroshock.png",
    name: "Electroshock",
    info: "About half a second after the lightning bolt appears over the dome",
    note: "",
    frames: 17,
  },
  "Enigma/Enigmax Attack": {
    type: "block",
    perfect: "00:00:01.350",
    partialStart: "00:00:01.283",
    partialEnd: "00:00:01.750",
    video: "./resources/enigma-enigmax-attack.mp4",
    poster: "./resources/enigma-enigmax-attack.png",
    name: "Enigma/Enigmax Attack",
    info: "After the arrow shape rears back, as it points forward again",
    note: "",
    frames: 10,
  },
  "Factory Chief Attack": {
    type: "block",
    perfect: "00:00:00.616",
    partialStart: "00:00:00.550",
    partialEnd: "00:00:00.916",
    video: "./resources/factory-chief-attack.mp4",
    poster: "./resources/factory-chief-attack.png",
    name: "Factory Chief Attack",
    info: "Before it moves its arm from behind to hit you",
    note: "",
    frames: 5,
  },
  "Fear Roulette": {
    type: "block",
    perfect: "0:00:03.616",
    partialStart: "00:00:03.550",
    partialEnd: "0:00:03.616",
    video: "./resources/fear-roulette.mp4",
    poster: "./resources/fear-roulette.png",
    name: "Fear Roulette",
    info: "A frame before it starts falling",
    note: "It will stop at 7 times before falling",
    frames: 5,
  },
  "Fink Flower/Snapdragon Attack": {
    type: "block",
    perfect: "00:00:00.783",
    partialStart: "00:00:00.716",
    partialEnd: "00:00:01.100",
    video: "./resources/fink-flower-snapdragon-attack.mp4",
    poster: "./resources/fink-flower-snapdragon-attack.png",
    name: "Fink Flower/Snapdragon Attack",
    info: "As the leaves swing down",
    note: "",
    frames: 5,
  },
  "Fire Saber": {
    type: "block",
    perfect: "00:00:01.766",
    partialStart: "00:00:01.700",
    partialEnd: "00:00:02.083",
    video: "./resources/fire-saber.mp4",
    poster: "./resources/fire-saber.png",
    name: "Fire Saber",
    info: "Just before the beam hits",
    note: "",
    frames: 5,
  },
  Flame: {
    type: "block",
    perfect: "00:00:01.533",
    partialStart: "00:00:01.466",
    partialEnd: "00:00:01.833",
    video: "./resources/flame.mp4",
    poster: "./resources/flame.png",
    name: "Flame",
    info: "When the orb descends on you",
    note: "",
    frames: 5,
  },
  "Flame Stone": {
    type: "block",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.900",
    partialEnd: "00:00:01.266",
    video: "./resources/flame-stone.mp4",
    poster: "./resources/flame-stone.png",
    name: "Flame Stone",
    info: "When the flame stone engulfs your head",
    note: "",
    frames: 5,
  },
  "Forkie/Jawful Attack": {
    type: "block",
    perfect: "00:00:00.866",
    partialStart: "00:00:00.800",
    partialEnd: "00:00:01.183",
    video: "./resources/forkie-jawful-attack.mp4",
    poster: "./resources/forkie-jawful-attack.png",
    name: "Forkie/Jawful Attack",
    info: "Just before the fork is thrust",
    note: "",
    frames: 5,
  },
  "Frogog Attack 1": {
    type: "block",
    perfect: "00:00:01.650",
    partialStart: "00:00:01.583",
    partialEnd: "00:00:02.016",
    video: "./resources/frogog-attack-1.mp4",
    poster: "./resources/frogog-attack-1.png",
    name: "Frogog Attack 1",
    info: "Just as the goop lands",
    note: "",
    frames: 9,
  },
  "Frogog Attack 2": {
    type: "block",
    perfect: "00:00:01.516",
    partialStart: "00:00:01.450",
    partialEnd: "00:00:01.850",
    video: "./resources/frogog-attack-2.mp4",
    poster: "./resources/frogog-attack-2.png",
    name: "Frogog Attack 2",
    info: "When his mouth is fully open",
    note: "",
    frames: 7,
  },
  Funguspike: {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.250",
    partialEnd: "00:00:01.649",
    video: "./resources/funguspike.mp4",
    poster: "./resources/funguspike.png",
    name: "Funguspike",
    info: "Just before the third needle hits",
    note: "",
    frames: 6,
  },
  "Geckit/Gecko Attack 1": {
    type: "block",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:01.050",
    video: "./resources/geckit-gecko-attack-1.mp4",
    poster: "./resources/geckit-gecko-attack-1.png",
    name: "Geckit/Gecko Attack 1",
    info: "As the tongue makes contact",
    note: "",
    frames: 10,
  },
  "Gecko Attack 2": {
    type: "block",
    perfect: "00:00:02.733",
    partialStart: "00:00:02.666",
    partialEnd: "00:00:03.100",
    video: "./resources/gecko-attack-2.mp4",
    poster: "./resources/gecko-attack-2.png",
    name: "Gecko Attack 2",
    info: "When the goop hits the ground",
    note: "",
    frames: 8,
  },
  "Gecko Fun &amp; Run": {
    type: "block",
    perfect: "00:00:00.366",
    partialStart: "00:00:00.316",
    partialEnd: "00:00:00.683",
    video: "./resources/gecko-fun-amp-run.mp4",
    poster: "./resources/gecko-fun-amp-run.png",
    name: "Gecko Fun &amp; Run",
    info: "Right before it makes contact",
    note: "",
    frames: 5,
  },
  "Geno Beam/Geno Blast/Geno Flash": {
    type: "attack",
    perfect: "00:00:03.349",
    partialStart: "00:00:03.116",
    partialEnd: "00:00:03.666",
    video: "./resources/geno-beam-geno-blast-geno-flash.mp4",
    poster: "./resources/geno-beam-geno-blast-geno-flash.png",
    name: "Geno Beam/Geno Blast/Geno Flash",
    info: "As the final star finishes filling up",
    note: "",
    frames: 19,
  },
  "Geno Boost": {
    type: "attack",
    perfect: "00:00:02.583",
    partialStart: "00:00:02.516",
    partialEnd: "00:00:03.233",
    video: "./resources/geno-boost.mp4",
    poster: "./resources/geno-boost.png",
    name: "Geno Boost",
    info: "As the first arrow rises above the character's head",
    note: "",
    frames: 24,
  },
  "Geno Clone Attack": {
    type: "block",
    perfect: "00:00:00.800",
    partialStart: "00:00:00.733",
    partialEnd: "00:00:01.100",
    video: "./resources/geno-clone-attack.mp4",
    poster: "./resources/geno-clone-attack.png",
    name: "Geno Clone Attack",
    info: "Before the fist hits",
    note: "",
    frames: 4,
  },
  "Geno Double Punch": {
    type: "attack",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.316",
    video: "./resources/geno-double-punch.mp4",
    poster: "./resources/geno-double-punch.png",
    name: "Geno Double Punch",
    info: "As the fists launch",
    note: "",
    frames: 9,
  },
  "Geno Finger Shot": {
    type: "attack",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.649",
    partialEnd: "00:00:01.116",
    video: "./resources/geno-finger-shot.mp4",
    poster: "./resources/geno-finger-shot.png",
    name: "Geno Finger Shot",
    info: "Right before your final bullet",
    note: "",
    frames: 10,
  },
  "Geno Hand Cannon": {
    type: "attack",
    perfect: "00:00:01.166",
    partialStart: "00:00:01.099",
    partialEnd: "00:00:01.616",
    video: "./resources/geno-hand-cannon.mp4",
    poster: "./resources/geno-hand-cannon.png",
    name: "Geno Hand Cannon",
    info: "As the first bullet fires",
    note: "",
    frames: 12,
  },
  "Geno Hand Gun": {
    type: "attack",
    perfect: "00:00:01.199",
    partialStart: "00:00:01.133",
    partialEnd: "00:00:01.633",
    video: "./resources/geno-hand-gun.mp4",
    poster: "./resources/geno-hand-gun.png",
    name: "Geno Hand Gun",
    info: "As the first bullet fires",
    note: "",
    frames: 12,
  },
  "Geno Star Gun": {
    type: "attack",
    perfect: "00:00:01.450",
    partialStart: "00:00:01.383",
    partialEnd: "00:00:01.883",
    video: "./resources/geno-star-gun.mp4",
    poster: "./resources/geno-star-gun.png",
    name: "Geno Star Gun",
    info: "As the first star fires",
    note: "",
    frames: 12,
  },
  "Geno Stella 023": {
    type: "attack",
    perfect: "00:00:01.216",
    partialStart: "00:00:01.150",
    partialEnd: "00:00:01.666",
    video: "./resources/geno-stella-023.mp4",
    poster: "./resources/geno-stella-023.png",
    name: "Geno Stella 023",
    info: "Right before the laser fires",
    note: "",
    frames: 13,
  },
  "Geno Unarmed": {
    type: "attack",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.333",
    video: "./resources/geno-unarmed.mp4",
    poster: "./resources/geno-unarmed.png",
    name: "Geno Unarmed",
    info: "As the fist launches",
    note: "",
    frames: 10,
  },
  "Geno Whirl": {
    type: "attack",
    perfect: "00:00:02.499",
    partialStart: "00:00:02.433",
    partialEnd: "00:00:02.816",
    video: "./resources/geno-whirl.mp4",
    poster: "./resources/geno-whirl.png",
    name: "Geno Whirl",
    info: "As the projectile passes through the target",
    note: "",
    frames: 5,
  },
  "Glum Reaper Sickle": {
    type: "block",
    perfect: "00:00:00.916",
    partialStart: "00:00:00.850",
    partialEnd: "00:00:01.233",
    video: "./resources/glum-reaper-scythe.mp4",
    poster: "./resources/glum-reaper-scythe.png",
    name: "Glum Reaper Sickle",
    info: "Just before the scythe connects",
    note: "",
    frames: 5,
  },
  "Glum Reaper/Greaper Attack": {
    type: "block",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.650",
    partialEnd: "00:00:01.033",
    video: "./resources/glum-reaper-greaper-attack.mp4",
    poster: "./resources/glum-reaper-greaper-attack.png",
    name: "Glum Reaper/Greaper Attack",
    info: "As the scythe connects",
    note: "",
    frames: 5,
  },
  "Glum Reaper/Greaper Fear sickle": {
    type: "block",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.250",
    video: "./resources/glum-reaper-greaper-fear-sickle.mp4",
    poster: "./resources/glum-reaper-greaper-fear-sickle.png",
    name: "Glum Reaper/Greaper Fear sickle",
    info: "Just before the scythe connects",
    note: "",
    frames: 5,
  },
  "Goomba/Pro Goomba Bite": {
    type: "block",
    perfect: "00:00:00.833",
    partialStart: "00:00:00.766",
    partialEnd: "00:00:01.149",
    video: "./resources/goomba-pro-goomba-bite.mp4",
    poster: "./resources/goomba-pro-goomba-bite.png",
    name: "Goomba/Pro Goomba Bite",
    info: "As it finishes the somersault, before it touches the ground",
    note: "",
    frames: 5,
  },
  "Goomba/Pro Goomba Spine": {
    type: "block",
    perfect: "00:00:01.233",
    partialStart: "00:00:01.166",
    partialEnd: "00:00:01.549",
    video: "./resources/goomba-pro-goomba-spine.mp4",
    poster: "./resources/goomba-pro-goomba-spine.png",
    name: "Goomba/Pro Goomba Spine",
    info: "Just before the spine makes contact",
    note: "",
    frames: 7,
  },
  "Grate Guy Attack": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.466",
    video: "./resources/grate-guy-attack.mp4",
    poster: "./resources/grate-guy-attack.png",
    name: "Grate Guy Attack",
    info: "During his max stretch",
    note: "",
    frames: 10,
  },
  "Gunk Ball": {
    type: "block",
    perfect: "00:00:01.250",
    partialStart: "00:00:01.183",
    partialEnd: "00:00:01.566",
    video: "./resources/gunk-ball.mp4",
    poster: "./resources/gunk-ball.png",
    name: "Gunk Ball",
    info: "When the projectile makes contact",
    note: "",
    frames: 5,
  },
  "Gunyolk Attack": {
    type: "block",
    perfect: "00:00:01.366",
    partialStart: "00:00:01.300",
    partialEnd: "00:00:01.783",
    video: "./resources/gunyolk-attack.mp4",
    poster: "./resources/gunyolk-attack.png",
    name: "Gunyolk Attack",
    info: "Right before the first ball hits",
    note: "2 frames before it hits",
    frames: 10,
  },
  "Hammer Bros. Attack": {
    type: "block",
    perfect: "00:00:01.066",
    partialStart: "00:00:01.000",
    partialEnd: "00:00:01.383",
    video: "./resources/hammer-bros-attack.mp4",
    poster: "./resources/hammer-bros-attack.png",
    name: "Hammer Bros. Attack",
    info: "During the downward strike",
    note: "",
    frames: 5,
  },
  "Hammer Bros. Hammer Time": {
    type: "block",
    perfect: "00:00:01.466",
    partialStart: "00:00:01.400",
    partialEnd: "00:00:01.633",
    video: "./resources/hammer-bros-hammer-time.mp4",
    poster: "./resources/hammer-bros-hammer-time.png",
    name: "Hammer Bros. Hammer Time",
    info: "During the first hammer's bonk",
    note: "",
    frames: 10,
  },
  "Helio explosion": {
    type: "block",
    perfect: "00:00:00.500",
    partialStart: "00:00:00.433",
    partialEnd: "00:00:00.866",
    video: "./resources/helio-explosion.mp4",
    poster: "./resources/helio-explosion.png",
    name: "Helio explosion",
    info: "Just before it hits",
    note: "",
    frames: 9,
  },
  "Hippopo Attack": {
    type: "block",
    perfect: "00:00:01.000",
    partialStart: "00:00:00.933",
    partialEnd: "00:00:01.316",
    video: "./resources/hippopo-attack.mp4",
    poster: "./resources/hippopo-attack.png",
    name: "Hippopo Attack",
    info: "Just after the Hippopo's mouth closes",
    note: "",
    frames: 6,
  },
  "Hippopo Body Slam": {
    type: "block",
    perfect: "00:00:00.883",
    partialStart: "00:00:00.816",
    partialEnd: "00:00:01.050",
    video: "./resources/hippopo-body-slam.mp4",
    poster: "./resources/hippopo-body-slam.png",
    name: "Hippopo Body Slam",
    info: "Just before the Hippopo makes contact",
    note: "",
    frames: 9,
  },
  "Hobgoblin Dark Claw": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.083",
    partialEnd: "00:00:01.550",
    video: "./resources/hobgoblin-dark-claw.mp4",
    poster: "./resources/hobgoblin-dark-claw.png",
    name: "Hobgoblin Dark Claw",
    info: "As it starts bringing its claws down",
    note: "",
    frames: 10,
  },
  "Hobgoblin/Straw Head Attack": {
    type: "block",
    perfect: "00:00:01.233",
    partialStart: "00:00:01.166",
    partialEnd: "00:00:01.600",
    video: "./resources/hobgoblin-straw-head-attack.mp4",
    poster: "./resources/hobgoblin-straw-head-attack.png",
    name: "Hobgoblin/Straw Head Attack",
    info: "After it finishes rearing its head back",
    note: "",
    frames: 10,
  },
  "Hot Shot": {
    type: "block",
    perfect: "00:00:01.850",
    partialStart: "00:00:01.783",
    partialEnd: "00:00:02.166",
    video: "./resources/hot-shot.mp4",
    poster: "./resources/hot-shot.png",
    name: "Hot Shot",
    info: "Right as the fire hits you",
    note: "",
    frames: 5,
  },
  "Huhwhat Attack": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.550",
    video: "./resources/huhwhat-attack.mp4",
    poster: "./resources/huhwhat-attack.png",
    name: "Huhwhat Attack",
    info: "As its eyes widen and it raises its right hand",
    note: "",
    frames: 10,
  },
  "Huhwhat/Pleaseno/Whuhoh Carni-Kiss": {
    type: "block",
    perfect: "00:00:01.366",
    partialStart: "00:00:01.300",
    partialEnd: "00:00:01.700",
    video: "./resources/huhwhat-pleaseno-whuhoh-carni-kiss.mp4",
    poster: "./resources/huhwhat-pleaseno-whuhoh-carni-kiss.png",
    name: "Huhwhat/Pleaseno/Whuhoh Carni-Kiss",
    info: "As the box closes completely",
    note: "",
    frames: 6,
  },
  "Ice Rock": {
    type: "block",
    perfect: "00:00:03.316",
    partialStart: "00:00:03.250",
    partialEnd: "00:00:03.616",
    video: "./resources/ice-rock.mp4",
    poster: "./resources/ice-rock.png",
    name: "Ice Rock",
    info: "Right as the Ice touches the ! sign. 4 frames before breaking",
    note: "4 frames before breaking",
    frames: 5,
  },
  "Ink Blast": {
    type: "block",
    perfect: "00:00:00.866",
    partialStart: "00:00:00.799",
    partialEnd: "00:00:01.183",
    video: "./resources/ink-blast.mp4",
    poster: "./resources/ink-blast.png",
    name: "Ink Blast",
    info: "Before the ink hits",
    note: "",
    frames: 6,
  },
  "Jabit Last Shot": {
    type: "block",
    perfect: "00:00:01.366",
    partialStart: "00:00:01.299",
    partialEnd: "00:00:01.683",
    video: "./resources/jabit-last-shot.mp4",
    poster: "./resources/jabit-last-shot.png",
    name: "Jabit Last Shot",
    info: "About 3/4 of the way towards the character",
    note: "13/17 frames",
    frames: 5,
  },
  "Jagger/Terra Cotta Terrapunch": {
    type: "block",
    perfect: "00:00:01.416",
    partialStart: "00:00:01.350",
    partialEnd: "00:00:01.733",
    video: "./resources/jagger-terra-cotta-terrapunch.mp4",
    poster: "./resources/jagger-terra-cotta-terrapunch.png",
    name: "Jagger/Terra Cotta Terrapunch",
    info: "At half way towards the character",
    note: "",
    frames: 5,
  },
  "Jagger/Terrapin Attack": {
    type: "block",
    perfect: "00:00:01.066",
    partialStart: "00:00:01.000",
    partialEnd: "00:00:01.449",
    video: "./resources/jagger-terrapin-attack.mp4",
    poster: "./resources/jagger-terrapin-attack.png",
    name: "Jagger/Terrapin Attack",
    info: "As the punch connects with you",
    note: "",
    frames: 8,
  },
  "Jester Attack": {
    type: "block",
    perfect: "00:00:01.716",
    partialStart: "00:00:01.649",
    partialEnd: "00:00:02.133",
    video: "./resources/jester-attack.mp4",
    poster: "./resources/jester-attack.png",
    name: "Jester Attack",
    info: "As the hand touches",
    note: "",
    frames: 12,
  },
  "Jester Card Rain": {
    type: "block",
    perfect: "00:00:01.116",
    partialStart: "00:00:01.050",
    partialEnd: "00:00:01.433",
    video: "./resources/jester-card-rain.mp4",
    poster: "./resources/jester-card-rain.png",
    name: "Jester Card Rain",
    info: "As the 3rd and 4th cards hit",
    note: "",
    frames: 7,
  },
  "Jester Card Toss": {
    type: "block",
    perfect: "00:00:01.016",
    partialStart: "00:00:00.933",
    partialEnd: "00:00:01.333",
    video: "./resources/jester-card-toss.mp4",
    poster: "./resources/jester-card-toss.png",
    name: "Jester Card Toss",
    info: "As the card hits",
    note: "",
    frames: 6,
  },
  "Jinnie Jump": {
    type: "block",
    perfect: "00:00:02.449",
    partialStart: "00:00:02.383",
    partialEnd: "00:00:02.783",
    video: "./resources/jinnie-jump.mp4",
    poster: "./resources/jinnie-jump.png",
    name: "Jinnie Jump",
    info: "A quarter second after it puckers its lips",
    note: "",
    frames: 7,
  },
  "Jinnie Orb": {
    type: "block",
    perfect: "00:00:01.466",
    partialStart: "00:00:01.399",
    partialEnd: "00:00:01.783",
    video: "./resources/jinnie-orb.mp4",
    poster: "./resources/jinnie-orb.png",
    name: "Jinnie Orb",
    info: "Before the orb hits",
    note: "",
    frames: 5,
  },
  "Jinnie Rock": {
    type: "block",
    perfect: "00:00:01.133",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.449",
    video: "./resources/jinnie-rock.mp4",
    poster: "./resources/jinnie-rock.png",
    name: "Jinnie Rock",
    info: "As the front rock reaches the character",
    note: "",
    frames: 6,
  },
  "Jinx Bombs Away": {
    type: "block",
    perfect: "00:00:01.416",
    partialStart: "00:00:01.350",
    partialEnd: "00:00:01.733",
    video: "./resources/jinx-bombs-away.mp4",
    poster: "./resources/jinx-bombs-away.png",
    name: "Jinx Bombs Away",
    info: "A 3rd of the way until it is fully on the character",
    note: "Not the first touch",
    frames: 5,
  },
  "Jinx Quicksilver": {
    type: "block",
    perfect: "00:00:00.700",
    partialStart: "00:00:00.633",
    partialEnd: "00:00:01.016",
    video: "./resources/jinx-quicksilver.mp4",
    poster: "./resources/jinx-quicksilver.png",
    name: "Jinx Quicksilver",
    info: "As Jinx jumps forward after crouching",
    note: "",
    frames: 5,
  },
  "Jinx Silver Bullet": {
    type: "block",
    perfect: "00:00:00.950",
    partialStart: "00:00:00.883",
    partialEnd: "00:00:01.266",
    video: "./resources/jinx-silver-bullet.mp4",
    poster: "./resources/jinx-silver-bullet.png",
    name: "Jinx Silver Bullet",
    info: "4 frames after the blue effect starts",
    note: "",
    frames: 6,
  },
  "Jinx Triple Kick": {
    type: "block",
    perfect: "00:00:00.916",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.233",
    video: "./resources/jinx-triple-kick.mp4",
    poster: "./resources/jinx-triple-kick.png",
    name: "Jinx Triple Kick",
    info: "About a third of the way towards the character",
    note: "3/10 frames",
    frames: 5,
  },
  Jinxed: {
    type: "block",
    perfect: "00:00:02.149",
    partialStart: "00:00:02.083",
    partialEnd: "00:00:02.500",
    video: "./resources/jinxed.mp4",
    poster: "./resources/jinxed.png",
    name: "Jinxed",
    info: "2 frames after reaching the highest point in the air",
    note: "",
    frames: 11,
  },
  "Johnny Attack": {
    type: "block",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.900",
    partialEnd: "00:00:01.283",
    video: "./resources/johnny-attack.mp4",
    poster: "./resources/johnny-attack.png",
    name: "Johnny Attack",
    info: "As the trident makes contact",
    note: "",
    frames: 6,
  },
  "Johnny Skewer": {
    type: "block",
    perfect: "00:00:01.200",
    partialStart: "00:00:01.133",
    partialEnd: "00:00:01.516",
    video: "./resources/johnny-skewer.mp4",
    poster: "./resources/johnny-skewer.png",
    name: "Johnny Skewer",
    info: "Before the trident makes contact, after the tip has spun around twice",
    note: "",
    frames: 5,
  },
  "K-9 Fangs": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.416",
    video: "./resources/k-9-fangs.mp4",
    poster: "./resources/k-9-fangs.png",
    name: "K-9 Fangs",
    info: "As the bite closes",
    note: "",
    frames: 5,
  },
  "King Calamari attack": {
    type: "block",
    perfect: "00:00:00.383",
    partialStart: "00:00:00.333",
    partialEnd: "00:00:00.800",
    video: "./resources/king-calamari-attack.mp4",
    poster: "./resources/king-calamari-attack.png",
    name: "King Calamari attack",
    info: "As it rears the tentacles back",
    note: "",
    frames: 12,
  },
  "Knife Guy Attack": {
    type: "block",
    perfect: "00:00:01.650",
    partialStart: "00:00:01.583",
    partialEnd: "00:00:01.966",
    video: "./resources/knife-guy-attack.mp4",
    poster: "./resources/knife-guy-attack.png",
    name: "Knife Guy Attack",
    info: "As the slash impact hits",
    note: "",
    frames: 7,
  },
  "Knife Guy Knife": {
    type: "block",
    perfect: "00:00:01.616",
    partialStart: "00:00:01.550",
    partialEnd: "00:00:01.933",
    video: "./resources/knife-guy-knife.mp4",
    poster: "./resources/knife-guy-knife.png",
    name: "Knife Guy Knife",
    info: "Right as the knife impacts",
    note: "",
    frames: 5,
  },
  "Lakitu Attack": {
    type: "block",
    perfect: "00:00:00.783",
    partialStart: "00:00:00.716",
    partialEnd: "00:00:01.100",
    video: "./resources/lakitu-attack.mp4",
    poster: "./resources/lakitu-attack.png",
    name: "Lakitu Attack",
    info: "Just before the slap connects",
    note: "",
    frames: 5,
  },
  "Lava Babble/Lava Blubble/Lava Bubble Attack": {
    type: "block",
    perfect: "00:00:01.833",
    partialStart: "00:00:01.766",
    partialEnd: "00:00:02.199",
    video: "./resources/lava-babble-lava-blubble-lava-bubble-attack.mp4",
    poster: "./resources/lava-babble-lava-blubble-lava-bubble-attack.png",
    name: "Lava Babble/Lava Blubble/Lava Bubble Attack",
    info: "Just before it jumps into you",
    note: "",
    frames: 8,
  },
  "Lightning Orb": {
    type: "block",
    perfect: "00:00:01.033",
    partialStart: "00:00:00.966",
    partialEnd: "00:00:01.533",
    video: "./resources/lightning-orb.mp4",
    poster: "./resources/lightning-orb.png",
    name: "Lightning Orb",
    info: "While the orb is on its way to you",
    note: "",
    frames: 17,
  },
  "Leveled-Up Punchinello Grinder": {
    type: "block",
    perfect: "00:00:01.150",
    partialStart: "00:00:01.066",
    partialEnd: "00:00:01.466",
    video: "./resources/leveled-up-punchinello-grinder.mp4",
    poster: "./resources/leveled-up-punchinello-grinder.png",
    name: "Leveled-Up Punchinello Grinder",
    info: "Right when it starts moving its arm forward",
    note: "",
    frames: 5,
  },
  "Machine Made (Axem Yellow) Body Slam": {
    type: "block",
    perfect: "00:00:00.833",
    partialStart: "00:00:00.766",
    partialEnd: "00:00:01.233",
    video: "./resources/machine-made-axem-yellow-body-slam.mp4",
    poster: "./resources/machine-made-axem-yellow-body-slam.png",
    name: "Machine Made (Axem Yellow) Body Slam",
    info: "A bit before half way to the character",
    note: "5/12 frames",
    frames: 10,
  },
  "Machine Made (Drill Bit) Attack": {
    type: "block",
    perfect: "00:00:00.983",
    partialStart: "00:00:00.916",
    partialEnd: "00:00:01.300",
    video: "./resources/machine-made-drill-bit-attack.mp4",
    poster: "./resources/machine-made-drill-bit-attack.png",
    name: "Machine Made (Drill Bit) Attack",
    info: "Half way between Drill Bit and the character",
    note: "",
    frames: 6,
  },
  "Machine Made (Drill Bit) Skewer": {
    type: "block",
    perfect: "00:00:00.983",
    partialStart: "00:00:00.916",
    partialEnd: "00:00:01.300",
    video: "./resources/machine-made-drill-bit-skewer.mp4",
    poster: "./resources/machine-made-drill-bit-skewer.png",
    name: "Machine Made (Drill Bit) Skewer",
    info: "Half way between Drill Bit and the character",
    note: "",
    frames: 6,
  },
  "Mad Mallet Attack": {
    type: "block",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.650",
    partialEnd: "00:00:01.033",
    video: "./resources/mad-mallet-attack.mp4",
    poster: "./resources/mad-mallet-attack.png",
    name: "Mad Mallet Attack",
    info: "Right when it is vertical",
    note: "",
    frames: 5,
  },
  "Magmite/Magmus Attack": {
    type: "block",
    perfect: "00:00:02.066",
    partialStart: "00:00:02.000",
    partialEnd: "00:00:02.383",
    video: "./resources/magmite-magmus-attack.mp4",
    poster: "./resources/magmite-magmus-attack.png",
    name: "Magmite/Magmus Attack",
    info: "As its body makes contact",
    note: "",
    frames: 5,
  },
  "Malakoopa/Paratroopa Attack": {
    type: "block",
    perfect: "00:00:01.166",
    partialStart: "00:00:01.099",
    partialEnd: "00:00:01.516",
    video: "./resources/malakoopa-paratroopa-attack.mp4",
    poster: "./resources/malakoopa-paratroopa-attack.png",
    name: "Malakoopa/Paratroopa Attack",
    info: "Right as it bonks into you",
    note: "",
    frames: 7,
  },
  "Mallow Clone Attack": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:00.983",
    video: "./resources/mallow-clone-attack.mp4",
    poster: "./resources/mallow-clone-attack.png",
    name: "Mallow Clone Attack",
    info: "As the fist connects",
    note: "",
    frames: 5,
  },
  "Mallow Cymbals": {
    type: "attack",
    perfect: "00:00:00.533",
    partialStart: "00:00:00.466",
    partialEnd: "00:00:00.849",
    video: "./resources/mallow-cymbals.mp4",
    poster: "./resources/mallow-cymbals.png",
    name: "Mallow Cymbals",
    info: "Right as the cymbals clap together",
    note: "",
    frames: 5,
  },
  "Mallow Froggiestick": {
    type: "attack",
    perfect: "00:00:00.733",
    partialStart: "00:00:00.666",
    partialEnd: "00:00:01.050",
    video: "./resources/mallow-froggiestick.mp4",
    poster: "./resources/mallow-froggiestick.png",
    name: "Mallow Froggiestick",
    info: "As stick impact hits",
    note: "",
    frames: 5,
  },
  "Mallow HP Rain": {
    type: "attack",
    perfect: "00:00:04.516",
    partialStart: "00:00:04.450",
    partialEnd: "00:00:05.083",
    video: "./resources/mallow-hp-rain.mp4",
    poster: "./resources/mallow-hp-rain.png",
    name: "Mallow HP Rain",
    info: "During the extended hover period",
    note: "about 20 frames long",
    frames: 20,
  },
  "Mallow Ribbit Stick": {
    type: "attack",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:00.966",
    video: "./resources/mallow-ribbit-stick.mp4",
    poster: "./resources/mallow-ribbit-stick.png",
    name: "Mallow Ribbit Stick",
    info: "As the stick hits the ground",
    note: "",
    frames: 5,
  },
  "Mallow Sage Stick": {
    type: "attack",
    perfect: "00:00:00.733",
    partialStart: "00:00:00.666",
    partialEnd: "00:00:01.049",
    video: "./resources/mallow-sage-stick.mp4",
    poster: "./resources/mallow-sage-stick.png",
    name: "Mallow Sage Stick",
    info: "As stick impact hits",
    note: "",
    frames: 5,
  },
  "Mallow Shocker": {
    type: "attack",
    perfect: "00:00:02.049",
    partialStart: "00:00:01.983",
    partialEnd: "00:00:02.416",
    video: "./resources/mallow-shocker.mp4",
    poster: "./resources/mallow-shocker.png",
    name: "Mallow Shocker",
    info: "Right when lightning strikes",
    note: "",
    frames: 5,
  },
  "Mallow Sonic Cymbal": {
    type: "attack",
    perfect: "00:00:00.583",
    partialStart: "00:00:00.516",
    partialEnd: "00:00:00.900",
    video: "./resources/mallow-sonic-cymbal.mp4",
    poster: "./resources/mallow-sonic-cymbal.png",
    name: "Mallow Sonic Cymbal",
    info: "Right as the cymbals clap together",
    note: "",
    frames: 5,
  },
  "Mallow Sticky Glove": {
    type: "attack",
    perfect: "00:00:00.633",
    partialStart: "00:00:00.566",
    partialEnd: "00:00:01.016",
    video: "./resources/mallow-sticky-glove.mp4",
    poster: "./resources/mallow-sticky-glove.png",
    name: "Mallow Sticky Glove",
    info: "Right after arms start to go forward",
    note: "",
    frames: 9,
  },
  "Mallow Thought Peek": {
    type: "block",
    perfect: "00:00:02.800",
    partialStart: "00:00:02.716",
    partialEnd: "00:00:03.349",
    video: "./resources/mallow-thought-pee.mp4",
    poster: "./resources/mallow-thought-pee.png",
    name: "Mallow Thought Peek",
    info: "When the spotlights converge",
    note: "",
    frames: 19,
  },
  "Mallow Thunderbolt": {
    type: "attack",
    perfect: "00:00:02.533",
    partialStart: "00:00:02.466",
    partialEnd: "00:00:02.933",
    video: "./resources/mallow-thunderbolt.mp4",
    poster: "./resources/mallow-thunderbolt.png",
    name: "Mallow Thunderbolt",
    info: "When 3 bolts in a row start to clear",
    note: "",
    frames: 10,
  },
  "Mallow Unarmed": {
    type: "attack",
    perfect: "00:00:00.316",
    partialStart: "00:00:00.250",
    partialEnd: "00:00:00.883",
    video: "./resources/mallow-unarmed.mp4",
    poster: "./resources/mallow-unarmed.png",
    name: "Mallow Unarmed",
    info: "As Mallow extends his fist",
    note: "",
    frames: 20,
  },
  "Mallow Whomp Glove": {
    type: "attack",
    perfect: "00:00:00.466",
    partialStart: "00:00:00.416",
    partialEnd: "00:00:00.800",
    video: "./resources/mallow-whomp-glove.mp4",
    poster: "./resources/mallow-whomp-glove.png",
    name: "Mallow Whomp Glove",
    info: "Right before Mallow extends his fist",
    note: "",
    frames: 6,
  },
  "Mario Clone Attack": {
    type: "block",
    perfect: "00:00:01.216",
    partialStart: "00:00:01.150",
    partialEnd: "00:00:01.533",
    video: "./resources/mario-clone-attack.mp4",
    poster: "./resources/mario-clone-attack.png",
    name: "Mario Clone Attack",
    info: "Before the clone hits the target",
    note: "",
    frames: 5,
  },
  "Mario Hammer": {
    type: "attack",
    perfect: "00:00:00.533",
    partialStart: "00:00:00.466",
    partialEnd: "00:00:01.083",
    video: "./resources/mario-hammer.mp4",
    poster: "./resources/mario-hammer.png",
    name: "Mario Hammer",
    info: "During the swing",
    note: "",
    frames: 19,
  },
  "Mario Jump": {
    type: "attack",
    perfect: "00:00:01.183",
    partialStart: "00:00:01.183",
    partialEnd: "00:00:01.483",
    video: "./resources/mario-jump.mp4",
    poster: "./resources/mario-jump.png",
    name: "Mario Jump",
    info: "When Mario appears on screen",
    note: "Might even be earlier. The indicator comes on screen with him.",
    frames: 8,
  },
  "Mario Koopa Shell": {
    type: "attack",
    perfect: "00:00:00.883",
    partialStart: "00:00:00.816",
    partialEnd: "00:00:01.200",
    video: "./resources/mario-koopa-shell.mp4",
    poster: "./resources/mario-koopa-shell.png",
    name: "Mario Koopa Shell",
    info: "Before the shell touches the ground",
    note: "",
    frames: 5,
  },
  "Mario Lazy Shell": {
    type: "attack",
    perfect: "00:00:00.949",
    partialStart: "00:00:00.883",
    partialEnd: "00:00:01.266",
    video: "./resources/mario-lazy-shell.mp4",
    poster: "./resources/mario-lazy-shell.png",
    name: "Mario Lazy Shell",
    info: "Before connecting with Mario's foot",
    note: "",
    frames: 5,
  },
  "Mario Masher": {
    type: "attack",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:01.133",
    video: "./resources/mario-masher.mp4",
    poster: "./resources/mario-masher.png",
    name: "Mario Masher",
    info: "During the forward swing",
    note: "",
    frames: 15,
  },
  "Mario Mega Glove": {
    type: "attack",
    perfect: "00:00:00.533",
    partialStart: "00:00:00.466",
    partialEnd: "00:00:00.816",
    video: "./resources/mario-mega-glove.mp4",
    poster: "./resources/mario-mega-glove.png",
    name: "Mario Mega Glove",
    info: "When Mario's punch is behind him",
    note: "",
    frames: 4,
  },
  "Mario Paratroopa Shell": {
    type: "attack",
    perfect: "00:00:00.966",
    partialStart: "00:00:00.883",
    partialEnd: "00:00:01.283",
    video: "./resources/mario-paratroopa-shell.mp4",
    poster: "./resources/mario-paratroopa-shell.png",
    name: "Mario Paratroopa Shell",
    info: "Right when Mario's foot is vertical ",
    note: "11/19 frames from the shell highest point to the floor",
    frames: 5,
  },
  "Mario Punch Glove": {
    type: "attack",
    perfect: "00:00:00.483",
    partialStart: "00:00:00.416",
    partialEnd: "00:00:00.816",
    video: "./resources/mario-punch-glove.mp4",
    poster: "./resources/mario-punch-glove.png",
    name: "Mario Punch Glove",
    info: "During the forward swing",
    note: "",
    frames: 6,
  },
  "Mario Super Hammer": {
    type: "attack",
    perfect: "00:00:00.616",
    partialStart: "00:00:00.566",
    partialEnd: "00:00:00.950",
    video: "./resources/mario-super-hammer.mp4",
    poster: "./resources/mario-super-hammer.png",
    name: "Mario Super Hammer",
    info: "At the start of the swing",
    note: "",
    frames: 5,
  },
  "Mario Ultra Hammer": {
    type: "attack",
    perfect: "00:00:00.733",
    partialStart: "00:00:00.666",
    partialEnd: "00:00:01.049",
    video: "./resources/mario-ultra-hammer.mp4",
    poster: "./resources/mario-ultra-hammer.png",
    name: "Mario Ultra Hammer",
    info: "During the downward swing",
    note: "",
    frames: 5,
  },
  "Mario Unarmed": {
    type: "attack",
    perfect: "00:00:00.483",
    partialStart: "00:00:00.416",
    partialEnd: "00:00:00.783",
    video: "./resources/mario-unarmed.mp4",
    poster: "./resources/mario-unarmed.png",
    name: "Mario Unarmed",
    info: "During the forward swing",
    note: "",
    frames: 4,
  },
  "Mastadoom Attack 1": {
    type: "block",
    perfect: "00:00:00.649",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:01.049",
    video: "./resources/mastadoom-attack-1.mp4",
    poster: "./resources/mastadoom-attack-1.png",
    name: "Mastadoom Attack 1",
    info: "When the trunk reaches the bottom of the swing",
    note: "",
    frames: 10,
  },
  "Mastadoom Attack 2": {
    type: "block",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.250",
    video: "./resources/mastadoom-attack-2.mp4",
    poster: "./resources/mastadoom-attack-2.png",
    name: "Mastadoom Attack 2",
    info: "Right before the bone hits",
    note: "",
    frames: 5,
  },
  "Megasmilax Attack": {
    type: "block",
    perfect: "00:00:00.400",
    partialStart: "00:00:00.333",
    partialEnd: "00:00:00.716",
    video: "./resources/megasmilax-attack.mp4",
    poster: "./resources/megasmilax-attack.png",
    name: "Megasmilax Attack",
    info: "As it lunges forward",
    note: "",
    frames: 5,
  },
  "Mezzo Bomb Explosion": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.066",
    video: "./resources/mezzo-bomb-explosion.mp4",
    poster: "./resources/mezzo-bomb-explosion.png",
    name: "Mezzo Bomb Explosion",
    info: "When the bomb gets close to you",
    note: "",
    frames: 10,
  },
  "Micro Bomb Explosion": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:01.066",
    video: "./resources/micro-bomb-explosion.mp4",
    poster: "./resources/micro-bomb-explosion.png",
    name: "Micro Bomb Explosion",
    info: "When the bomb gets close to you",
    note: "",
    frames: 10,
  },
  "Mini Goomba Bite": {
    type: "block",
    perfect: "00:00:00.833",
    partialStart: "00:00:00.766",
    partialEnd: "00:00:01.150",
    video: "./resources/mini-goomba-bite.mp4",
    poster: "./resources/mini-goomba-bite.png",
    name: "Mini Goomba Bite",
    info: "As it finishes the somersault, before it touches the ground",
    note: "",
    frames: 5,
  },
  "Mouth Attack": {
    type: "block",
    perfect: "00:00:00.983",
    partialStart: "00:00:00.916",
    partialEnd: "00:00:01.300",
    video: "./resources/mouth-attack.mp4",
    poster: "./resources/mouth-attack.png",
    name: "Mouth Attack",
    info: "As the mouth fully closes",
    note: "",
    frames: 5,
  },
  "Mouth Carni-Kiss": {
    type: "block",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.649",
    partialEnd: "00:00:01.033",
    video: "./resources/mouth-carni-kiss.mp4",
    poster: "./resources/mouth-carni-kiss.png",
    name: "Mouth Carni-Kiss",
    info: "As the animated teeth fully close",
    note: "",
    frames: 5,
  },
  "Ninja Knife": {
    type: "block",
    perfect: "00:00:00.783",
    partialStart: "00:00:00.700",
    partialEnd: "00:00:01.100",
    video: "./resources/ninja-knife.mp4",
    poster: "./resources/ninja-knife.png",
    name: "Ninja Knife",
    info: "Just before the knife hits",
    note: "",
    frames: 4,
  },
  "Ninja Shuriken": {
    type: "block",
    perfect: "00:00:01.183",
    partialStart: "00:00:01.116",
    partialEnd: "00:00:01.283",
    video: "./resources/ninja-shuriken.mp4",
    poster: "./resources/ninja-shuriken.png",
    name: "Ninja Shuriken",
    info: "Just before the shuriken hits",
    note: "",
    frames: 5,
  },
  "Ninja Warp Stab": {
    type: "block",
    perfect: "00:00:00.616",
    partialStart: "00:00:00.550",
    partialEnd: "00:00:00.950",
    video: "./resources/ninja-warp-stab.mp4",
    poster: "./resources/ninja-warp-stab.png",
    name: "Ninja Warp Stab",
    info: "Just after the ninja's arm moves forward",
    note: "",
    frames: 5,
  },
  "Octolot/Octovader Attack": {
    type: "block",
    perfect: "00:00:01.866",
    partialStart: "00:00:01.800",
    partialEnd: "00:00:02.266",
    video: "./resources/octolot-octovader-attack.mp4",
    poster: "./resources/octolot-octovader-attack.png",
    name: "Octolot/Octovader Attack",
    info: "Once the mouth fully widens",
    note: "",
    frames: 10,
  },
  "Orbison Attack": {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.249",
    partialEnd: "00:00:01.699",
    video: "./resources/orbison-attack.mp4",
    poster: "./resources/orbison-attack.png",
    name: "Orbison Attack",
    info: "Just before the orb makes contact",
    note: "",
    frames: 10,
  },
  "Peach Clone Attack": {
    type: "block",
    perfect: "00:00:00.616",
    partialStart: "00:00:00.550",
    partialEnd: "00:00:01.016",
    video: "./resources/peach-clone-attack.mp4",
    poster: "./resources/peach-clone-attack.png",
    name: "Peach Clone Attack",
    info: "In between the first and second slaps",
    note: "",
    frames: 10,
  },
  "Peach Come Back": {
    type: "attack",
    perfect: "00:00:03.516",
    partialStart: "00:00:03.450",
    partialEnd: "00:00:03.850",
    video: "./resources/peach-come-back.mp4",
    poster: "./resources/peach-come-back.png",
    name: "Peach Come Back",
    info: "Once the star overlaps the character's model",
    note: "",
    frames: 8,
  },
  "Peach Frying Pan": {
    type: "attack",
    perfect: "00:00:00.533",
    partialStart: "00:00:00.466",
    partialEnd: "00:00:00.933",
    video: "./resources/peach-frying-pan.mp4",
    poster: "./resources/peach-frying-pan.png",
    name: "Peach Frying Pan",
    info: "At the height of Peach raising the pan",
    note: "",
    frames: 10,
  },
  "Peach Group Hug": {
    type: "attack",
    perfect: "00:00:01.800",
    partialStart: "00:00:01.733",
    partialEnd: "00:00:02.216",
    video: "./resources/peach-group-hug.mp4",
    poster: "./resources/peach-group-hug.png",
    name: "Peach Group Hug",
    info: "After the double chirping sound, when the stars shrink in size",
    note: "",
    frames: 10,
  },
  "Peach Parasol": {
    type: "attack",
    perfect: "00:00:00.583",
    partialStart: "00:00:00.516",
    partialEnd: "00:00:00.983",
    video: "./resources/peach-parasol.mp4",
    poster: "./resources/peach-parasol.png",
    name: "Peach Parasol",
    info: "During the downward swing",
    note: "",
    frames: 10,
  },
  "Peach Slap Glove": {
    type: "attack",
    perfect: "00:00:00.583",
    partialStart: "00:00:00.516",
    partialEnd: "00:00:00.983",
    video: "./resources/peach-slap-glove.mp4",
    poster: "./resources/peach-slap-glove.png",
    name: "Peach Slap Glove",
    info: "When the first slap connects",
    note: "",
    frames: 10,
  },
  "Peach Super Slap": {
    type: "attack",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.599",
    partialEnd: "00:00:01.066",
    video: "./resources/peach-super-slap.mp4",
    poster: "./resources/peach-super-slap.png",
    name: "Peach Super Slap",
    info: "When the first slap connects",
    note: "",
    frames: 10,
  },
  "Peach Therapy": {
    type: "attack",
    perfect: "00:00:01.783",
    partialStart: "00:00:01.716",
    partialEnd: "00:00:02.183",
    video: "./resources/peach-therapy.mp4",
    poster: "./resources/peach-therapy.png",
    name: "Peach Therapy",
    info: "After the double chirping sound, when the stars shrink in size",
    note: "",
    frames: 10,
  },
  "Peach Unarmed": {
    type: "attack",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.599",
    partialEnd: "00:00:01.066",
    video: "./resources/peach-unarmed.mp4",
    poster: "./resources/peach-unarmed.png",
    name: "Peach Unarmed",
    info: "When the first slap connects",
    note: "",
    frames: 10,
  },
  "Peach War Fan": {
    type: "attack",
    perfect: "00:00:00.700",
    partialStart: "00:00:00.633",
    partialEnd: "00:00:01.066",
    video: "./resources/peach-war-fan.mp4",
    poster: "./resources/peach-war-fan.png",
    name: "Peach War Fan",
    info: "The frame the fan is vertical in front of Peach",
    note: "",
    frames: 8,
  },
  "Pinwheel Attack": {
    type: "block",
    perfect: "00:00:00.749",
    partialStart: "00:00:00.683",
    partialEnd: "00:00:01.066",
    video: "./resources/pinwheel-attack.mp4",
    poster: "./resources/pinwheel-attack.png",
    name: "Pinwheel Attack",
    info: "Starts the first frame the second time it flashes white / before it's face flashed to red for the fourth time ",
    note: "",
    frames: 6,
  },
  "Pleaseno Attack": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.400",
    video: "./resources/pleaseno-attack.mp4",
    poster: "./resources/pleaseno-attack.png",
    name: "Pleaseno Attack",
    info: "As soon as it splits into two",
    note: "",
    frames: 5,
  },
  "Pounder Attack": {
    type: "block",
    perfect: "00:00:00.733",
    partialStart: "00:00:00.666",
    partialEnd: "00:00:01.016",
    video: "./resources/test2.mp4",
    poster: "./resources/pounder-attack.png",
    name: "Pounder Attack",
    info: "Right the frame it is almost vertical",
    note: "As vertical as it gets during the animation",
    frames: 6,
  },
  "Pounder/Poundette Mallet": {
    type: "block",
    perfect: "00:00:01.050",
    partialStart: "00:00:00.983",
    partialEnd: "00:00:01.366",
    video: "./resources/test.mp4",
    poster: "./resources/pounder-poundette-mallet.png",
    name: "Pounder/Poundette Mallet",
    info: "About 3/4 of the mallet's arc",
    note: "It remains 2 frames in that position",
    frames: 4,
  },
  "Poundette Attack": {
    type: "block",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.650",
    partialEnd: "00:00:01.016",
    video: "./resources/poundette-attack.mp4",
    poster: "./resources/poundette-attack.png",
    name: "Poundette Attack",
    info: "Right when it's vertical",
    note: "As vertical as it gets",
    frames: 5,
  },
  "Pulsar Migraine": {
    type: "block",
    perfect: "00:00:02.283",
    partialStart: "00:00:02.199",
    partialEnd: "00:00:02.683",
    video: "./resources/pulsar-migraine.mp4",
    poster: "./resources/pulsar-migraine.png",
    name: "Pulsar Migraine",
    info: "After the crystals fully encase the cute blue thing",
    note: "",
    frames: 9,
  },
  "Punchinello Attack": {
    type: "block",
    perfect: "00:00:00.849",
    partialStart: "00:00:00.783",
    partialEnd: "00:00:01.166",
    video: "./resources/punchinello-attack.mp4",
    poster: "./resources/punchinello-attack.png",
    name: "Punchinello Attack",
    info: "As he makes contact",
    note: "",
    frames: 6,
  },
  "Puppox Attack 2": {
    type: "block",
    perfect: "00:00:00.816",
    partialStart: "00:00:00.750",
    partialEnd: "00:00:01.216",
    video: "./resources/puppox-attack-2.mp4",
    poster: "./resources/puppox-attack-2.png",
    name: "Puppox Attack 2",
    info: "As the right foot touches the ground",
    note: "One frame before touching the ground",
    frames: 10,
  },
  "Raspberry Attack": {
    type: "block",
    perfect: "00:00:00.266",
    partialStart: "00:00:00.200",
    partialEnd: "00:00:00.633",
    video: "./resources/raspberry-attack.mp4",
    poster: "./resources/raspberry-attack.png",
    name: "Raspberry Attack",
    info: "While the mouth is closing",
    note: "",
    frames: 8,
  },
  "Raspberry Orb": {
    type: "block",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:00.966",
    video: "./resources/raspberry-orb.mp4",
    poster: "./resources/raspberry-orb.png",
    name: "Raspberry Orb",
    info: "As the orb is about to hit",
    note: "",
    frames: 6,
  },
  "Reacher Fast Bone Toss": {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.250",
    partialEnd: "00:00:01.633",
    video: "./resources/reacher-fast-bone-toss.mp4",
    poster: "./resources/reacher-fast-bone-toss.png",
    name: "Reacher Fast Bone Toss",
    info: "Just before the bone hits",
    note: "",
    frames: 7,
  },
  "Reacher Reach": {
    type: "block",
    perfect: "00:00:01.216",
    partialStart: "00:00:01.150",
    partialEnd: "00:00:01.533",
    video: "./resources/reacher-reach.mp4",
    poster: "./resources/reacher-reach.png",
    name: "Reacher Reach",
    info: "When the hands extend to their furthest point",
    note: "",
    frames: 5,
  },
  "Ribbite Attack": {
    type: "block",
    perfect: "00:00:01.550",
    partialStart: "00:00:01.483",
    partialEnd: "00:00:01.866",
    video: "./resources/ribbite-attack.mp4",
    poster: "./resources/ribbite-attack.png",
    name: "Ribbite Attack",
    info: "As it leans forward",
    note: "2 frames after being vertical",
    frames: 5,
  },
  "Right Eye Attack": {
    type: "block",
    perfect: "00:00:00.400",
    partialStart: "00:00:00.333",
    partialEnd: "00:00:00.716",
    video: "./resources/right-eye-attack.mp4",
    poster: "./resources/right-eye-attack.png",
    name: "Right Eye Attack",
    info: "Right after the pupil narrows",
    note: "",
    frames: 5,
  },
  "Ring-a-Ding Attack": {
    type: "block",
    perfect: "00:00:00.933",
    partialStart: "00:00:00.866",
    partialEnd: "00:00:01.399",
    video: "./resources/ring-a-ding-attack.mp4",
    poster: "./resources/ring-a-ding-attack.png",
    name: "Ring-a-Ding Attack",
    info: "A frame before the last star comes out of the bell",
    note: "",
    frames: 15,
  },
  "Shaman Attack": {
    type: "block",
    perfect: "00:00:00.699",
    partialStart: "00:00:00.633",
    partialEnd: "00:00:01.016",
    video: "./resources/shaman-attack.mp4",
    poster: "./resources/shaman-attack.png",
    name: "Shaman Attack",
    info: "When the wand hits you",
    note: "",
    frames: 5,
  },
  "Shy Guy/Shy Ranger/Sling Shy Slingshot": {
    type: "block",
    perfect: "00:00:00.900",
    partialStart: "00:00:00.833",
    partialEnd: "00:00:01.266",
    video: "./resources/shy-guy-shy-ranger-sling-shy-slingshot.mp4",
    poster: "./resources/shy-guy-shy-ranger-sling-shy-slingshot.png",
    name: "Shy Guy/Shy Ranger/Sling Shy Slingshot",
    info: "Once the shot is about halfway to its target",
    note: "",
    frames: 8,
  },
  "Shy Ranger Knife": {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.250",
    partialEnd: "00:00:01.633",
    video: "./resources/shy-ranger-knife.mp4",
    poster: "./resources/shy-ranger-knife.png",
    name: "Shy Ranger Knife",
    info: "Just before the knife hits",
    note: "",
    frames: 5,
  },
  "Shy Ranger Shuriken": {
    type: "block",
    perfect: "00:00:01.349",
    partialStart: "00:00:01.283",
    partialEnd: "00:00:01.666",
    video: "./resources/shy-ranger-shuriken.mp4",
    poster: "./resources/shy-ranger-shuriken.png",
    name: "Shy Ranger Shuriken",
    info: "Just before the shuriken hits",
    note: "",
    frames: 5,
  },
  "Smilax Attack": {
    type: "block",
    perfect: "00:00:00.649",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:00.966",
    video: "./resources/smilax-attack.mp4",
    poster: "./resources/smilax-attack.png",
    name: "Smilax Attack",
    info: "As it lunges forward",
    note: "",
    frames: 5,
  },
  "Smithy 1 Hammer": {
    type: "block",
    perfect: "00:00:01.416",
    partialStart: "00:00:01.366",
    partialEnd: "00:00:01.750",
    video: "./resources/smithy-1-hammer.mp4",
    poster: "./resources/smithy-1-hammer.png",
    name: "Smithy 1 Hammer",
    info: "As he swings down",
    note: "",
    frames: 5,
  },
  "Smithy 2 Finger Gun": {
    type: "block",
    perfect: "00:00:01.616",
    partialStart: "00:00:01.550",
    partialEnd: "00:00:01.949",
    video: "./resources/smithy-2-finger-gun.mp4",
    poster: "./resources/smithy-2-finger-gun.png",
    name: "Smithy 2 Finger Gun",
    info: "Just before the final bullet hits",
    note: "",
    frames: 10,
  },
  "Smithy 2 Hammer": {
    type: "block",
    perfect: "00:00:01.399",
    partialStart: "00:00:01.333",
    partialEnd: "00:00:01.716",
    video: "./resources/smithy-2-hammer.mp4",
    poster: "./resources/smithy-2-hammer.png",
    name: "Smithy 2 Hammer",
    info: "As he swings down",
    note: "",
    frames: 6,
  },
  "Smithy 2 Magnum": {
    type: "block",
    perfect: "00:00:01.283",
    partialStart: "00:00:01.216",
    partialEnd: "00:00:01.600",
    video: "./resources/smithy-2-magnum.mp4",
    poster: "./resources/smithy-2-magnum.png",
    name: "Smithy 2 Magnum",
    info: "Just before the bullet bill hits",
    note: "",
    frames: 5,
  },
  "Speardovich Attack": {
    type: "block",
    perfect: "00:00:01.566",
    partialStart: "00:00:01.500",
    partialEnd: "00:00:01.966",
    video: "./resources/speardovich-attack.mp4",
    poster: "./resources/speardovich-attack.png",
    name: "Speardovich Attack",
    info: "During the spear lunge",
    note: "",
    frames: 10,
  },
  "Speardovich Orb": {
    type: "block",
    perfect: "00:00:01.033",
    partialStart: "00:00:00.966",
    partialEnd: "00:00:01.350",
    video: "./resources/speardovich-orb.mp4",
    poster: "./resources/speardovich-orb.png",
    name: "Speardovich Orb",
    info: "Just before the orb hits",
    note: "",
    frames: 5,
  },
  "Speardovich Pierce": {
    type: "block",
    perfect: "00:00:01.800",
    partialStart: "00:00:01.733",
    partialEnd: "00:00:02.216",
    video: "./resources/speardovich-pierce.mp4",
    poster: "./resources/speardovich-pierce.png",
    name: "Speardovich Pierce",
    info: "After the glint, while the spear is thrusting",
    note: "",
    frames: 10,
  },
  "Spikester/Spikey/Urspike Attack 1": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.600",
    partialEnd: "00:00:00.983",
    video: "./resources/spikester-spikey-urspike-attack-1.mp4",
    poster: "./resources/spikester-spikey-urspike-attack-1.png",
    name: "Spikester/Spikey/Urspike Attack 1",
    info: "When he begins to fall",
    note: "",
    frames: 5,
  },
  "Spikey/Urspike Attack 2": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.400",
    video: "./resources/spikey-urspike-attack-2.mp4",
    poster: "./resources/spikey-urspike-attack-2.png",
    name: "Spikey/Urspike Attack 2",
    info: "Just before the needle hits",
    note: "",
    frames: 5,
  },
  "Spinthra Poison": {
    type: "block",
    perfect: "00:00:00.716",
    partialStart: "00:00:00.649",
    partialEnd: "00:00:01.050",
    video: "./resources/spinthra-poison.mp4",
    poster: "./resources/spinthra-poison.png",
    name: "Spinthra Poison",
    info: "During the lunge",
    note: "",
    frames: 8,
  },
  "Spritz Bomb": {
    type: "block",
    perfect: "00:00:01.416",
    partialStart: "00:00:01.350",
    partialEnd: "00:00:01.733",
    video: "./resources/spritz-bomb.mp4",
    poster: "./resources/spritz-bomb.png",
    name: "Spritz Bomb",
    info: "At about three quarters of the arc",
    note: "",
    frames: 5,
  },
  "Starslap/Zeostar Attack": {
    type: "block",
    perfect: "00:00:02.083",
    partialStart: "00:00:02.016",
    partialEnd: "00:00:02.400",
    video: "./resources/starslap-zeostar-attack.mp4",
    poster: "./resources/starslap-zeostar-attack.png",
    name: "Starslap/Zeostar Attack",
    info: "Just before unleashing the kick",
    note: "",
    frames: 5,
  },
  "Stompillar Attack": {
    type: "block",
    perfect: "00:00:01.316",
    partialStart: "00:00:01.250",
    partialEnd: "00:00:01.683",
    video: "./resources/stompillar-attack.mp4",
    poster: "./resources/stompillar-attack.png",
    name: "Stompillar Attack",
    info: "As the mouth is closing",
    note: "5 frames before it's fully closed",
    frames: 9,
  },
  "Stop it!": {
    type: "block",
    perfect: "00:00:02.750",
    partialStart: "00:00:02.683",
    partialEnd: "00:00:03.150",
    video: "./resources/stop-it-.mp4",
    poster: "./resources/stop-it-.png",
    name: "Stop it!",
    info: "As the final hit comes down",
    note: "",
    frames: 10,
  },
  "Stop! Stop!": {
    type: "block",
    perfect: "00:00:01.683",
    partialStart: "00:00:01.616",
    partialEnd: "00:00:02.083",
    video: "./resources/stop-stop-.mp4",
    poster: "./resources/stop-stop-.png",
    name: "Stop! Stop!",
    info: "As the final hit comes down",
    note: "",
    frames: 10,
  },
  Storm: {
    type: "block",
    perfect: "00:00:01.983",
    partialStart: "00:00:01.916",
    partialEnd: "00:00:02.350",
    video: "./resources/storm.mp4",
    poster: "./resources/storm.png",
    name: "Storm",
    info: "After the tornado starts clearing",
    note: "",
    frames: 7,
  },
  "Strong Bowser Clone Claw": {
    type: "block",
    perfect: "00:00:00.666",
    partialStart: "00:00:00.599",
    partialEnd: "00:00:01.033",
    video: "./resources/strong-bowser-clone-claw.mp4",
    poster: "./resources/strong-bowser-clone-claw.png",
    name: "Strong Bowser Clone Claw",
    info: "As Bowser's arm is coming forward",
    note: "",
    frames: 12,
  },
  "Strong Bowser Clone Spine": {
    type: "block",
    perfect: "00:00:01.083",
    partialStart: "00:00:01.016",
    partialEnd: "00:00:01.400",
    video: "./resources/strong-bowser-clone-spine.mp4",
    poster: "./resources/strong-bowser-clone-spine.png",
    name: "Strong Bowser Clone Spine",
    info: "Just before the spine hits",
    note: "",
    frames: 6,
  },
  "Strong Geno Clone Attack": {
    type: "block",
    perfect: "00:00:01.366",
    partialStart: "00:00:01.300",
    partialEnd: "00:00:01.766",
    video: "./resources/strong-geno-clone-attack.mp4",
    poster: "./resources/strong-geno-clone-attack.png",
    name: "Strong Geno Clone Attack",
    info: "As the third star hits",
    note: "",
    frames: 10,
  },
  "Strong Mallow Clone Attack": {
    type: "block",
    perfect: "00:00:00.650",
    partialStart: "00:00:00.583",
    partialEnd: "00:00:01.083",
    video: "./resources/strong-mallow-clone-attack.mp4",
    poster: "./resources/strong-mallow-clone-attack.png",
    name: "Strong Mallow Clone Attack",
    info: "As Mallow's Cymbals clap together",
    note: "",
    frames: 11,
  },
  "Strong Mario Clone Attack": {
    type: "block",
    perfect: "00:00:01.200",
    partialStart: "00:00:01.133",
    partialEnd: "00:00:01.516",
    video: "./resources/strong-mario-clone-attack.mp4",
    poster: "./resources/strong-mario-clone-attack.png",
    name: "Strong Mario Clone Attack",
    info: "Just before Mario lands",
    note: "",
    frames: 6,
  },
  "Strong Peach Clone Attack": {
    type: "block",
    perfect: "00:00:00.483",
    partialStart: "00:00:00.416",
    partialEnd: "00:00:00.883",
    video: "./resources/strong-peach-clone-attack.mp4",
    poster: "./resources/strong-peach-clone-attack.png",
    name: "Strong Peach Clone Attack",
    info: "As Peach swings the Frying Pan down",
    note: "",
    frames: 10,
  },
  "Stumpet Backfire": {
    type: "block",
    perfect: "00:00:01.600",
    partialStart: "00:00:01.533",
    partialEnd: "00:00:01.883",
    video: "./resources/stumpet-backfire.mp4",
    poster: "./resources/stumpet-backfire.png",
    name: "Stumpet Backfire",
    info: "Before the rock hits",
    note: "",
    frames: 5,
  },
  "Stumpet Va Va Voom": {
    type: "block",
    perfect: "00:00:01.716",
    partialStart: "00:00:01.650",
    partialEnd: "00:00:02.016",
    video: "./resources/stumpet-va-va-voom.mp4",
    poster: "./resources/stumpet-va-va-voom.png",
    name: "Stumpet Va Va Voom",
    info: "Before the rock hits",
    note: "",
    frames: 5,
  },
  "Tentacle (Left) Slap": {
    type: "block",
    perfect: "00:00:00.766",
    partialStart: "00:00:00.700",
    partialEnd: "00:00:01.150",
    video: "./resources/tentacle-left-slap.mp4",
    poster: "./resources/tentacle-left-slap.png",
    name: "Tentacle (Left) Slap",
    info: "As the tentacle descends on you",
    note: "",
    frames: 12,
  },
  "Tentacle (Right) Slap": {
    type: "block",
    perfect: "00:00:00.566",
    partialStart: "00:00:00.500",
    partialEnd: "00:00:00.966",
    video: "./resources/tentacle-right-slap.mp4",
    poster: "./resources/tentacle-right-slap.png",
    name: "Tentacle (Right) Slap",
    info: "As the tentacle descends on you",
    note: "",
    frames: 11,
  },
  "Terra Cotta Sword": {
    type: "block",
    perfect: "00:00:01.516",
    partialStart: "00:00:01.450",
    partialEnd: "00:00:01.816",
    video: "./resources/terra-cotta-sword.mp4",
    poster: "./resources/terra-cotta-sword.png",
    name: "Terra Cotta Sword",
    info: "Right when the sword is vertical",
    note: "",
    frames: 5,
  },
  Thornet: {
    type: "block",
    perfect: "00:00:01.166",
    partialStart: "00:00:01.100",
    partialEnd: "00:00:01.483",
    video: "./resources/thornet.mp4",
    poster: "./resources/thornet.png",
    name: "Thornet",
    info: "Just before the projectile connects",
    note: "",
    frames: 5,
  },
  "Thropher Attack 1": {
    type: "block",
    perfect: "00:00:02.583",
    partialStart: "00:00:02.516",
    partialEnd: "00:00:02.950",
    video: "./resources/thropher-attack-1.mp4",
    poster: "./resources/thropher-attack-1.png",
    name: "Thropher Attack 1",
    info: "After the flurry of swings, while it holds a claw in the air",
    note: "",
    frames: 10,
  },
  "Thropher Attack 2": {
    type: "block",
    perfect: "00:00:01.716",
    partialStart: "00:00:01.649",
    partialEnd: "00:00:02.116",
    video: "./resources/thropher-attack-2.mp4",
    poster: "./resources/thropher-attack-2.png",
    name: "Thropher Attack 2",
    info: "Before the projectile makes contact",
    note: "",
    frames: 10,
  },
  "Valentina Attack": {
    type: "block",
    perfect: "00:00:00.799",
    partialStart: "00:00:00.733",
    partialEnd: "00:00:01.116",
    video: "./resources/valentina-attack.mp4",
    poster: "./resources/valentina-attack.png",
    name: "Valentina Attack",
    info: "When she begins to swing her hand",
    note: "",
    frames: 5,
  },
  "Whuhoh Bite": {
    type: "block",
    perfect: "00:00:01.466",
    partialStart: "00:00:01.400",
    partialEnd: "00:00:01.783",
    video: "./resources/whuhoh-bite.mp4",
    poster: "./resources/whuhoh-bite.png",
    name: "Whuhoh Bite",
    info: "When the mouth fully closes after the bite",
    note: "",
    frames: 5,
  },
  "Wiggler Ball": {
    type: "block",
    perfect: "00:00:01.666",
    partialStart: "00:00:01.599",
    partialEnd: "00:00:02.033",
    video: "./resources/wiggler-ball.mp4",
    poster: "./resources/wiggler-ball.png",
    name: "Wiggler Ball",
    info: "As projectile lands",
    note: "",
    frames: 8,
  },
  "Wiggler Slam": {
    type: "block",
    perfect: "00:00:01.050",
    partialStart: "00:00:00.983",
    partialEnd: "00:00:01.366",
    video: "./resources/wiggler-slam.mp4",
    poster: "./resources/wiggler-slam.png",
    name: "Wiggler Slam",
    info: "As Wiggler is slamming down",
    note: "",
    frames: 5,
  },
  "Will-o-Wisp": {
    type: "block",
    perfect: "00:00:02.283",
    partialStart: "00:00:02.216",
    partialEnd: "00:00:02.766",
    video: "./resources/will-o-wisp.mp4",
    poster: "./resources/will-o-wisp.png",
    name: "Will-o-Wisp",
    info: "As soon as the orb rises out of the ground",
    note: "",
    frames: 15,
  },
  "Zombone Attack": {
    type: "block",
    perfect: "00:00:01.383",
    partialStart: "00:00:01.316",
    partialEnd: "00:00:01.783",
    video: "./resources/zombone-attack.mp4",
    poster: "./resources/zombone-attack.png",
    name: "Zombone Attack",
    info: "As the mouth closes",
    note: "",
    frames: 10,
  },
};
